### ISSUE TITLE
Coördinatenpaar in conceptual-schemas wordt niet herkend in Imvertor

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#100]
Coördinatenpaar is opgenomen in conceptual-schemas, maar een verwijzing naar dit datatype levert in Imvertor de fout Unknown type "CoRdinatenpaar" op.

**Comment by WijnandvanRiel** [comment]
De oplossing om in conceptual-schemas.xml Coördinatenpaar te wijzigen naar CoRdinatenpaar werkt niet. Imvertor genereert nog steeds de zelfde fout.

**Comment by ArjanLoeffen** [comment]
Opgelost door naam normalisatie uit te zetten ("AsIs") voor BRO klassen en eigenschappen in conceptuele en logische modellen
