### ISSUE TITLE
Naam van detaildiagram in BRO-catalogus is overbodig

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#101]
Verzoek om de namen van BRO-detaildiagrammen niet over te nemen uit EA en niet te tonen in de catalogus

**Comment by ArjanLoeffen** [comment]
In de doc-rules file (folder docrules) is nu een parameter opgenomen:

> /doc-rules/image-purpose/show-caption

Deze is voor iedere owner bescbhikbaar, en kan yes/no zijn. Ik heb 'm voor BRO gezet op no. De captions vervallen hiermee.
Beschikbaar over een uurtje in 1.59.
