### ISSUE TITLE
Kardinaliteit wordt niet correct weergegeven in ReSpec

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#106]
In de respec catalogus van SFR zijn relaties met een kardinaliteit van 1..10 gemodelleerd. Deze worden niet weergegeven.
![image](https://user-images.githubusercontent.com/57146824/73831284-5cabfb80-4806-11ea-9476-404e2a0406f1.png)

**Comment by ArjanLoeffen** [comment]
Gefixed, beschikbaar op 13 febr.

**Comment by ArjanLoeffen** [comment]
Fixed. Probleem is tevens vervallen met het vervallen van het tonen van relaties in BRO catalogi.

**Comment by ArjanLoeffen** [comment]
@WijnandvanRiel , kunnen we deze sluiten?
