### ISSUE TITLE
To many  warnings for "is not part of the collection"

### ISSUE THREAD

**Issue by ThiesMesdag** [Imvertor/Imvertor-Maven#11]
The "is not part of the collection warning" is issued to often. When there is a generalisation with specialisations then you can choose to make either the generalisation a part of the collection or the specialisation classes. Both the generalisation and the specialisation as part of the collection should result in a warning.

So: 
When the generalisation is made part of the collection there should be a warning if also the specialisation classes are member of the collection. 

_"Both generalisation class and specialisation class are part of the collection"._

When not all specialisation classes are part of the collection there could be a warning:
''Not all  specialisation classes of "X" are part of the collection"

**Comment by ArjanLoeffen** [comment]
@ThiesMesdag Thies, speelt dit nog?

**Comment by kad-mesdat** [comment]
Ik denk het wel. Maar dat zouden we moeten testen. Maar 2017 is wel heel lang geleden. Dus het is geen "hot" issue.

**Comment by ArjanLoeffen** [comment]
Dank vier ik 'm af en kunnen we 'm later wellicht heropenen.
