### ISSUE TITLE
EA profielen zijn niet geschikt voor EA 15.*

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#118]
Dear Sparx people,
I tried to import a UML profile that has imported successfully in versions 12, 13 and 14 (as far as I can tell) into 1.51, but that failed.

antwoord:
The problem appears to be your use of brackets in the profile name "myprofile (NL)" which trips up EA. Round brackets are used for other reasons in profile items. In general, it is a good idea not to have punctuation of any type in profile or stereotype names. I tried renaming your profile to "myprofile" and it appeared to work OK.

**Comment by ArjanLoeffen** [comment]
Oplossing werkt niet. Mail gestuurd dd. 29 april 20.

**Comment by ArjanLoeffen** [comment]
De naam van het profiel wordt nu zonder speciale karakters  weggeschreven. Daarmee laadt het profiel weer goed in EA.  Echter, de weergave van de onderdelen van het profiel is niet correct. daarvoor moet EA opnieuw worden opgestart.

Daarmee sluit ik dit issue.

**Comment by rcdeboer** [comment]
@ArjanLoeffen Op http://www.armatiek.nl/Imvertor/wiki/Imvertor-EA-profiles staan volgens mij nog de profielen met speciale karakters. Inladen van Kadaster Grouping (NL) 0.9.ea-profile.xml in EA 15.2 (build 1554) geeft mij de foutmelding _Error parsing: Kadaster Grouping (NL) 0.9.ea-profile.xml_

Waar kan ik het profiel zonder speciale karakters vinden?

**Comment by ArjanLoeffen** [comment]
@rcdeboer deze profielen worden meegegeneeerd met een Imvertor run. Je vindt ze terug in de /ea folder. Ik zal de laatste profielen op de site updaten.
