### ISSUE TITLE
Tagged value Position correct afleiden

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#129]
Zie discussie "Imvertor: tagged value Position bij een logisch model" via mail.

![image](https://user-images.githubusercontent.com/12828217/92696430-24473f80-f34a-11ea-99ae-c0ce9d513a1a.png)

**Comment by ArjanLoeffen** [comment]
Dit lijkt een fout van de add-in. De SourceAssociation wordt gevuld met een associatie ID in de vorm {999-999} maar moet gevuld worden met EAID_999_999. Dit, omdat de @xml.id van de associatie in de supplier de vorm EAID_999_999 heeft.

![image](https://user-images.githubusercontent.com/12828217/92714016-f0751580-f35b-11ea-8a56-a9624f91e159.png)

**Comment by ArjanLoeffen** [comment]
@HanWelmer wil jij dit eens navragen?

**Comment by HanWelmer** [comment]
**In de XMI van het SFR conceptueelmodel (zie job ) zie ik 2 keer de waarde van bovenstaande SourceAssociation, op de regels 61177 en 61178 (bold is van mij):**

<UML:TaggedValue tag="$ea_src_xref_property" value="$XREFPROP=$XID={6716CAF8-DBC7-4980-93CE-7C23937A63B1}$XID...property$TYP;$VIS=Public$VIS;$PAR=0$PAR;$DES=@STEREO;Name=Relatierol;GUID={09814F38-7B4E-4fc0-9EFB-CFBBD224BF07};FQName=MIM-BRO Grouping (NL)::Relatierol;@ENDSTEREO;$DES;$CLT=**{CC68FC4C-8AF5-4dca-8F4D-40DDE0FF2373**}$CLT;$SUP=&lt;none&gt;$SUP;$ENDXREF;"/>
										<UML:TaggedValue tag="$ea_dst_xref_property" value="$XREFPROP=$XID={5A2FC142-7221-4456-B7D2-9183A54CD0E7}$XID;$NAM=Stereotypes$NAM;$TYP=connectorDestEnd property$TYP;$VIS=Public$VIS;$PAR=0$PAR;$DES=@STEREO;Name=Relatierol;GUID={09814F38-7B4E-4fc0-9EFB-CFBBD224BF07};FQName=MIM-BRO Grouping (NL)::Relatierol;@ENDSTEREO;$DES;$CLT={**CC68FC4C-8AF5-4dca-8F4D-40DDE0FF2373**}$CLT;$SUP=&lt;none&gt;$SUP;$ENDXREF;"/>


**In de XMI van het SFR logisch model (zie job ) zie ik 1 keer de waarde van bovenstaande SourceAssociation, op regel31463 (bold is van mij):**
<UML:TaggedValue tag="SourceAssociation" value="{**CC68FC4C-8AF5-4dca-8F4D-40DDE0FF2373**}" xmi.id="EAID_A20F05D7_D768_43c5_B637_1C8252C5CC94"/>

In beide gevallen dus zonder EAID_.

Het is mij overigens niet duidelijk of en wanneer EA een prefix voor een UUID plaatst. Ik zie in zowel het conceptueel model als het logisch model, op zowel de plaats waar een modelelement wordt gedeclareerd als op de plaats waar naar een modelelement wordt gerefereerd, UUIDs staan zonder prefix, met een prefix EAID_ of met een prefix EAPK_. Ik constateer wel dat UUIDs met een prefix EAPK_ ook voorkomen met een prefix EAID_.

**Comment by ArjanLoeffen** [comment]
Ik kijk maandag nog eens.

--
Arjan vanaf mobiel

Op vr 11 sep. 2020 08:33 schreef Han Welmer <notifications@github.com>:

**Comment by HanWelmer** [comment]
Hallo Arjan,

Bel me eventueel van te voren even voor een nadere mondelinge toelichting.

Prettig weekend,

Han Welmer.



Ir. H.J. (Han) Welmer
GEO Data & IT


M 06-1520.8740
E han.welmer@tno.nl<mailto:han.welmer@tno.nl>

Locatie<http://www.tno.nl/locaties/UT> Utrecht


[cid:image001.gif@01D68838.AF99D9D0]<http://www.tno.nl/>

Dit bericht kan informatie bevatten die niet voor u is bestemd. Indien u niet de geadresseerde bent of dit bericht abusievelijk aan u is toegezonden, wordt u verzocht dat aan de afzender te melden en het bericht te verwijderen. TNO aanvaardt geen aansprakelijkheid voor de inhoud van deze e-mail, de wijze waarop u deze gebruikt en voor schade, van welke aard ook, die verband houdt met risico's verbonden aan het elektronisch verzenden van berichten.

**Comment by ArjanLoeffen** [comment]
In de XMI van het conceptueel model treffen we aan:
![image](https://user-images.githubusercontent.com/12828217/93127347-05400900-f6ce-11ea-86dc-905f2ce64c5a.png)
Er wordt in het logisch model een trace geplaatst naar deze associatie. Maar dan in de vorm
{CC68FC4C-8AF5-4dca-8F4D-40DDE0FF2373} zoals in deze discussie getoond.
Ik vat dat op als een fout, maar ik zou het wel kunnen omzetten, als ik de regels ken en als jullie  het niet bij bellekens willen beleggen.

**Comment by HanWelmer** [comment]
Helaas ken ik de regels ook niet. Maar hieronder mijn waarnemingen.

De waarde CC68FC4C-8AF5-4dca-8F4D-40DDE0FF2373 (let op de min-tekens) in het logisch model verwijst naar de source rol of de target rol van een associatie in het conceptueel model met de tagged value $ea_src_xref_property of $ea_dst_xref_property".

logisch model:
tag="SourceAssociation" value="{CC68FC4C-8AF5-4dca-8F4D-40DDE0FF2373}".

conceptueel model: 
tag="$ea_src_xref_property" value="$XREFPROP=...$CLT={CC68FC4C-8AF5-4dca-8F4D-40DDE0FF2373}$CLT;..."
tag="$ea_dst_xref_property" value="$XREFPROP=...$CLT={CC68FC4C-8AF5-4dca-8F4D-40DDE0FF2373}$CLT..."

**Mijns inziens moet er verwezen worden naar het attribuut xmi.id van de associatie in de conceptueel model (let op de underscores en de EAID_ prefix in het voorbeeld).**

logisch model:
tag="SourceAssociation" value="EAID_CC68FC4C_8AF5_4dca_8F4D_40DDE0FF2373"

conceptueel model: 
xmi.id="EAID_CC68FC4C_8AF5_4dca_8F4D_40DDE0FF2373"

Wat ik probeer te zeggen is: kijk niet naar de prefix of de underscores vs min-tekens. Maar gebruik de juiste waarde bij het vullen van de tagged value sourceAssociation, namelijk de waarde van het attribuut xmi.id. Voor hetzelfde geld heb ik het fout en zit het probleem niet in het opslaan van de verwijzing maar in het volgen van de verwijzing. Hoe dan ook, traces voor relaties werken heel anders dan traces voor attributen.

**Comment by ArjanLoeffen** [comment]
De SourceAssociation target value is een "trace" naar de associatie, niet naar een source of target role. De trace ID vanuit het logisch model heeft de vorm {abc} (in de XMI). De ID van de associatie in het conceptueel model heeft de vorm EAID_abc (in de XMI).  
In de weergave van de rollen van de associatie wordt de associatie geïdentificeerd via $CLT als {abc}. Hier treedt dus verwarring op.

Het script had EAID_abc moeten genereren. We willen dit echter nu niet vervangen omdat daarmee bestaande modellen"omvallen".

Wat we moeten doen is de {abc} uit de SourceAsscociation tagged values aan het begin al omzetten  in EAID_abc. Daarmee wordt de trace weer actief.

Arjan neemt ook contact op met Geert Bellekens om de keuze die in het script is gemaakt toe te lichten.

**Comment by HanWelmer** [comment]
en in de {abc} moeten mintekens vervangen worden door underscores en moeten de curly braces worden verwijderd.

Voorbeeld:
sourceAssociation = {CC68FC4C-8AF5-4dca-8F4D-40DDE0FF2373}
wordt omgekat naar EAID_CC68FC4C_8AF5_4dca_8F4D_40DDE0FF2373

**Comment by GeertBellekens** [comment]
In EA hebben GUID's altijd het formaat {CC68FC4C-8AF5-4dca-8F4D-40DDE0FF2373}. Bij eender welk ander formaat zouden de links ook niet teruggevonden worden.

Enkel in de xmi exports worden deze tagged values omgezet naar het EAID_CC68FC4C_8AF5_4dca_8F4D_40DDE0FF2373 formaat. De transformatie is inderdaad vrij triviaal zoals Han aangeeft.
De reden waarom deze waarde niet is omgezet door de xmi export, is omdat EA de waarde van een tagged value beschouwt als inhoud of tekst. die wordt dus één op één behouden.

**Comment by ArjanLoeffen** [comment]
Okay, deze fix is doorgevoerd in 1.61.2.
