### ISSUE TITLE
Naamgeving GML bestanden

### ISSUE THREAD

**Issue by lennartvanbergen** [Imvertor/Imvertor-Maven#132]
We merken dat de bestandsnaam van de XSD met GML erin anders is dan bedoeld. Zou je dit willen rechttrekken met onderstaande specificatie? Het gaat om de **dikgedrukte** delen.

Graag in/vanaf 1.61 al. 

*****************************************************************************
Releasnotes bij de kadaster-gml.xsd 
*****************************************************************************
Created by: Lennart van Bergen 
Creation date: 30-7-2020

Last update by: Lennart van Bergen
Last update data: 30-7-2020

-----------------------------------------------------------------------------
Topic: Een kadaster profiel gebaseerd op voor GML 3.2.2. SF-2, in 1 kleine GML.XSD 
-----------------------------------------------------------------------------
Created by: 
Arjan Loeffen (Armantiek) 
Lennart van Bergen (Kadaster)
met hulp van Geonovum. 

Creation date: 30-7-2020

Reden: ter vervanging van GML 3.2.1 die niet meer gesuppotr wordt vanwege een bugfix, vandaar 3.2.2.
Reden: om een kleine subset van GML te kunnen gebruiken voor alleen de types die vallen onder SF-2.  

-----------------------------------------------------------------------------
Korte beschrijving gebruik 
-----------------------------------------------------------------------------
Handmatig: pak de zip uit naar je eigen XSD folder. Je krijgt dan een /gml folder op het ROOT niveau van je XSD folder. 

Genereren: dit is de default set die gegenereerd wordt vanuit Imvertor, vanaf versie 1.61. 

Importeer vervolgens de XSD in je eigen XSD die hoort bij je eigen XSD model en kies GML types. Dit hoort altijd een element te zijn die eindigt op PropertyType. 

De gmlsfProfile folder is optioneel. Deze is er zodat je bij een levering een hele kleine XML meeleveren met daarin of de GML die je levert aan SF level 0, 1 of 2 voldoet. Dat is netjes. 

-----------------------------------------------------------------------------
Wat is het?
-----------------------------------------------------------------------------

De schemas in deze folder zijn gebaseerd op GML  
zoals gepubliceerd op 
- specificatie: https://www.ogc.org/standards/gml 
- schemas: http://schemas.opengis.net/gml/
- versie 3.2.2.

Deze schema's zijn vervolgens via een profiel teruggebracht naar alleen de elementen en types die nodig zijn voor het simple features profile SF2, voor GML types die we voorzien dat deze bij het Kadaster nodig zouden kunnen zijn, in het bijzonder voor de geo basisregistraties. Zodat we bij het Kadaster ervoor kunnen kiezen om een kleine XSD set kunnen gebruiken. 

Deze set is ook met Imvertor www.imvertor.org te genereren dat alle GM types van SF2 te gebruiken in een informatiemodel. 

Deze set komt standaard mee met een Imvertor generatie (publish). 

Imvertor informatie: 

createxmlschema         = yes
createxmlschemavariant  = Kadaster
mapping                 = *
creategmlprofile        = *

Die laatste twee parameters, daar kan je mee aangeven welke GML schema's je wilt.

**Stuurparameters en effect op het GML bestand qua naamgeving**: 

mapping                 = NEN3610_GML322_ENV
creategmlprofile        = no

Hele GML 3.2.2. wordt mee gegenereerd.
**XSD naam: gml.xsd**
Bv. zie GML zelf. 

--

mapping                 = NEN3610_GML322_ENV
creategmlprofile        = yes

-> Er wordt een model specifiek profiel gegenereerd voor het aangeboden model. 
**XSD naam: `<modelnaam>`-gml.xsd** 
Bv. imkad-gml.xsd 
 
--

mapping                 = NEN3610_GML322PROFILE_ENV
creategmlprofile        = no

-> Er wordt een standaard profiel meegeleverd, degene in deze folder. 
**XSD naam: kadaster-gml.xsd** 
DIT IS DE DEFAULT.

--

mapping                 = NEN3610_GML322PROFILE_ENV
creategmlprofile        = yes

-> Er wordt op basis van het standaard profiel een model-specifiek profiel meegeleverd. Dit is wel interessant als je andere documentatie wenst op te nemen in het standaard GML profiel. 
**XSD naam:  `<modelnaam>`-gml.xsd**

--

Merk op dat als je andere generatie settings neemt, dat het GML bestand een andere naam krijgt. Je XML of GML zal echter nog steeds aan de nieuwe XSD voldoen. Ze zijn onderling uitwisselbaar. Dat is ook de bedoeling. Als er vragen over komen kan je dus zeggen dat er inhoudelijk niks veranderd is.

**Comment by ArjanLoeffen** [comment]
Is verdubbeling van #131. We gaan hier verder.
