### ISSUE TITLE
Verbeteringen catalogusformaat

### ISSUE THREAD

**Issue by lvdbrink** [Imvertor/Imvertor-Maven#133]
Bij het werken aan IMGeluid (in Geonovum omgeving van Imvertor) hebben we een aantal wensen voor het catalogusformat: 
-	“Gestruktureerde datatypen” koptekst van de paragraaf met gestructureerde datatypen > “Gestructureerde” graag schrijven met een “c”. Zie bv https://geonovum.github.io/IMG/#gestruktureerde-datatypen
-	Bovenaan hfd Inhoud van waardenlijsten graag "deze tekst is normatief" verwijderen. https://geonovum.github.io/IMG/#lis
-	In de tabellen graag de kolomheader “Formaat” wijzigen naar “Type”. Dit komt voor bij de volgende tabellen :
    - Overzicht attributen
    - Overzicht data elementen
    - Bij Objecttype details in de tabellen per attribuut, maar hier is het geen kolomheader maar een kopje in cel 1 van een rij.
    - Idem bij Data element details
-	De tekst “Indicatie kardinaliteit” graag aanpassen naar “Kardinaliteit”. Dit komt voor in de detail tabellen van attributen en data elementen. 
-	De kolomheader “card” graag aanpassen naar “Kardinaliteit”. Dit komt voor in de overzichtstabellen van attributen en data elementen.
-	In https://geonovum.github.io/IMG/#cat begint de beschrijving van het Informatiemodel Geluid met een aantal diagrammen. Is het mogelijk om elk diagram in een sectie te zetten met als titel de diagramnaam (Name veld)?

**Comment by ArjanLoeffen** [comment]
Uitgevoerd. Wat betreft de laatste opdracht, ik heb er van gemaakt:
![image](https://user-images.githubusercontent.com/12828217/94842628-e8b90600-041b-11eb-922a-92ca93b8556f.png)

**Comment by lvdbrink** [comment]
Dat was inderdaad wat ik bedoelde!

**Comment by lvdbrink** [comment]
Getest; Voor gestructureerde datatypen (https://geonovum.github.io/IMG/#gestructureerde-datatypen) wordt nog wel “Card” gebruikt in de tabel ipv “Kardinaliteit”. 

Verder goed.

**Comment by ArjanLoeffen** [comment]
Nu hersteld, morgen beschikbaar.

**Comment by wilkoquak** [comment]
Vandaag een Catalogus gemaakt met daarin nog steeds 'Indicatie Kardinaliteit:

![afbeelding](https://github.com/Imvertor/Imvertor-Maven/assets/2814052/8ce25e11-9fbf-47c1-a203-e3776fd5975d)

Ik heropen dit issue...

**Comment by ArjanLoeffen** [comment]
Okay, hersteld :-)
