### ISSUE TITLE
Nog niet eerder tegengekomen JSON foutmelding 

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#135]
Het aanbieden van een basismodel levert de volgende fout op:
![imvertor json-fout](https://user-images.githubusercontent.com/57146824/94814308-72a3a780-03f9-11eb-8d3b-cafd252fec78.jpg)
Ik ben hem nog niet eerder tegengekomen en weet ook niet waar ik moet zoeken voor een oplossing.

**Comment by ArjanLoeffen** [comment]
Kan het zijn dat je géén documentatie samenstelt maar wél Json concepten wilt samenstellen? Dat is nu nog niet mogelijk, dus als je de documentatie niet samenstelt moet je ook createjsonconcepts op false zetten. 
De reden voor deze melding is dat in de documentatie-slag de lijsten worden uitgelezen (uit externe bron). En die lijsten hebben we nodig in de Json concepten-slag. 

Geef aan als je deze twee functies uit elkaar wilt laten halen.

**Comment by WijnandvanRiel** [comment]
De twee functies hoeven wat mij betreft niet uit elkaar gehaald te worden. De toevoeging aan de properties-file: createjsonconcepts = false,  is afdoende
