### ISSUE TITLE
geen Unit of Measure (UOM) in XSD's

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#136]
Na afleiding van logisch model uit conceptueel model zijn de tagged values die de uom vormen niet aanwezig in de XSD's

**Comment by ArjanLoeffen** [comment]
Het type in het conceptual schema moet "Measure" zijn, en het package GML3, óf
het type in het conceptual schema moet "Measure" zijn, en het package Ro_BRO. Check dat eerst even.

Anders graag een testgeval.

**Comment by WijnandvanRiel** [comment]
Eigenlijk zijn beide het geval.
Het eerste is het geval: het type in het conceptual schema is "Measure" zijn, en het package is GML3.
Daarnaast hebben we een BRO_Common package/map in conceptual-schema's waar het type wellicht verkeerd is. We hebben nu een wijziging doorgevoerd, die we morgen gaan testen.

**Comment by WijnandvanRiel** [comment]
Fout gevonden: type was MeasureType ipv Measure
