### ISSUE TITLE
Aanpassing tags in Enterprise Architect UML SIM profile conform MIM 1.1

### ISSUE THREAD

**Issue by MaxWelling7** [Imvertor/Imvertor-Maven#141]
In het profiel voor IHW (IHWSIM Grouping NL) komen tags voor die niet bij de betreffende stereotypes voorkomen zoals beschreven in [MIM 1.1](https://docs.geostandaarden.nl/mim/vv-st-mim-20200225/#specificatie-metagegevens-voor-datatypen).

Verzoek om de zichtbaarheid van tags binnen Enterprise Architect conform MIM 1.1 te maken.
Bijgevoegd een excel waarin staat aangegeven welke wijzigingen noodzakelijk zijn: 
[Imvertor Wijziging tags in UML profiel IHWSIM Grouping NL.xlsx](https://github.com/Imvertor/Imvertor-Maven/files/5457526/Imvertor.Wijziging.tags.in.UML.profiel.IHWSIM.Grouping.NL.xlsx)

**Comment by ArjanLoeffen** [comment]
De zichtbaarheid is het gevolg van aanwezigheid in metamodel, en/of in notes field. In bijgevoegde excel is aangegeven:

- Rood = aanpassing niet doorgevoerd
- Groen = aanpassing doorgevoerd, tagged value verwijderd/toegevoegd in metamodel
- Geel = aanpassing doorgevoerd, tagged value blijft bestaan, maar niet zichtbaar in profiel.

[Imvertor.Wijziging.tags.in.UML.profiel.IHWSIM.Grouping.NL.xlsx](https://github.com/Imvertor/Imvertor-Maven/files/5559482/Imvertor.Wijziging.tags.in.UML.profiel.IHWSIM.Grouping.NL.xlsx)

**Comment by ArjanLoeffen** [comment]
Aanpassingen zoals beschreven doorgevoerd in 1.61.1

**Comment by ArjanLoeffen** [comment]
Omdat verwarring optreedt hebben we besloten de beschreven aanpak alleen uit te voeren als is expliciet opgegeven dat de tagged values niet in profiel moeten komen als er al een notes field voor is. 

De eerste aanpassing is dus teruggedraaid; keuze om via notes of via een tv info in te voeren ligt bij de analist, tenzij dit als een owner-specifieke parameter is aangegeven:

> ea-omit-tv-when-notes-field-exists

De waarde no/nee betekent: nooit weglaten uit EA profiel/toolbox.

Hiermee sluit ik dit issue omdat er ook niet eerder verdere reacties op waren.
