### ISSUE TITLE
Imvertor publicatie SIM Uitgebreid: onterechte waarschuwing bij data element ontbreken Herkomst

### ISSUE THREAD

**Issue by MaxWelling7** [Imvertor/Imvertor-Maven#142]
Bij het publiceren van een SIM model met daarin classes met stereotype _Gestructureerde datatype_ data worden waarschuwingen gegeven over het ontbreken van de _Herkomst_ van _Data elementen_.

Volgens de definitie van Data element in [MIM 1.1](https://docs.geostandaarden.nl/mim/vv-st-mim-20200225/#specificatie-metagegevens-voor-datatypen) is de Herkomst niet als aspect opgenomen. Graag deze controle verwijderen.

**Comment by ArjanLoeffen** [comment]
De tagged value was al geconfigureerd in stelselcatalogus configuratie (SBR) waar  IM 1.0 en MIM 1.1 op teruggaan:

SBR ← MIM 1.0 ← MIM 1.1

Vraag is of herkomst bij al deze metamodellen kan worden verwijderd?
