### ISSUE TITLE
Vaste GML 3.2.2 XMI opnemen

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#144]
In de verwerking van modellen die naar GML (en andere) modelconstructies verwijzen (zoals GM_Surface etc.) treedt er soms ambiguïteit op. Imvertor is niet in staat om vast te stellen welke GM_Surface bedoeld is. De enige informatie die het extra meekrijgt is de EA GUID. Daar houdt het dan aan vast: GM_Surface + GUID is dan een unieke identificatie van dat element, en de verwerking ervan in bijv. XSD's.

Er moet dus voor dat soort gevallen een vaste XMI worden gebruikt. Deze XMI (die op zich niet afhankelijk is van een specifieke GML versie) kan beschikbaar worden gesteld in de Imvertor repository. Dus: Ophalen uit de repository, inladen in je eigen EA omgeving, en vanaf dat moment verwijzen daar die constructies.

**Comment by lennartvanbergen-kadaster** [comment]
Zou je de link willen toevoegen naar de gepubliceerde XMI van het EA package dat we moeten gebruiken voor GML 3.2.2?

**Comment by ArjanLoeffen** [comment]
Zie https://github.com/Imvertor/Imvertor-Maven/tree/master/src/main/resources/input/Kadaster/eap voor ons voorstel voor standaard GML3 en MIM11 datatypen.

**Comment by ArjanLoeffen** [comment]
NB. In de configuratie voor Kadaster wordt vanuit GML3 (ISO 19136) ook overgenomen:

![image](https://user-images.githubusercontent.com/12828217/100209091-bef6f980-2f09-11eb-915b-6eb72d4b58a9.png)

Ik denk dat dit weg moet; Kadaster (Intern) verwijst nooit naar GML primitieve typen zoals deze, maar tikt die zelf in. In de externe modellen conform MIM wordt verwezen naar de MIM datatypen, dus uit het externe MIM11 package.

Mijn voorstel is dus deze primitieve typen uit de conceptual map te verwijderen. Graag jullie Okay.

**Comment by ThiesMesdag** [comment]
Eens met de analyse, dus wat mij betreft kunnen ze uit de GML3 package.

**Comment by lennartvanbergen-kadaster** [comment]
Oke m.b.t. de types 

@ArjanLoeffen ik zie als link naar de GML package een EAP en geen XMI. Ik zou graag de XMI willen zien als target van de link, want dan kan ik tegen iedereen vertellen: download die. Ipv. open de EAP, doe een export, gebruik die XMI.

**Comment by ArjanLoeffen** [comment]
Het standaard MIM11 package voor Kadaster is:
https://github.com/Imvertor/Imvertor-Maven/blob/master/src/main/resources/input/Kadaster/eap/Kadaster-MIM11.xmi

Het standaard GML package voor Kadaster is:
https://github.com/Imvertor/Imvertor-Maven/blob/master/src/main/resources/input/Kadaster/eap/Kadaster-GML3.xmi

Verzoek aan Kadaster is deze package te importeren en te gebruiken bij referenties naar MIM11 en GML constructs.

**Comment by lennartvanbergen-kadaster** [comment]
Na download lukt het me niet om deze files in te lezen... er komen parsing errors. 

Het bestand heet bij mij: Kadaster-MIM11.xmi maar ook als Kadaster-MIM11.xmi lukt dit niet helaas. 

En heeft de volgende content: 

<?xml version="1.0" encoding="windows-1252"?>
<XMI xmi.version="1.1" xmlns:UML="omg.org/UML1.3" timestamp="2020-11-25 11:06:38">
	<XMI.header>
		<XMI.documentation>
			<XMI.exporter>Enterprise Architect</XMI.exporter>
			<XMI.exporterVersion>2.5</XMI.exporterVersion>
		</XMI.documentation>
	</XMI.header>
	<XMI.content>
		<UML:Model name="EA Model" xmi.id="MX_EAID_A76425DB_C2F6_443f_8C73_33356AFEB13E">
			<UML:Namespace.ownedElement>
				<UML:Class name="EARootClass" xmi.id="EAID_11111111_5487_4080_A7F4_41526CB0AA00" isRoot="true" isLeaf="false" isAbstract="false"/>
				<UML:Package name="MIM11 Primitieve datatypen" xmi.id="EAPK_A76425DB_C2F6_443f_8C73_33356AFEB13E" isRoot="false" isLeaf="false" isAbstract="false" visibility="public">
					<UML:ModelElement.stereotype>
						<UML:Stereotype xmi.idref="EAID_C4635107_D8EF_4ff5_9984_B6A5D0FAE491"/>
					</UML:ModelElement.stereotype>
					<UML:ModelElement.taggedValue>
						<UML:TaggedValue tag="documentation" value="Dit zijn de &quot;gedeclareerde primitieve datatypen&quot; zoals in MIM1.1 geformuleerd. In modellen kan men eigen primitieve datatypen aanmaken die een specialisatie vormen van deze typen. &#xA;&#xA;Deze 11 typen zijn alle opgenomen in de Imvertor MIM11-MAP, welke wordt geimporteerd door de zgn. &quot;conceptual-schemas&quot;.&#xA;&#xA;LET OP: Deze typen worden alleen correct herkend wanneer een integrale kopie (met behoud van identifiers) wordt overgenomen in het model van een toepassing.  "/>

en verder ...

**Comment by ArjanLoeffen** [comment]
Je moet naar dat file gaan, in github, en de ruwe versie downloaden: rechter muisknop op:
![image](https://user-images.githubusercontent.com/12828217/104470237-cb1e3f80-55b9-11eb-9361-e9b3752fde1b.png)

Deze versie laad je in EA. Zojuist getest, werkt.

**Comment by kad-mesdat** [comment]
Waar/ hoe laad jij die in EA?

**Comment by ArjanLoeffen** [comment]
Publish / Import XML / Import package from XMI

**Comment by lennartvanbergen-kadaster** [comment]
Ah, ik zie het al. 

> Het standaard MIM11 package voor Kadaster is:
https://github.com/Imvertor/Imvertor-Maven/blob/master/src/main/resources/input/Kadaster/eap/Kadaster-MIM11.xmi

Ik had verwacht de MDG daar te vinden om die in te laden via import MDG. Maar wat er staat bij de _datatypen_.

**Comment by lennartvanbergen-kadaster** [comment]
Ja, helemaal goed zo, werkt inderdaad. Thanks!
