### ISSUE TITLE
Pas EA profile aan, wordt EA "toolbox"

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#146]
Op dit moment levert Imvertor een EA profile. Dit kan echter beter worden omgezet in een toolbox, die intuitiever kan worden ingezet in EA. 

Vaststellen of we het profile aanpassen zodat het een toolbox wordt, of dat beide naast elkaar moeten kunnen worden opgevraagd.

Nb. Het is dus mogelijk een complete toolbox te laten genereren op MIM11 en op klant-specifieke modellen (o.a. wanneer afgeleid van MIM maar ook van eerdere metamodellen).

**Comment by melsk-r** [comment]
Een MDG bestand bestaat over het algemeen uit meerdere delen:
* Een profile deel
* Een toolbox deel
* Een diagram deel

Om je daar wat inzicht in te geven heb ik een [handleiding voor het maken van een MDG](https://github.com/Imvertor/Imvertor-Maven/files/5628693/Handleiding.maken.MDG.pdf) bijgevoegd waarin staat beschreven hoe ik tot nu toe zo'n MBG bestand maakte.
Bij VNG Realisatie maken we wel alle 3 de delen aan in het MDG bestand maar volgens gebruiken we daarvan alleen het profile en toolbox deel. Ik zou eerlijk gezegd ook niet weten wat ik met het diagram deel zou moeten doen.

Naar mijn mening moet in het MDG bestand dus minimaal de eerste 2 delen zitten.

**Comment by ArjanLoeffen** [comment]
We hebben vandaag een uitbreiding doorgevoerd op de resultaten van Imvertor. We bieden nu ook de mogelijkheid om een complete EA Toolbox te genereren, welke kan worden ingeladen via MDG Technologies (beschrijving volgt). Effect hiervan is bijvoorbeeld het volgende:
![image](https://user-images.githubusercontent.com/12828217/100888888-df4d2800-34b6-11eb-8a1f-2d858fd73058.png)
Modellen kunnen op deze manier intuïtief en gecontroleerd worden opgebouwd. De indeling en naamgeving is in te stellen, en vereist wellicht nog wat overleg. 
Maar de eerste start is nu in samenwerking met VNG Realisatie gemaakt.
