### ISSUE TITLE
Verbeterde weergave van Relaties in ReSpec catalogus

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#147]
Verzoek voor een verbeterde tekstuele weergave van Relaties tussen entiteiten

**Comment by ArjanLoeffen** [comment]
De relaties zijn bijgevoegd voor BRO aan het einde van de lijst van attributen.
Er is geen visueel onderscheid tussen relaties en attributen in de TOC; daarvoor moet je naar de details toe.
Wordt meegenomen in Imvertor 1.62.2, van 12 dec.

**Comment by WijnandvanRiel** [comment]
Bedankt voor het uitwerken. 
Hier een paar eerste bevindingen: 
1.	De target van de relatie wordt niet goed weergegeven. 
 
![image](https://user-images.githubusercontent.com/57146824/104019884-9b87c580-51bc-11eb-982a-4d900355fe7d.png)

Moet conform EA worden.
2.	 Bij relaties worden –Definitie -- wel, maar --regels-- en --Regels IMBRO/A-- niet overgenomen in de catalogus. 
3.	Als objecten een attribuut hebben met als stereotype gegevensgroep, wordt deze in de catalogus weergegeven als association met ook alle tagged values van een relatie. Bijv:
 
![image](https://user-images.githubusercontent.com/57146824/104019910-a8a4b480-51bc-11eb-922b-3ff476c2d6d0.png)

Wordt in de catalogus beschreven als
 
![image](https://user-images.githubusercontent.com/57146824/104019937-b2c6b300-51bc-11eb-94dc-bfe3010068c7.png)

 
Dit moet worden: Type gegeven - Gegevensgroep 
4.	Bij Gegevensgroepen worden wel --Regels-- en andere tv’s getoond, maar geen --Regels IMBRO/A--

**Comment by ArjanLoeffen** [comment]
Waar kan ik dit "live" op testen?

**Comment by WijnandvanRiel** [comment]
Hoi Arjan,
De bevindingen komen uit FRD en GUF.
Annita is bezig met GUF en ik met FRD. Voor FRD heb ik zojuist een job gedraaid: 2021-01-08-16-04-50-000 (armatiek.nl)<https://imvertor.armatiek.nl/imvertor-executor/dashboard/app?job=2021-01-08-16-04-50-000>
Kun je daar mee uit de voeten?

Met groet,
Wijnand

**Comment by ArjanLoeffen** [comment]
Okay, lijkt goed onder 1.63.0. Graag even speciaal voorbeeld geven van IMBRO/A regels issue.

**Comment by WijnandvanRiel** [comment]
Goedemorgen Arjan,
Hoe komen wij aan  1.63.0. Bij het aanbieden aan Imvertor krijgen we ook al een Warning over deze versie, maar ik zie hem nog niet beschikbaar in de EA-plugin settings.
Met groet,
Wijnand

**Comment by ArjanLoeffen** [comment]
Is nu gecorrigeerd. De laatste versie beschikbaar in de SAAS is nu 1.,63.

**Comment by WijnandvanRiel** [comment]
Het is nog niet helemaal correct: de regels en toelichting op relaties worden nog niet weergegeven in de catalogus.

**Comment by WijnandvanRiel** [comment]
En kan het woord Source vervangen worden in Bron en Target in Doel?

**Comment by ArjanLoeffen** [comment]
Regels en regels IMBRO/A zijn gedefinieerd op relatierol, niet op relatie.  Regels komen goed door.
Ik zie dat IMBRO/A op rol nog niet doorkomt; dat herstellen we. Beschikbaar in 1.63.0 van 24 jan.

**Comment by ArjanLoeffen** [comment]
Bron en doel zijn nu voor BRO zo opgenomen.

**Comment by WijnandvanRiel** [comment]
#147 Omdat we zoals je ook al aangaf uitgaan van de relatierol, zou in de header van dit gegeven de ‘Relatierol naam’ moeten bevatten.  
Dus in onderstaand voorbeeld zou ‘4.3.3.4 bevat’ moeten worden ‘4.3.3.4 gerelateerdeOntwerpoppervlakteInfiltratie’. 
![Picture3](https://user-images.githubusercontent.com/57146824/105708783-33074b00-5f15-11eb-81c9-b729e7be0987.jpg)
Is dat te realiseren?

**Comment by WijnandvanRiel** [comment]
Graag ook de volgorde in de catalogus wijzigen in Entiteiten, attributen, gegevensgroepen, relaties. De laatste twee staan nu omgekeerd

**Comment by ArjanLoeffen** [comment]
De naam van de relatie rol is nu opgenomen in de TOC en als header zoals gevraagd.

**Comment by ArjanLoeffen** [comment]
In overleg met @Thijs Knapen is besloten dat voor gegevensgroepen toch óók de tagged value Regels IMBRO/A  moet worden getoond. 

We vatten dit op als een fix, en zetten deze in de master.

**Comment by thijs** [comment]
Check aub dat je de juiste @ gebruikt. @thijs is niet de Thijs die je denk
dat het is!

**Comment by ArjanLoeffen** [comment]
In overleg met Thijs Knapen is besloten dat voor gegevensgroepen toch óók de tagged value Regels IMBRO/A moet worden getoond.

We vatten dit op als een fix, en zetten deze in de master.
