### ISSUE TITLE
Verzoek voor een verbeterde tekstuele weergave van gegevensgroepen 

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#148]
Verzoek voor een verbeterde tekstuele weergave van Gegevensgroepen in de respec-catalogus

**Comment by ArjanLoeffen** [comment]
Gegevensgroep wordt nu als Entiteit weergegeven:

![image](https://user-images.githubusercontent.com/12828217/101909496-dac2f680-3bbd-11eb-94df-8fe80be83392.png)

Hier kan een beteren naar worden geplaatst, bijv. Gegevensgroeptype, maar dat willen de juristen misschien niet want dan rakn ze van slag. Graag suggesties.

**Comment by WijnandvanRiel** [comment]
De weergave als entiteit ziet er goed uit. Alleen: 
•	De regels bij gegevensgroepen en gegevensgroeptype worden niet getoond. Deze zijn volgens afspraak opgenomen in de Element notes. 
•	De IMBRO/A regels bij gegevensgroepen en gegevensgroeptypes worden nog niet getoond.

**Comment by ArjanLoeffen** [comment]
Ik zie dat alle regels in de genoemde constructies wél worden weergegeven. Alleen bij gegevensgroep wordt niet Regels IMBRO/A herkend, conform metamodel. Dus ik denk dat ik niets hoef aan te passen?

Kun je een voorbeeld geven van waar het mis gaat?

**Comment by WijnandvanRiel** [comment]
#148 De regels IMBRO/A laten we schieten omdat we nu niet meer het profiel willen gaan aanpassen. We gaan dit anders oplossen. 
Bij de gegevensgroepen staan nog wel een paar dingen die niet in thuis horen bij een gegevensgroep (Relatiesoortnaam, Relatierol naam en Bron), maar bij een relatie:
![Picture4](https://user-images.githubusercontent.com/57146824/105718507-95fedf00-5f21-11eb-90f4-4a78028a6653.jpg)
Kun je die er nog uit halen? 
En is er een mogelijkheid om bij Doel een link te leggen naar het Gegevensgroeptype, vergelijkbaar met de link naar een domeintabel?

**Comment by WijnandvanRiel** [comment]
Graag ook de volgorde in de catalogus wijzigen in Entiteiten, attributen, gegevensgroepen, relaties. De laatste twee staan nu omgekeerd

**Comment by ArjanLoeffen** [comment]
Opeenvolging aangepast. Hiermee denk ik dit issue te hebben afgerond.

**Comment by WijnandvanRiel** [comment]
Graag een ander begrip gebruiken voor Doel, 'Gegevensgroeptype' zou beter zijn
![image](https://user-images.githubusercontent.com/57146824/111495485-b425d600-873f-11eb-9f31-0081276a76aa.png)

**Comment by ArjanLoeffen** [comment]
Is gedaan. Morgen beschikbaar.

**Comment by WijnandvanRiel** [comment]
Is het mogelijk om het Doel van de gegevensgroep als hyperlink naar het gegevensgroeptype te presenteren?

**Comment by ArjanLoeffen** [comment]
Ja dat kan maar wil je dat wel? Volgens mij doe je dat soort links nergens, alleen naar waardenlijsten, toch?

**Comment by WijnandvanRiel** [comment]
Als we het niet zouden willen, zouden we het niet vragen. Sommige gegevensgroepen worden op meerdere plekken gebruikt, in de respec-catalogus staat dan maar 1-maal het gegevensgroeptype en met de link verwijs je daar naar toe. Idd, vergelijkbaar met de waardenlijst.

**Comment by WijnandvanRiel** [comment]
Kan in de tekstuele weergave van de gegevensgroep ook de tagged value Materiele historie opgenomen worden, vergelijkbaar met attributen?

**Comment by ArjanLoeffen** [comment]
Ik heb beide aanpassingen gedaan. Beschikbaar per 21/5 in 1.64.
