### ISSUE TITLE
Error: Notes field "Rules" not recognized, and skipped 

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#149]
Bij het aanbieden van een logisch model voor de BRO worden niet alle attribute-notes herkend. Bij de entiteit ObjectHistory bij de attributen startDateObject en endDateObject zijn in het Notes veld waarden opgenomen voor de tagged values Definition, Rules en Description. Vergelijkbaar met de notes bij attributen uit een conceptueel model.
Aanbieden geeft de volgende melding: Notes field "Rules" not recognized, and skipped Imvert2canonical.xsl / nl.imvertor.common.Messenger
zie Job: 2020-12-04-09-37-59-344

**Comment by ArjanLoeffen** [comment]
Notitie velden herkend voor logische modellen zijn: Name, Definition, Description.
Notitie velden voor conceptuele modellen zijn: Naam, Definitie, Toelichting, Omschrijving (uit MIM 1.0 profiel overgenomen) en regel, Regels IMBRO/A, Domein IMBRO/A, Reden geen waarde, Populatie.
Geef maar aan wat er moet veranderen.

**Comment by WijnandvanRiel** [comment]
we gaan dit op een andere manier oplossen

**Comment by WijnandvanRiel** [comment]
we gaan dit op een andere manier oplossen
