### ISSUE TITLE
Weergave van de relatienaam plus targetnaam

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#153]
Is er een mogelijkheid om achter de naam van de relatie ook de naam van de target te plaatsen 
Dit zou er dan als volgt uit kunnen zien (voorbeeld uit FRD):
5.3.5.3 heeft
5.3.5.4 heeft
Dat zou dan worden:
5.3.5.3 heeft Elektromagnetische meetmethode
5.3.5.4 heeft Geo-ohmkabel meetmethode

**Comment by ArjanLoeffen** [comment]
Waar moet die constructie komen? Je verwijst naar iets dat ik niet ken: "5.3.5.3 heeft".

**Comment by WijnandvanRiel** [comment]
Zou de header (paragraaf titel) van dit gegeven de ‘Relatierol naam’ kunnen worden?

**Comment by ArjanLoeffen** [comment]
Gedaan. In 1.63.1.
