### ISSUE TITLE
constructen voor externe standaarden in conceptual schema's leiden tot step-level error

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#158]
**Huidige situatie:**
In BRO conceptual schemas zijn de constructen voor externe standaarden opgenomen in een cs:Map met een cs:id, cs:namespace, cs:location en een cs:release, bijvoorbeeld voor INSPIRE-SOIL

```
<cs:Map>
--
   <cs:id>INSPIRE-SOIL</cs:id>
   <cs:namespace>http://inspire.ec.europa.eu/</cs:namespace>
   <cs:desc>Links to the INSPIRE Soil   cataloque and schemas.</cs:desc>
   <cs:location>http://inspire.ec.europa.eu/schemas/so/4.0/Soil.xsd</cs:location>
   <cs:phase>3</cs:phase>
   <cs:version>1.0</cs:version>
   <cs:release>4.0</cs:release>
```

Bij het genereren van berichtschema's zoekt Imvertor 'lokaal' in de mappenstructuur naar de xsd's o.b.v. combinatie cs:id, cs:namespace, cs:location en cs:release. Deze xsd’s moeten in de Github repository opgenomen zijn in de volgende structuur:
«prefix»/xsd/«namespace zonder http:// en tot eerste back-slash»/«cs:id-cs:release»/«cs:location vanaf de namespace» ,dus bijvoorbeeld: 
_Imvertor-Maven/src/main/resources/input/BRO/xsd/inspire.ec.europa.eu/INSPIRE-SOIL-4.0/schemas/so/4.0/Soil.xsd_
waarin 

```
«prefix»                          = Imvertor-Maven/src/main/resources/input/BRO/
«afgekapte namespace»               = inspire.ec.europa.eu
«cs:id>>-<<cs:release»                = INSPIRE-SOIL-4.0
«cs:location vanaf de namespace»  = schemas/so/4.0/Soil.xsd
```
Een step-levelsystem treedt op als combinatie «cs:id-cs:release» niet wordt gevonden, bijvoorbeeld als Imvertor-Maven/src/main/resources/input/BRO/xsd/inspire.ec.europa.eu/INSPIRE-SOIL-4.0 niet wordt gevonden.

**Probleem**:
In de BRO conceptual schemas zijn de constructen van ISO-19115 opgenomen in twee eigen «cs:Map» elementen: cs:id GEX10 en cs:id CIT10. Dat komt omdat deze GEX10 en CIT10 een eigen XSD-bestand, een eigen namespace en eigen location hebben.

```
<cs:Map>
--
  <cs:id>GEX10</cs:id>
  <cs:namespace>http://standards.iso.org/iso/19115/-3/gex/1.0</cs:namespace>
  <cs:desc>Extent   information</cs:desc>
  <cs:location>http://standards.iso.org/iso/19115/-3/gex/1.0/gex.xsd</cs:location>
  <cs:phase>3</cs:phase>

<cs:version>1.0</cs:version>
--
<cs:release>2006</cs:release>
 
<cs:id>CIT10</cs:id>
<cs:namespace>http://standards.iso.org/iso/19115/-3/cit/1.0</cs:namespace>
<cs:desc>Citation and responsible party   information</cs:desc>
<cs:location>http://standards.iso.org/iso/19115/-3/cit/1.0/cit.xsd</cs:location>
<cs:phase>3</cs:phase>
<cs:version>1.0</cs:version>
<cs:release>2006</cs:release>

```
De locatie in de Github repository van xsd's voor ISO19115 staat onder xsd/standards.iso.org/ISO19115-2006. Bij het generen van berichtschema's treedt een step-level system error op:
Cannot find external XSD folder for schema to append: D:\imvertor\ImvertorOS-M-server\Imvertor-builds\Imvertor\1.63\Imvertor-bin\input\BRO\xsd\standards.iso.org\CIT10-2006.
Imvertor zoekt de xsd’s in xsd/standards.iso.org/CIT10-2006. Dit betekent de xsd’s voor ISO19115 GEX10 en CIT10 uit elkaar getrokken zouden moeten worden dan wel gekopieerd moeten worden in aparte directories onder de namespace xsd/standards.iso.org/, dus onder xsd/standards.iso.org/GEX10-2006 en onder xsd/standards.iso.org/CIT10-2006. Dit is niet wenselijk… 
**Gewenste situatie:**
Imvertor zoekt niet op combinatie cs:id en cs:release, maar enkel op cs:release. Het cs:id wordt daarmee betekenisloos. De ISO19115 xsd’s voor GEX10 en CIT10 kunnen dan worden opgenomen in xsd/standards.iso.org/2006/ iso/19115/-3/*. Dit maakt het mogelijk om naar verschillende schemalocaties te verwijzen, dus zowel naar:
`<cs:location>http://standards.iso.org/iso/19115/-3/cit/1.0/cit.xsd</cs:location> en <cs:location>http://standards.iso.org/iso/19115/-3/gex/1.0/gex.xsd</cs:location> `
**Verwachte impact:**
-	Broncode Imvertor aanpassen
-	De mappen structuur van xsd’s in de Github-repository (voor alle organisatie) aanpassen.

**Tijdelijke workaround**
Een kopie van de ISO1995-cit xsd's naar een map standards.iso.org/CIT10-2006, zie pull request https://github.com/Imvertor/Imvertor-Maven/pull/157

**Comment by ArjanLoeffen** [comment]
De impact van deze aanpassingen lijkt te groot. Het is ook de vraag of dit klopt. 

Het schema cit.xsd importeert gco en mcc, en die importeren zelf ook weer schema's. Het lijkt erop dat de bindende factor tussen de schema's de "wrapper" ISO19115 uit 2006 is. De aanname dat we een map kunnen introduceren met de naam CIT is dus wellicht verkeerd. Er moet dan een map worden gebruikt met de naam ISO19115. 

Helaas haal je daarmee een hele reeks schema's binnen die je niet wenst. Dat vraagt dan om een BRO specifiek profiel van ISO19115, zoals dat ook is gedaan voor GML.

Het is natuurlijk ook mogelijk een CIT map in te voeren. Maar:
- dan moeten daarin alle schema's zijn opgenomen die relevant zijn voor CIT (dus de hele "import tree") 
- of dan moet voor alle schema's een map worden opgenomen in configuratie en in de conceptual-schemas.xml 

Op die manier is het dan mogelijk voor Imvertor een complete set van externe schema's samen te stellen en mee te leveren zodat alle schema's lokaal kunnen worden benaderd. 

Feitelijk betekent bovenstaande zienswijze dat de merge die uitvoerd is onder #157 moet worden heroverwogen; ze is niet compleet of niet in lijn met deze analyse.
