### ISSUE TITLE
Lengte voor CharacterString 2..5 wordt niet goed gegeneerd?

### ISSUE THREAD

**Issue by lennartvanbergen** [Imvertor/Imvertor-Maven#159]
In UML: CharacterString met tagged value lengte 1..5 

Imvertor 1.63
UML model is goedgekeurd. 

In XSD: 
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:length value="5"/>
<xs:pattern value="\S.*"/>
</xs:restriction>
</xs:simpleType>

XML met daarin <deel>1234</deel> voldoet niet aan de XSD. De lengte moet namelijk precies 5 zijn, want dat betekent <xs:length value="5"/>

Opmerking: in UML is **zelf ingetypt**: CharacterString ipv het typen package te gebruiken. Kan dat het zijn?

--

Voor CharacterString 1..5 moet dit toch zijn: 

<xs:simpleType>
<xs:restriction base="xs:string">
**<xs:minLength value="1"/>
<xs:maxLength value="5"/>**
<xs:pattern value="\S.*"/>
</xs:restriction>
</xs:simpleType>

?

In 1.61 wordt precies hetzelfde model wel gegenereerd als voorgaande XSD met min en max length. 

--

Lijkt op volgend issue: 
https://github.com/Imvertor/Imvertor-Maven/issues/143
Maar hier is lengte behandeld voor Integer

**Comment by lennartvanbergen-kadaster** [comment]
1.63 met attribuutsoort naam = CharacterString uit typen en kadaster-extern gaat goed.
Gaat ook goed als zelf CharacterString ingetypt. 

Waar het misgaat is bij IMKAD Stuk
Attribuutsoort deelEnNummer = gestructureerd datatype DeelEnNummer en dan data element deel heeft lengte 1..5  

Krijgen daar length 5.

**Comment by ArjanLoeffen** [comment]
Ik kan dit niet reproduceren in de testgevallen die ik voor Kadaster beheer.
Welke job kan ik bekijken om het effect te zien?

**Comment by kad-veltms** [comment]
Hoi Arjan, kan je hier wat meer mee?

Job ID 2021-02-12-13-27-22-281 (Kadaster-extern uitgebreid/ChainTranslateAndReport:1.63)

Voorbeeld: TypeDeelEnNummer/deel 
--> in UML CharacterString met tagged value Lengte 1..5
--> in XSD met Length ipv MaxLength zoals 1.61 wel genereerd
<xs:element name="deel" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="5"/>
						<xs:pattern value="\S.*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

**Comment by ArjanLoeffen** [comment]
Inderdaad is de fout herleidbaar tot "nativescalars" die yes in in dit geval. Het is nu gecorrigeerd voor CharacterString (letterlijk zo ingetoetst). Het lijk erop dat ook total/fractiondigits en pattern wel goed gingen, dat is niet aangepast.

Nu zou dus voor nativescalars yes én no het goed moeten gaan.
Beschikbaar vanaf 13 febr 2021.

**Comment by lennartvanbergen-kadaster** [comment]
Top!

**Comment by kad-mesdat** [comment]
Nog een verbetering. 

Voor Integers met een lengte wordt nu 'minInclusive'  en 'maxInclusive' gegenereerd, maar dat was `totalDigits`. Ik vind `totalDigits`="32" wel makkelijker lezen dan `maxInclusive`="100000000000000000000000000000000" Bovendien zou dat dan ook 99999999999999999999999999999999 moeten zijn.

**Comment by ArjanLoeffen** [comment]
Speelt dit nu nog?

**Comment by lennartvanbergen-kadaster** [comment]
Je laatste vraag kan @kad-mesdat beter beantwoorden. 

Interessante MIM 1.1.1 of 1.1.2. ontwikkeling op dit vlak is https://github.com/Geonovum/MIM-Werkomgeving/issues/109 

Als we met MIM 1.1.1. aan de slag gaan is het denk ik goed om even de koppel bij elkaar te steken.

**Comment by kad-mesdat** [comment]
> Speelt dit nu nog?

Ik heb even gekeken in de in september gegenereerde CDMKAD en daar was het weer total digits = 32 dus lijkt mij opgelost.
