### ISSUE TITLE
Andere opzet van de metamodel configuratie

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#160]
Ik pleit voor een andere opzet van de metamodel configuratie. Een opzet waarbij:
* organisaties automatisch de organisatieonafhankelijke MIM configuratie volgen;
* organisaties de mogelijkheid hebben om daar configuraties aan toe te voegen;
* maar ook de mogelijkheid hebben om (nog) niet gebruikte onderdelen van het MIM weg te laten.

VNG-Realisatie maakt geen gebruik van de totale set aan MIM 1.1 stereotypes en heeft daar dus behoefte aan. Zo maken wij (nog) geen gebruik van de volgende in de MIM configuratie gedefinieerde stereotypes:

- Toepassing
- View
- Extern
- System
- Process
- Product
- Service
- Keuze
- Keuze element
- Tekentechnisch
- Externe koppeling
- Relatierol
- Anoniem
- Componenten
- Folder
- IsId
- Provided
- Referentie
- System-reference-class
- System-reference-package

welke overigens niet allemaal deel uitmaken van MIM 1.1 wat n.m.m. dus niet correct is.

Deze wens is vooral van belang nu VNG-Realisatie voornemens is de door Imvertor gegenereerde MDG profielen te gaan gebruiken in Enterprise Architect. Daarin willen we echter zo min mogelijk componenten opgenomen hebben die we niet gebruiken.

Een mogelijkheid om dat te bereiken is de organisatieonafhankelijke configuratie (MIM11.xml) op te delen in hapklare brokken die je als organisatie wel of niet in de eigen configuratie (voor VNG-Realisatie bijv. 'VNGRSIM.xml') kunt opnemen.

Om het voor organisaties die niets wensen te veranderen aan de huidige opzet onaangetast te laten include je de hapklare brokken gewoon in het MIM11.xml bestand. Organisaties die er wel gebruik van willen maken kunnen i.p.v. het includen van MIM11.xml juist de gewenste hapklare brokken includen in de eigen configuratie.

**Comment by ArjanLoeffen** [comment]
Dit moeten we even goed doornemen. We willen een MIM 1.1 configuratie gaan opzetten, en hebben expliciet niet het plan om MIM 1.1.. in "brokken" te gaan aanbieden (waarbij je bepaalde brokken zou kunnen "weglaten". Een standaard is een standaard toch :-)

Voordat we dit gaan doen dus eerst overleg met MIM community/comité.

**Comment by melsk-r** [comment]
Prima plan. Mijn idee is ook al weer 1 jaar oud dus ik kan me voorstellen dat, als ik me er weer even in zou verdiepen, ik er inmiddels al weer anders tegenaan kijk.
Het doel van mijn voorstel was iig om zo slank mogelijke MDG profielen te kunnen genereren zodat je geen constructies kunt introduceren die niet door de OAS stylesheets worden ondersteund. Lijkt me handig zeker nu er steeds meer organisaties gebruik maken van deze stylesheets. Maar wellicht kunnen we dat ook op andere manieren bereiken.

Ik ben ook benieuwd hoe Johan daar tegenaan kijkt dus ik assign hem ook even.

**Comment by melsk-r** [comment]
Assignen gaat niet dus ik vraag hem wel gewoon even te kijken naar dit issue.

**Comment by JohanBoer** [comment]
Ik snap de behoefte om de MDG-profiele zo slank mogelijk te houden, maar MIM1.1 is MIM1.1 . Integraal dus.  Dat een organisatie er voor kiest om bepaalde constructs of stereotypes niet toe te passen is natuurlijk mogelijk, maar dergelijke inzichten kunnen veranderen op basis van voorschrijdend inzicht. 

Ik zou MIM 1.1 niet opdelen in brokken, maar integraal configureren en dus ook opnemen in de MDG-profielen van VNGR. Daarnaast moeten wij binnen onze eigen organisatie afspreken hoe wij omgaan met MIM. En hoe wij de gebruikte constructs en stereotypes omzetten in UGM en BSM. 

Als voorbeeld het stereotype "IsId".  Wij gebruiken daar nu de EA-eigenschap "IsId" voor, maar misschien moeten wij overwegen om ons op dit vlak aan MIM te gaan conformeren.

**Comment by melsk-r** [comment]
Ok, dan concludeer ik dat we hier niet onze kostbare tijd in moeten steken en ik stel dan ook voor om dit issue te sluiten. Tenzij jij @ArjanLoeffen er op de e.o.a. manier toch brood in ziet.

**Comment by ArjanLoeffen** [comment]
We hebben binnen de community afgesproken e.e.a. om te gooien, zie #256 . Ik sluit dit issue.
