### ISSUE TITLE
INGETROKKEN Voor GM/GML altijd propertyType toepassen - ook bij een Keuze/Union 

### ISSUE THREAD

**Issue by lennartvanbergen** [Imvertor/Imvertor-Maven#162]
**INGETROKKEN** 
_In GML is onderstaande niet mogelijk ... een ref naar een type kan niet. Elke xyzPropertyType is een type. Vandaar dat het waarschijnlijk ook is zoals het nu al is geworden._

Voor keuzes/union wordt de volgende XSD gegenereerd: 

<xs:complexType name="VlakOfMultivlak” abstract="false">
      <xs:choice minOccurs="1" maxOccurs="1">
              <xs:element **ref**="**gml:Surface**" minOccurs="1" maxOccurs="1"/>
              <xs:element **ref**="**gml:MultiSurface**" minOccurs="1" maxOccurs="1"/>
      </xs:choice>
</xs:complexType>

Wat grotendeels goed is. Behalve dat PropertyType niet gebruikt wordt. 

Voor alle GM Types in UML willen we altijd propertyType toepassen. Dus ook bij Keuze/Union. Dit hangt niet af van CDMKAD/IMKAD of van intern of extern of wel of niet NEN3610. De modellering van geometrie en de XSD behoort altijd hetzelfde te zijn. 

Oftewel, ook voor een keuze/union. 

De XSD zou wat ons betreft dus behoren te zijn:

<xs:complexType name="VlakOfMultivlak” abstract="false">
      <xs:choice minOccurs="1" maxOccurs="1">
              <xs:element **ref**="gml:Surface**PropertyType**" minOccurs="1" maxOccurs="1"/>
              <xs:element **ref**="gml:MultiSurface**PropertyType**" minOccurs="1" maxOccurs="1"/>
      </xs:choice>
</xs:complexType>

**Comment by lennartvanbergen-kadaster** [comment]
![VlakOfMultivlak](https://user-images.githubusercontent.com/24241862/109794511-37124100-7c16-11eb-9a45-dd7a536556b3.jpg)
