### ISSUE TITLE
Volgorde van relaties

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#165]
Voor objecten is met de tagged value Positie aan te geven in welke volgorde de objecten gepubliceerd worden. Bij relaties ontbreekt deze tag. Is er een manier om relaties in een eigen te bepalen volgorde weer te geven?

**Comment by ArjanLoeffen** [comment]
Deze tagged value is wel gedefinieerd, en wordt gebruikt om posities aan te geven. 
Zie https://imvertor.armatiek.nl/imvertor-executor/dashboard/wiki?key=info-DOCMANOPEEEN.

In de BRO configuratie is deze tagged value opgenomen, waar mis je 'm?

**Comment by WijnandvanRiel** [comment]
De tv Positie kan gebruikt worden bij Objecttypes en daar werkt hij ook goed. Als voorbeeld: https://broprogramma.github.io/BHR-G/#global_class_Model_Boring De aan boring gerelateerde objecten staan in de goede volgorde in de catalogus (met de klok mee). De tekstuele beschrijving van de relaties van Boring staat echter in een andere, willekeurige volgorde.  In EA kan bij de properties van de associatie-relaties niet de tagged value Positie gebruikt worden.

**Comment by ArjanLoeffen** [comment]
Ik vermoed dat je het volgende bedoelt:

![image](https://user-images.githubusercontent.com/12828217/112719291-876c7e00-8ef8-11eb-88f4-b65da5912b0d.png)

Dat is nu hersteld. 
PS Ik snap niet dat jullie niet de zelfde namen hanteren in TOC en in diagram. Wat is de reden?

**Comment by WijnandvanRiel** [comment]
Het is nog niet correct. Het gaat om de volgorde van de tekstuele beschrijving van de associatie-relaties 
![image](https://user-images.githubusercontent.com/57146824/112831600-7a849180-9094-11eb-801d-a4205bc96242.png)
In bovenstaand voorbeeld moet dat zijn: Weggegraven laag (type gegeven: Associatie van Boring),  Geboord interval, Boorsnelheid, Bemonsterd interval. Dus niet eerst Bemonsterd interval en daarna Geboord interval. Op de volgorde van de beschrijving hebben we geen invloed, maar zou opgelost kunnen worden door aan de associatie-relatie de tv 'positie' toe te voegen.

**Comment by WijnandvanRiel** [comment]
Getest en komt er goed uit. Top.
