### ISSUE TITLE
Verbeterde tekstuele weergave stereotype Keuze

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#166]
Het modelelement Keuze kan wel in een domeinmodel gedefinieerd worden, maar wordt in een respec-catalogus niet als tekst weergegeven. Zie bijv:  https://broprogramma.github.io/GUF/#graph_EAID_9D151445_53ED_4738_9920_071518BB50C1 Er zijn verschillende RO's die dat nodig hebben.

**Comment by ArjanLoeffen** [comment]
Zou je willen aangeven hoe dat moet worden weergegeven in de catalogus? Dit graag dmv. een voorbeeld in html of msword oid?

**Comment by WijnandvanRiel** [comment]
Als voorbeeld kun je kijken naar: https://broprogramma.github.io/GUF/#global_class_Model_Gerealiseerdeoppervlakteinfiltratie
Hierin ook het attribuut geometrie met als datatype een keuze tussen punt, lijn of vlak.

Bij 4.3.9.2 is het attribuut geometrie beschreven.
Het keuze datatype zou als 4.3.20 toegevoegd kunnen worden (na alle objecttypen en gegevensgroeptypen.)
Als volgt weergegeven:
![image](https://user-images.githubusercontent.com/57146824/112624478-f8932f00-8e2d-11eb-901a-12968082ed40.png)

Bovenstaand voorbeeld is vergelijkbaar met de weergave  van keuze-elementen op attribuutniveau uit de BAG

**Comment by ArjanLoeffen** [comment]
Gedaan. Beschikbaar in 1.64.0.

**Comment by WijnandvanRiel** [comment]
Getest en OK
