### ISSUE TITLE
Externe packages

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#168]
Kan me uitgelegd worden hoe het MIM-stereotype Extern (zie: https://docs.geostandaarden.nl/mim/mim/#extern) in Imvertor is geïmplementeerd? Stel ik wil constructies uit een bepaald RO gebruiken in een ander RO. Dan zou ik verwachten dat ik ze in een package met stereotype extern zet. Moet er dan nog iets gebeuren in Imvertor om dat te kunnen verwerken? Nu wordt deze constructie niet herkend.

**Comment by ArjanLoeffen** [comment]
Zie
https://imvertor.armatiek.nl/imvertor-executor/dashboard/wiki?key=info-IMVERTORCONCEPTUALSCHEMAS

Dit is de implementatie van Imvertor voor alle constructies uit modellen die buiten het bewerkte model vallen. "Extern" stereotype wordt dus niet apart afgehandeld door Imvertor. Het wordt gezien als de typering van een "wrapper" package waarin je alle externe constructies, waar je niet zomaar naar kunt verwijzen in je EA omgeving, opneemt.

**Comment by WijnandvanRiel** [comment]
Voor BRO-brede constructies is dit handig, maar voor enkele cross-RO verwijzigingen niet. We denken een andere werkwijze gevonden te hebben.
