### ISSUE TITLE
Datatype gYear en GMonth voor mogelijk onvolledige datum.

### ISSUE THREAD

**Issue by kad-mesdat** [Imvertor/Imvertor-Maven#171]
In https://www.noraonline.nl/images/noraonline/c/c3/GAB_mogelijk_onvolledige_datum_1.0.pdf is de mogelijk onvolledige datum beschreven die gebruikt de basistypen gYearMonth en gYear. Deze zitten nu niet in de MIM 1.1 Primitieve Datatypen xmi. Hoewel (nog?) niet in MIM zou het wel handig zijn om deze te kunnen gebruiken. 

![image](https://user-images.githubusercontent.com/67012704/112148468-37cb4100-8bde-11eb-917e-e08095ded8fe.png)

Zou je deze kunnen toevoegen of is er een andere manier om custom datatypen toe te voegen?

**Comment by ArjanLoeffen** [comment]
Ik heb beide toegevoegd: gYearMonth (YearMonth) en time (Time) in een aparte mapping.  gYear en gMonbth waren al onderdeel van MIM11. De XMI moet bij gebruikers worden vervangen als zijn  willen verwijzen naar deze nieuwe uitbreidingen voor Kadaster op MIM11.
Zie de XMI in 
```
/input/Kadaster/eap/Kadaster-MIM11.xmi
```
