### ISSUE TITLE
Imvertor 1.64 levert onverwacht resultaat

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#174]
In de BRO catalogi die gegenereerd wordt sinds Imvertor 1.64 wordt op één plek (alleen bij het registratieobject) een onverwachte code 9999 gepubliceerd: 
![image](https://user-images.githubusercontent.com/57146824/113115673-f6094e80-920c-11eb-80c5-acbf8383f2b1.png)

**Comment by ArjanLoeffen** [comment]
Is gecorrigeerd; kwam op door herinterpretated van calculate-position() /  calculate-node-position() functies.

**Comment by WijnandvanRiel** [comment]
Getest en 9999 komt niet meer voor
