### ISSUE TITLE
Geneste targets wanneer het isID mogelijk geen waarde heeft werkt niet meer

### ISSUE THREAD

**Issue by kad-mesdat** [Imvertor/Imvertor-Maven#185]
In onze informatie modellen willen we op een aantal plekken de target objecten van de relaties genest in het xsd-schema hebben, namelijk wanneer de id van het target object er mogelijk niet is. 
Dit werkte eerder wel (bij KKG?) maar werkt nu niet meer. 
![image](https://user-images.githubusercontent.com/67012704/121889751-e680a880-cd19-11eb-8133-3edc864ae1fb.png)

Als er geen isId attribuut is in het target object wordt het sowieso al genest gegenereerd:
![image](https://user-images.githubusercontent.com/67012704/121890015-2ba4da80-cd1a-11eb-9102-a5ecaf10ae31.png)

**Comment by ArjanLoeffen** [comment]
Het probleem is (was) dat het criterium voor de Kadaster schema generator is dat het target object (in de View dus) een voidable ID kan hebben. Als dat zo is, nesten. Als dat niet zo is, dan mogelijk niet nesten. 

Voidable ID werd herkend aan het stereotype \<<voidable\>>. Dat wordt nu: stereotype, of de tagged value "Waarde mogelijk onbekend" (of beide).

Beschikbaar in 1.64.2 van 15 juni.

**Comment by lennartvanbergen-kadaster** [comment]
Ja, inderdaad, vanaf MIM 1.0 is het 'mogelijk geen waarde' waar we ons op willen/zouden moeten baseren. Er is een tagged value/metadata veld op informatiemodel niveau die heet: MIM versie. Als daar 1.1 staat lijkt het mij goed om de generatie te baseren op 'mogelijk geen waarde'. Er is ook een validatie, dat als we voidable en 'mogelijk geen waarde' gebruiken, dat dit met elkaar klopt. Voidable is voor visueel. De juiste om ons op te baseren is 'mogelijk geen waarde'. Dit is ook zo'n beetje verborgen wijziging die mee is gekomen met de overgang van KKG naar MIM.
