### ISSUE TITLE
Voor het aantal cijfers voor en achter de komma kun je

### ISSUE THREAD

**Issue by kad-mesdat** [Imvertor/Imvertor-Maven#187]
Voor het aantal cijfers voor en achter de komma kun je
> 2.8.2.23 Metagegeven: Lengte (domein van een waarde van een gegeven)

volgen. Dat is geimplementeerd.

_Originally posted by @ArjanLoeffen in https://github.com/Imvertor/Imvertor-Maven/issues/173#issuecomment-841207985_

**Comment by kad-mesdat** [comment]
Bij het datatype real werkt het specificeren van het aantal cijfers voor en achter de komma  niet. Als ik er een decimal van maak dan werkt het wel. Het lijkt mij dat het ook voor een real zou moeten werken.

**Comment by wilkoquak** [comment]
XML schema staat fractionDigits alleen toe bij decimal. Het mag dus niet bij real.

**Comment by kad-mesdat** [comment]
Ok, vandaar. Is dat dan standaard 18 karakters? Het verschil tussen real en decimal is ook wel een beetje een theoretische discussie. In MIM is het volgende te lezen:

> Vrij vertaald: een real is een zwevendekommagetal, waarbij de precisie bepaald wordt door het aantal getoonde cijfers. Het getoonde getal is een schatting en geeft niet noodzakelijk de exacte waarde weer. Opmerking 1: Dit verschilt van decimal, want decimal is een exacte waarde en real is geschat. 

Daarom verwachtte ik wel een fractionDigits. Maar dit is dus niet een issue voor Imvertor. Hooguit moet de error tekst nog wat specifieker worden. (Ik kon de w3c definitie van xs:real ook niet vinden, daar zou in de melding naar verwezen kunnen worden)

Issue kan denk ik gesloten worden.

**Comment by wilkoquak** [comment]
Eens kijken of ik dat kan. Nee, kan je dat zelf?

**Comment by kad-mesdat** [comment]
Ja, ik denk wel dat dat lukt :-) Hierbij het issue gesloten.
