### ISSUE TITLE
Bepaalde karakters leiden tot problemen in yaml.

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#188]
Zie voor dit issue ook de issues [38](https://github.com/VNG-Realisatie/Regels-bij-activiteiten/issues/38) en [44](https://github.com/VNG-Realisatie/Regels-bij-activiteiten/issues/44) (VNG-Realisatie/Regels-bij-activiteiten).

bepaalde karakters die in het notes field van EA worden ingeklopt leiden in yaml tot problemen.
Als je het bestand [openapi.yaml](https://github.com/Imvertor/Imvertor-Maven/files/6710123/openapi.zip) met Notepad++ opent dan zie je bijv. in regel 962 en regel 980 'xC2' en 'xE2x80' staan. 

Wat het eerste karakter is, is niet duidelijk aangezien op die positie in EA in het Notes veld niets vreemds te zien valt. Zoals je hieronder ziet (het gaat om het karakter tussen 'activiteit.' en 'Bijvoorbeeld'):

![afbeelding](https://user-images.githubusercontent.com/20185784/123287254-e6995900-d50e-11eb-9641-d8ff4fb8616c.png)

Het tweede karakter is wel duidelijk. De string 'is (een)' wordt in het Notes veld omvat door de karakters “ en ”.

![afbeelding](https://user-images.githubusercontent.com/20185784/123289517-d4b8b580-d510-11eb-8fb6-86cf94ed1247.png)

Het eerste karakter wordt automatisch omgezet naar “ wat wel geaccepteerd wordt. Het tweede karakter wordt blijkbaar ook omgezet maar dat wordt niet geaccepteerd.

Ik heb de zip met daarin de xmi van het CIM bijgevoegd. In de issues waarnaar ik bovenaan dit issue verwijs staat beschreven waar je de betreffende notes kunt vinden.

[CIM PlanSW-TRSW-1816.zip](https://github.com/Imvertor/Imvertor-Maven/files/6710309/CIM.PlanSW-TRSW-1816.zip).

Wellicht moeten we dit soort problemen structureel oplossen door een waarschuwing te geven. Deze karakters automatisch door Imvertor laten vervangen is n.m.m. niet de manier omdat daarmee de oorzaak van de problemen niet wordt aangepakt. 

Misschien is het dan het handigste een lijst te maken waarin we karakters die problemen veroorzaken kunnen plaatsen. Zodra Imvertor een van de karakters in die lijst detecteert zou dan een waarschuwing/fout moeten worden gegenereerd.
De lijst kunnen we dan steeds uitbreiden.
Het is maar een idee.

**Comment by melsk-r** [comment]
Ik ben bezig met de json en yaml op een andere wijze te genereren (m.b.v. Saxon en Json map) en ik heb het idee dat daarmee al veel van de problemen die ik met vreemde karakters heb worden opgelost.
Zie https://github.com/VNG-Realisatie/Model-Driven-Design/issues/13 voor de status van de nieuwe wijze van genereren.

**Comment by ArjanLoeffen** [comment]
@melsk-r status?

**Comment by melsk-r** [comment]
Ik zie dit probleem zowel in de oude wijze van genereren als in de nieuwe wijze van genereren niet meer terugkomen. Ik sluit dit issue. Mocht het zich toch weer voordoen dan voeren we een nieuw issue op.
