### ISSUE TITLE
EAAddinFramework error

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#189]
Michiel Verhoef krijgt sinds 1 kwartier de volgende foutmelding:

![afbeelding](https://user-images.githubusercontent.com/20185784/123426482-c37cb100-d5c3-11eb-8ff5-3eccbcd84e94.png)

Ik vrees dat er een probleempje op de server speelt.

In de genoemde log staan o.a. deze fouten:

25-06-2021 02:24:54.582 diff: 1223656,5662 ms Error: Error in StartJob: Er zijn één of meer fouten opgetreden. stacktrace:    bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bij System.Threading.Tasks.Task`1.get_Result()
   bij EAImvertor.EAImvertorJob.Upload(String actionUrl, String pincode, String processName, String imvertorProperties, String modelFilePath, String historyFilePath, String propertiesFilePath) in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorJob.cs:regel 556
   bij EAImvertor.EAImvertorJob.startJob(BackgroundWorker backgroundWorker) in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorJob.cs:regel 244
25-06-2021 02:26:08.535 diff: 73953,4771 ms Error: Error in StartJob: Er zijn één of meer fouten opgetreden. stacktrace:    bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bij System.Threading.Tasks.Task`1.get_Result()
   bij EAImvertor.EAImvertorJob.Upload(String actionUrl, String pincode, String processName, String imvertorProperties, String modelFilePath, String historyFilePath, String propertiesFilePath) in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorJob.cs:regel 556
   bij EAImvertor.EAImvertorJob.startJob(BackgroundWorker backgroundWorker) in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorJob.cs:regel 244
25-06-2021 02:29:08.407 diff: 179871,4082 ms Error: Error in StartJob: Er zijn één of meer fouten opgetreden. stacktrace:    bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bij System.Threading.Tasks.Task`1.get_Result()
   bij EAImvertor.EAImvertorJob.Upload(String actionUrl, String pincode, String processName, String imvertorProperties, String modelFilePath, String historyFilePath, String propertiesFilePath) in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorJob.cs:regel 556
   bij EAImvertor.EAImvertorJob.startJob(BackgroundWorker backgroundWorker) in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorJob.cs:regel 244
25-06-2021 02:30:35.375 diff: 86968,7303 ms Error: Error in StartJob: Er zijn één of meer fouten opgetreden. stacktrace:    bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bij System.Threading.Tasks.Task`1.get_Result()
   bij EAImvertor.EAImvertorJob.Upload(String actionUrl, String pincode, String processName, String imvertorProperties, String modelFilePath, String historyFilePath, String propertiesFilePath) in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorJob.cs:regel 556
   bij EAImvertor.EAImvertorJob.startJob(BackgroundWorker backgroundWorker) in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorJob.cs:regel 244
25-06-2021 02:32:56.663 diff: 0 ms Error: Could not get configs because of error: Er zijn één of meer fouten opgetreden. Stacktrace:    bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bij System.Threading.Tasks.Task`1.get_Result()
   bij EAImvertor.EAImvertorSettings.getConfigXml() in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorSettings.cs:regel 103
25-06-2021 02:33:12.878 diff: 16214,5647 ms Error: Error in StartJob: Er zijn één of meer fouten opgetreden. stacktrace:    bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bij System.Threading.Tasks.Task`1.get_Result()
   bij EAImvertor.EAImvertorJob.Upload(String actionUrl, String pincode, String processName, String imvertorProperties, String modelFilePath, String historyFilePath, String propertiesFilePath) in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorJob.cs:regel 556
   bij EAImvertor.EAImvertorJob.startJob(BackgroundWorker backgroundWorker) in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Toolpack\EAImvertor\EAImvertorJob.cs:regel 244

**Comment by maartenkroon** [comment]
Het SSL certificaat van deze server is vandaag verlopen en deze foutmeldingen hebben hier zeer waarschijnlijk mee te maken. Dit certificaat zou eigenlijk automatisch moeten worden verlengd, maar daar is iets niet helemaal goed gegaan. Daarom hebben we  dit certificaat nu handmatig verlengd. Willen jullie het nog eens proberen?

NB. Aan de foutmeldingen zie ik dat jullie nog met een oude versie van de EA addin werken. Sinds enige tijd is er een nieuwe (door Armatiek zelf ontwikkelde) versie van de addin. Ik denk dat het goed zou zijn om binnenkort over te stappen naar deze nieuwe versie; aan de oude versie wordt geen onderhoud meer gepleegd.

**Comment by melsk-r** [comment]
Ik heb het inmiddels doorgegeven. Ik hoop dat Michiel vandaag nog even tijd heeft.

Grt,

Robert



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Maarten Kroon ***@***.***>
Datum: 25-06-21 18:13 (GMT+01:00)
Aan: Imvertor/Imvertor-Maven ***@***.***>
Cc: Robert Melskens <Robert.Melskens@VNG.NL>, Author ***@***.***>
Onderwerp: Re: [Imvertor/Imvertor-Maven] EAAddinFramework error (#189)


Het SSL certificaat van deze server is vandaag verlopen en deze foutmeldingen hebben hier zeer waarschijnlijk mee te maken. Dit certificaat zou eigenlijk automatisch moeten worden verlengd, maar daar is iets niet helemaal goed gegaan. Daarom hebben we dit certificaat nu handmatig verlengd. Willen jullie het nog eens proberen?

NB. Aan de foutmeldingen zie ik dat jullie nog met een oude versie van de EA addin werken. Sinds enige tijd is er een nieuwe (door Armatiek zelf ontwikkelde) versie van de addin. Ik denk dat het goed zou zijn om binnenkort over te stappen naar deze nieuwe versie; aan de oude versie wordt geen onderhoud meer gepleegd.

**Comment by melsk-r** [comment]
Issue kan gesloten worden. Michiel is zijn nieuwe laptop aan het inrichten en onderdeel daarvan is het helemaal opnieuw installeren en configureren van EA. Nieuwe versie van de EA Addin zal daarbij automatisch geïnstalleerd worden.
