### ISSUE TITLE
Identificerend gegeven opnemen in ReSpec (BRO)

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#193]
Zou het Attribute property 'Is ID' opgenomen kunnen worden in de Respec catalogus als deze eigenschap in EA op True staat? Vergelijkbaar met de BAG: Identificeren Ja
![BAG_IDisTrue](https://user-images.githubusercontent.com/57146824/125260025-35613400-e300-11eb-82d7-0304d9839195.png)

**Comment by ArjanLoeffen** [comment]
Deze toevoeging is gemaakt. Graag sluiten.
