### ISSUE TITLE
Probleem: Tagged value without name for stereotype "EXTERN"

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#198]
Zojuist heb ik  een Pull gedaan waardoor ik vervolgens de volgende melding krijg:

`FATAL 2021-07-29 15:19:54,227 : Imvert2ea-profile.xsl: [(NO CONTEXT)] No such parameter "ea-omit-tv-when-notes-field-exists"`

Ik heb geen idee wat die parameter precies doet maar na wat uitzoekwerk ben ik er achter gekomen dat in het bestand '/Imvertor-Maven/src/main/resources/input/KING/cfg/owners/KING.xml' de volgende parameter moet worden toegevoegd:

`<parameter name="ea-omit-tv-when-notes-field-exists">no</parameter>`

Helaas leidt dat weer tot de volgende melding:

`FATAL 2021-07-29 15:23:12,801 : Imvert2validate-derivation.xsl: [VNGR:: = http://www.vng.nl/] Tagged value without name for stereotype "EXTERN"`

Wat moet ik doen om die melding op te lossen?

**Comment by ArjanLoeffen** [comment]
Dit issue is inmiddels opgelost en had te maken met xi:include verwisseling van plek. @melsk-r graag  testen en sluiten.

**Comment by melsk-r** [comment]
@ArjanLoeffen: Ik zie nu dat dit hetzelfde issue is als waar wij eerder deze week contact over hadden. Dat hebben we toen opgelost door in de configuratie '...\src\main\resources\input\KING\cfg\tvsets\KINGGrouping.xml' voor de tagged value met het id 'CFG-TV-DATALOCATION' alsnog een 'name' property te definiëren. 
'**Alsnog**' omdat in '...\src\main\resources\input\Imvertor\cfg\tvsets\Grouping.xml' waar de betreffende tagged value wordt geïnitieerd geen 'name' property werd gedefinieerd. 

Inmiddels heb ik die oplossing ingecheckt. Wat ik me nu afvraag is of de oplossing die we eerder deze week hebben toegepast op de e.o.a. wijze conflicteert met de oplossing die jij hierboven schetst. Moet ik de oplossing die we eerder deze hebben gevonden weer terug draaien?
Zo niet, assign dan dit ussue maar weer aan mij.

**Comment by ArjanLoeffen** [comment]
Volgens mij werkt alles nu naar behoren. @melsk-r  kun je dit even checken en issue sluiten?

**Comment by melsk-r** [comment]
Wat mij betreft is het opgelost. FATAL errors krijg ik al lang niet meer.
Ik sluit hem.
