### ISSUE TITLE
Verschil in Respec Catalogus tussen 1.64 en 1.65

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#200]
In de respec-catalogus gegenereerd met 1.64 zijn de namen van codelijsten een link naar de codelijst:
In de xhtml: 
      a class="link" href="#detail_class_Model_Bepalingsprocedure">Bepalingsprocedure

In 1.65 ontbreekt die link:
In de xhtml:
    td>Bepalingsprocedure</td
Zoals ik nu zie, geldt dat voor alle codelists.

**Comment by ArjanLoeffen** [comment]
Dit geldt voor alle lijsten: enumeraties, referentielijsten, codelijsten. Wat is de regel? Wil je een link naar alle soorten lijsten, of alleen codelijst? Ik herstel in ieder geval codelijst.

**Comment by ArjanLoeffen** [comment]
Kleine bug, is hersteld.

**Comment by ArjanLoeffen** [comment]
beschikbaar op 11 sept, 1.65
