### ISSUE TITLE
kardinaliteit van associaties waar er niet expliciet eentje is opgegeven

### ISSUE THREAD

**Issue by wilkoquak** [Imvertor/Imvertor-Maven#203]
In UML diagrammen is het mogelijk een associatie te definieren zonder er een mulitipliciteit bij te zetten.  Zie bijvoorbeeld bij het plaatje hieronder. Als ik de UML specificatie erop nalees staat er hierover: 'If no mulitplicity is shown on the diagram, no conclusion may be drawn about the multiplicity in the model'. Oftewel: het model legt geen beperkingen op aan de multipliciteit en dat zou je kunnen interpreteren als '*' (alles mag).  Imvertor maakt er altijd '1' van, dat matcht wel weer mooi met default waardes van minOccurs en maxOccurs in xml-schema. 

Een vraag en een voorstel:
 - Op basis waarvan is in Imvertor deze default kardinaliteit bedacht?
 - Omdat deze default waardes voor associaties niet helemaal helder zijn lijkt het mij een best-practice ze altijd in te vullen (in ieder geval bij associalties met een rolnaam) en een warning te laten geven wanneer de kardinaliteit niet is gegeven.

![image](https://user-images.githubusercontent.com/2814052/133102679-0dd5d737-1d6a-4a67-bc82-32b944aceed7.png)

**Comment by lennartvanbergen-kadaster** [comment]
Er is gevraagd naar mijn mening. Deze is: het modelleren van informatie hoort expliciet te zijn. 

In MIM is de kardinaliteit (daarom) verplicht (en dit zou gecontroleerd moeten worden als je een MIM check uitvoert). 

Voor andere informatiemodellen die deze standaard niet volgen kan je andere keuzes maken (maar ik zou het wel verplicht maken omdat het zo wezenlijk is dat je niet per ongeluk bij een tool die een andere default heeft iets ander krijgt, zoals 0..* vanwege undefined, al ken ik geen tool die wat anders kiest dan 1..1, then again, geen tool analyse gedaan). 

UML 2.5 zegt hierover op pagina 199/200 van https://www.omg.org/spec/UML/2.5/PDF/

> NOTE. If no multiplicity is shown on the diagram, no conclusion may be drawn about the multiplicity in the model.

**Comment by ArjanLoeffen** [comment]
Hoe verhoudt zich dit tot "If no multiplicity is shown on an association end, it implies a multiplicity of exactly 1." op pagina 19 van dat PDF document?
Hoe dan ook, MIM vereist een multipliciteit. Dus dat is interessant; de meeste modellen die wij zien hebben die niet als de mult 1 is.

Hoe zou een tool dat moeten afhandelen? Hoe verwachten jullie dat bijv. Imvertor hiermee omgaat? 1/ Foutmelding, 2/ default naar 1.

**Comment by wilkoquak** [comment]
Die regel voor pagina 19 is een conventie die alleen voor hun eigen document geldt, dus niet voor UML diagrammen an sich. Als je zou willen dat dit ook voor MIM geldt zou je dat dus in de MIM standaard moeten opnemen. Daarna kan dat geïmplementeerd worden door Imvertor.

Wat betreft de afhandeling  in tools: Ik zou het fijn vinden als een tool me zou waarschuwen als ik vergeet een kardinaliteit te plaatsen en dan defaulten naar 1 is wel fijn voor de backwards compatibiliteit.

**Comment by ArjanLoeffen** [comment]
Okay, dat bouwen we dan zo.
Er komt een waarschuwing

>  No target multiplicity specified. Assuming 1.

wanneer je geen target kardinaliteit hebt gezet. En we plaatsen er dan "1".
Dit heeft betrekking op bijvoorbeeld de volgende onderdelen:

![image](https://user-images.githubusercontent.com/12828217/199246703-db2a5ded-d32f-431e-90ff-933bc7ced48a.png)

**Comment by melsk-r** [comment]
Beetje mosterd na de maaltijd maar ik kan me hier helemaal in vinden. Ik denk dat dit issue kan worden afgesloten.
