### ISSUE TITLE
ZIP file wordt geblokkeerd door Kadaster virusscanner

### ISSUE THREAD

**Issue by kad-mesdat** [Imvertor/Imvertor-Maven#209]
Als ik een imvertor resultaat-zip doorstuur per mail dan wordt deze bij het opslaan leeg gegooid door onze mail virusscanner. 
Als ik dezelfde zipfile uitpak en dan weer met 7zip inpak dan kan ik de zipfile wel versturen en laat de virusscanner de inhoud met rust. 

Zou het kunnen zijn dat er een security issue is met de Zip maker die jullie gebruiken? Of dat er in de metadata iets is wat de zip onbetrouwbaar doet lijken?
 
Binaire vergelijking me beyond compare levert geen verschillen op.

**Comment by maartenkroon** [comment]
Overigens staat GMail ook niet toe om een Imvertor ZIP resultaat te mailen. Maar in dat geval maakt het herinpakken van de files als .zip (of als .7z) bestand niet uit, ook die kan niet worden verstuurd. In de betreffende ZIP zitten Javascript (.js) files en in de  documentatie van GMail staat ook dat deze files inderdaad niet kunnen worden verstuurd:

_Gmail wil je account beschermen tegen potentiële virussen en schadelijke software, en staat daarom het volgende niet toe als bijlage:
bepaalde bestandstypen, ook als deze zijn bijgevoegd in gecomprimeerde vorm (zoals in een gz- of bz2-bestand) of in gearchiveerde vorm (zoals in een **zip**- of tgz-bestand),_
....
_De volgende bestandstypen worden geblokkeerd door Gmail:
.ade, .adp, .apk, .appx, .appxbundle, .bat, .cab, .chm, .cmd, .com, .cpl, .dll, .dmg, .ex, .ex_, .exe, .hta, .ins, .isp, .iso, .jar, **.js**, .jse, .lib, .lnk, .mde, .msc, .msi, .msix, .msixbundle, .msp, .mst, .nsh, .pif, .ps1, .scr, .sct, .shb, .sys, .vb, .vbe, .vbs, .vxd, .wsc, .wsf, .wsh_

**Comment by kad-mesdat** [comment]
De zipfile van de run:
cdmkad-Kapri-0.1-3-20210701-20211013-103659
Het attatchen lukte niet (drag and drop) want volgens github was het bestand leeg :-) _Try again with a file that's nog empty_

Ik vermoed dat ik hem ook niet kan versturen. Misschien als zip in zip?

**Comment by kad-mesdat** [comment]
Het lijkt er op dat dit een (tot op heden onoplosbaar) probleem is van outlook en dus niet met de zip te maken heeft. Het issue kan hier dus worden gesloten.
