### ISSUE TITLE
Soms xlink- xlinks conflict

### ISSUE THREAD

**Issue by kad-mesdat** [Imvertor/Imvertor-Maven#217]
In sommige modellen krijg ik de volgende error:

`XML schema: A schema cannot contain two global components with the same name; this schema contains two occurrences of 'http://www.w3.org/1999/xlink,simpleLink'. [xlink/1.0.0/xlink.xsd:17]`

Een praktische oplossing voor deze fout is het verwijderen van de xlinks.xsd. Blijkbaar ontstaat er ergens een mixup.
We hebben bij het Kadaster gekozen voor xlink.xsd. Tenzij er een afspraak is waar ik niet van weet zou de xlinks ook weggelaten kunnen worden. In de readme staat daar een hint naar: 
```
This XML Schema Document named xlinks.xsd has been stored here based 
on the change request: 
OGC 05-068r1 "Store xlinks.xsd file at a fixed location"

Arliss Whiteside, 2005-11-22
```

Voor een voorbeeld zie: 
KadasterJobscdmkad/Kapri/20210701:  2021-11-01-16-34-57-851

**Comment by ArjanLoeffen** [comment]
Dit probleem ken ik en ik heb er al eens naar gekeken. Het heeft te maken met de configuratie van externe schema's van organisatie die alle een andere naam hanteren. Omdat de schema's bij elkaar komen in een applicatie gaat dat soms mis.

De oplossing is niet simpel maar we kijken ernaar.

**Comment by kad-mesdat** [comment]
Op basis van een check van een collega is het vermoeden ontstaan dat https://www.ogc.org/blog/1597 en https://www.geonovum.nl/over-geonovum/actueel/belangrijke-informatie-over-wijziging-ogc-standaarden nog niet (goed) zijn doorgevoerd in de meegegenereerde xsd. 
op regel 27- 28 van gmlBase staat

   <import namespace="http://www.w3.org/1999/xlink" schemaLocation="../../xlink/1.0.0/xlinks.xsd"/>

De namespace is daarbij goed, maar de schemaLocation zou dan toch http://www.w3.org/1999/xlink.xsd of een lokale (geonovum) versie daarvan moeten zijn.

**Comment by kad-mesdat** [comment]
Ik heb dit even verder bekeken en het bestand op opengis.net (http://schemas.opengis.net/gml/3.2.1/gmlBase.xsd) bevat op die regel de volgende code: 
`<import namespace="http://www.w3.org/1999/xlink" schemaLocation="http://www.w3.org/1999/xlink.xsd"/>`

en Imvertor levert in ..\xsd\gml\3.2.2\gmlBase.xsd:
`   <import namespace="http://www.w3.org/1999/xlink"
           schemaLocation="../../xlink/1.0.0/xlinks.xsd"/>` 

Ofwel de "gmlBase.xsd" van Imvertor moet worden bijgewerkt met de versie van opengisnet, waar de s niet achter xlink staat .

**Comment by kad-mesdat** [comment]
Graag even meenemen in een volgende release.. Heb hier last van bij het genereren van het KK5 model. ([2022-02-24-09-18-59-909](https://imvertor.armatiek.nl/imvertor-executor/dashboard/app?subpath=imkad%2FKK-Product%2F20211101&job=2022-02-24-09-18-59-909)) Het gaat mis bij het genereren van de volledige gml.

**Comment by kad-mesdat** [comment]
Last valt mee, had imvertertor nog op 1.64. staan.. vandaar, maar als het nog niet gefixt is (ff de gmlbase file vervangen) dan graag alsnog.

**Comment by ArjanLoeffen** [comment]
Ik denk dat @ThiesMesdag gelijk heeft. xlinks.xsd referentie in de configuratie moet worden vervangen door xlink.xsd.

W3C: www.w3.org/TR/xlink zegt:

> A permanent copy of this schema document is available at http://www.w3.org/XML/2008/06/xlink.xsd.

Ook daar wordt dus voor de s-loze naam gekozen.

**Comment by ArjanLoeffen** [comment]
Dat probleem is opgelost. Er zijn geen referenties meer naar xlinks.xsd.
