### ISSUE TITLE
externe referentielijst niet gevuld

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#225]
Voor het registratieobject Geologisch booronderzoek wordt een externe referentielijsten in de respec-catalogus niet gevuld. In EA wordt bij de tv Locatie een URL gezet naar een publiek toegankelijke referentielijst in XML-formaat. Bij het aanbieden aan imvertor worden geen fouten gegenereerd, de tabelstructuur wordt ook aangemaakt, maar de inhoud blijft leeg. Het probleem heeft zich eerder voorgedaan bij hetzelfde registratieobject. Alleen de  inhoud van de refentielijst is onlangs gewijzigd.

**Comment by ArjanLoeffen** [comment]
De inhoud is niet meer een domeintabel, maar een waardenlijst:

![image](https://user-images.githubusercontent.com/12828217/145564865-ebaa821d-af34-43c1-9301-0eed344304d3.png)

De software is ingericht op domeintabellen, met een soortgelijke opbouw:

![image](https://user-images.githubusercontent.com/12828217/145564958-22e22294-c3bf-4ff1-9bbd-89def6938c15.png)

We kunnen de software aanpassen, of jullie noemen hernoemen het root element.

**Comment by WijnandvanRiel** [comment]
Ok, ik overleg even met Bregje.

**Comment by WijnandvanRiel** [comment]
Hoi Arjan,
Je hoeft niets aan te passen. We hebben onze werkinstructie geupdate met onderstaande informatie en het rootelement van de referentie-xml aangepast.
Bedankt voor de snelle reactie en alvast een goed weekend.

Met groet,
Wijnand
