### ISSUE TITLE
Warning mbt scalaire types

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#227]
Sinds een dag krijgen we bij het aanbieden van modellen aan imvertor de warning: No native scalars used Imvert2validation.xsl / nl.imvertor.common.Messenger

**Comment by ArjanLoeffen** [comment]
Als  de waarde van nativescalars yes is, wordt aangenomen dat bijv.
Characterstring letterlijk mag worden ingetikt.  Bij jullie is die waarde
yes. Maar je gebruikt die native  scalars niet.  Vandaar de waarschuwing.
Nb. Nieuw sinds enkele dagen.

--
Arjan vanaf mobiel

Op wo 15 dec. 2021 13:51 schreef Wijnand ***@***.***>:

**Comment by ArjanLoeffen** [comment]
Ja, dat kun je zelf doen zoals je beschrijft of centraal regelen in in de
properties file op de server.  Wat wil je doen?

--
Arjan vanaf mobiel

Op wo 15 dec. 2021 14:18 schreef Wijnand ***@***.***>:

**Comment by WijnandvanRiel** [comment]
We gaan het voorlopig zelf regelen in de properties die we meegeven bij het aanbieden van modellen.

**Comment by WijnandvanRiel** [comment]
We gaan het voorlopig oplossen in de properties-file en nog niet op server niveau
