### ISSUE TITLE
Datatype AN (niet zelf ingetypt, maar een modelelement) wordt afgekeurd

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Imvertor/Imvertor-Maven#235]
Ik probeer een IM te draaien waarin een UML-datatype met de naam AN is gedefinieerd. 

![Uploading AN-datatype.png…]()

Er komt echter een error:
ERRORIMBAGLV::Objecten::Nummeraanduiding.huisletter (attrib) = huisletter {34143E2D-A2C2-42b2-BCC6-EAFD511142DB}Native scalar "AN" not allowed Imvert2validation.xsl / nl.imvertor.common.Messenger

Vermoedelijk is het met de hand invullen (native) van AN niet meer toegestaan. Helemaal prima.

Echter, in IMBAGLV zit een zelf gedefinieerd primitief datatype AN. Zeg maar de nette manier om een AN type te definiëren, zodat AN intypen niet meer nodig is. 

Maar dit wordt nu dus onterecht afgekeurd (in mijn optiek). Voorheen wat dit nog wel toegestaan, dus ik vermoed dat dit een onbedoelde bijwerking is van een verbetering. 

Wellicht wordt de controle op zelf ingetypte datatypes zoals AN iets te vroeg in het controle proces uitgevoerd en op de Name van het datatype zonder te kijken of het een String is of een element met de naam AN.

**Comment by lennartvanbergen-kadaster** [comment]
Het is wat minder urgent. ik heb het datatype hernoemd naar AN-MES1 maar dat moet weer terug naar het UML-Datatype met de naam 'AN' zodra dit weer kan. Het is dus nog steeds wel urgent want we kunnen een model nu niet releasen.

**Comment by ArjanLoeffen** [comment]
De code documentatie zegt:

> Een type dat niet in het model terug te vinden is wordt opgevat als een scalair type. Als aangegeven is dat zulke "native scalars" niet worden gebruikt (property nativescalars = no) wordt dit gemeld.

Het lijkt er dus op dat je de parameter 

`nativescalars = yes`

had gezet. Als je hem uitzet moet het goed gaan. Ik heb zelf testmodellen waarin ik een primitief type AN definieer, en ik kan het zonder errors naar verwijzen.

**Comment by lennartvanbergen-kadaster** [comment]
Bedankt voor je oplossing. 

Genereren met: 
nativescalars      	= no 
gaat inderdaad goed. 

--

Ik zou echter op zich wel verwachten dat een zelf-gedefinieerd UML-Datatype (met een passend stereotype) altijd zou mogen, en dat deze bij 
nativescalars      	= yes
niet leidt tot een error. 

Tenzij inderdaad met 
nativescalars      	= yes
bedoeld wordt dat AN als ingetypte tekst mag, 
maar ook dat daarom een UML-Datatype met een gereserveerde "native" naam een conflict geeft. 

Maar ik zou verwachten dat met 
nativescalars      	= yes
bedoeld wordt dat alles mag wat met 
nativescalars      	= no
mag, maar aanvullend je ook bv. AN mag intypen. 

Goed, ik kan gewoon verder, dus er is geen urgentie meer vanuit deze kant.

Bedankt voor je oplossing!

**Comment by ArjanLoeffen** [comment]
De gedachte is: je kunt als je dat wilt typen intikken: `CharacterString`, `Integer`, of zelf `AN`. Het lijstje van typen is vast en keihard afgeschermd. je kunt niet zelf een Integer type maken (net als in normale programmeertalen).

Het lijstje in te tikken typen is te configureren, zie als voorbeeld de MIM1.0 typen: [hierzo](https://github.com/Imvertor/Imvertor-Maven/blob/master/src/main/resources/input/MIM/cfg/metamodels/MIM10-scalar.xml)

**Comment by lennartvanbergen-kadaster** [comment]
Aha, AN zit in dat lijstje. Ok, bedankt voor de toelichting.
