### ISSUE TITLE
Tv Lengte 0..10 geeft fout

### ISSUE THREAD

**Issue by kad-mesdat** [Imvertor/Imvertor-Maven#236]
Bij een testje probeerde ik een lengte 0..10 te specificeren voor een characterString attribuut in (Job 2022-01-17-16-12-14-573) DIt leidde tot de volgende foutmelding:

`XML schema: Invalid attribute value for 'value' in element 'length'. Recorded reason: cvc-datatype-valid.1.2.1: '0..10' is not a valid value for 'nonNegativeInteger'. [Kapri/Kapri/v20210505/Kapri-test_Levering_v1_0.xsd:83] `

Dit is echter niet waar, zie bijvoorbeeld https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#nonNegativeInteger

In de Job daarna (2022-01-17-16-19-17-547) met lengte 1..10 ging het wel goed. Dus mijn conclusie is dat de lengte 0 onterecht word afgekeurd.

**Comment by ArjanLoeffen** [comment]
Deze melding kom van Xerces, een XML schema parser. Die staat als zeer betrouwbaar te boek.

![image](https://user-images.githubusercontent.com/12828217/149914590-88b4971d-9379-401b-8ce0-df784b0afc62.png)

De waarde kan alleen een nonNegativeInteger zijn.  Ik vermoed dat de invoeging van xs:length niet terecht is. Hij moet er gewoon uit. Is het functioneel juist dat het dit wordt?

![image](https://user-images.githubusercontent.com/12828217/149915529-973e7f52-1e13-47ca-845a-26d151635cae.png)

**Comment by kad-mesdat** [comment]
Volgens mij is het probleem dat lengte 0..10 niet goed wordt gelezen. 
Bij lengte 1..10 wordt de 1 in minLength gezet en de 10 in maxLength.
Bij lengte 0..10 wordt 0..10 in length gezet in plaats van 0 in minLength en 10 in maxLenght
Length zou alleen gevuld moeten worden als er een enkel getal staat dus bij 'lengte =n' 
Bij 'lengte = n..m' moeten min en max length gevuld worden.

**Comment by ArjanLoeffen** [comment]
Okay, dat pas ik aan.

**Comment by ArjanLoeffen** [comment]
Ik heb de fix doorgevoerd in 1.65.4
