### ISSUE TITLE
"Role-based" informatiemodellen: uitlezen van TV relatiemodelleringtype?

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#242]
Het feit dat een IM rol-gebaseerd is wordt nu nog vastgesteld op metamodel niveau. Voorbeeld:

> `/MIM/cfg/metamodels/MIM11-ISO.xml` waarin opgenomen: `<feature name="role-based">true</feature>`

MIM introduceert TV `relatiemodelleringtype`. Dat betekent dat het metamodel wordt verwerkt op basis van een tagged value waarde. We moeten daar wat mee. Keuzes:

1/ In éérste instantie de tagged value `relatiemodelleringtype` uitlezen, en als die er niet is, terugvallen op role-based.
2/ Checken of beide waarden gelijk zijn.
3/ Feature role-based laten vallen.

Dat laatste kan niet voor niet-MIM metamodellen. Mijn voorstel is:  optie 1.

NB Deze eigenschap speelt op dit moment een rol in validatie, XSD compiler, Office (respec) compiler, en MIM serialisatie. Gelukkig niet bij het interpreteren van de XMI en het samenstellen van het systeemformaat.

**Comment by melsk-r** [comment]
Waarom zou je in 1. als de tagged value `relatiemodelleringtype` er niet is automatisch terugvallen op role-based? Waarom niet alleen role-based hanteren als dat gedefinieerd is in de tagged value `relatiemodelleringtype`?
Of waarom maken we het specificeren van een waarde in de tagged value `relatiemodelleringtype` niet verplicht?

Niet dat ik hier hele sterke gedachtes over heb maar ik vroeg het me zomaar af. Altijd goed om argumenten te hebben voor de keuzes die we maken.

**Comment by ArjanLoeffen** [comment]
`relatiemodelleringtype` kunnen we niet verplichten voor niet-MIM-modellen; die TV bestaat dan niet in het metamodel. 
Daarnaast zou ik bestaande aanpak niet willen veranderen; er komt dus "iets bij". Als eenmaal iedereen op MIM over is gestapt is `role-based` niet relevant meer, en kan vervallen.

**Comment by ArjanLoeffen** [comment]
In sluit 'm.

**Comment by melsk-r** [comment]
Ok, duidelijk.

**Comment by PalmJanssen** [comment]
Ah, interessant, ik dacht ook dat je dat met de TV kon bepalen, niet dus. Toch nog een vraag. Bij onze Geonovum configuratie blijkt role-based = true standaard te zijn ingevuld. Kan ik dat als gebruiker instellen? Ik wil namelijk soms op conceptueel niveau wel relatienaam based kunnen werken. Power to the user zeg ik maar.

**Comment by ArjanLoeffen** [comment]
> Ah, interessant, ik dacht ook dat je dat met de TV kon bepalen, niet dus. Toch nog een vraag. Bij onze Geonovum configuratie blijkt role-based = true standaard te zijn ingevuld. Kan ik dat als gebruiker instellen? Ik wil namelijk soms op conceptueel niveau wel relatienaam based kunnen werken. Power to the user zeg ik maar.

Paul, dat is precies wat we hebben toegevoegd; daar gaat de opmerking van Robert over. Dus als je in MIM modellen de MIM TV goed vult, dat kun je zelf bepalen welke aanpak je volgt: rol of relatie gebaseerd.
