### ISSUE TITLE
Quotes vallen weg bij transformatie van JSON naar YAML

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#244]
De YamlCompiler stylesheets genereren JSON code die m.b.v. de in de Java Class 'YamlCompiler.java' opgenomen code:

`bodyFile.toYaml(yamlFile)`

wordt omgezet naar yaml.
Nu komt het soms voor dat bij het genereren van de JSON de volgende construct wordt aangemaakt:

`"description": "",`

wat wordt vertaalt naar de yaml code:

`description:`

Dit is echter niet correct, het moet zijn:

`description: ''`

Verzoek is om te kijken of de transformatie op dit punt op de e.o.a. wijze te configureren is. Dit probleem doet zich pas sinds kort voor.

**Comment by melsk-r** [comment]
Bij deze [voorbeelden van zowel de Json als de gerelateerde Yaml](https://github.com/Imvertor/Imvertor-Maven/files/7986884/json-yaml.zip).

**Comment by melsk-r** [comment]
Probleem doet zich niet alleen voor bij lege descriptions maar ook bij enumeratie waarden zoals '01', '02', etc...

**Comment by melsk-r** [comment]
Bij deze [voorbeelden van de met de 1.64 versie gegenereerde Json en gerelateerde Yaml](https://github.com/Imvertor/Imvertor-Maven/files/8003556/correcte-json-yaml.zip). Hierin is van het beschreven probleem nog geen sprake.

**Comment by ArjanLoeffen** [comment]
We gebruiken [FasterXML java code](https://fasterxml.github.io/jackson-dataformats-text/javadoc/yaml/2.9/overview-summary.html)

Volgens [deze spec](https://fasterxml.github.io/jackson-dataformats-text/javadoc/yaml/2.9/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.Feature.html#ALWAYS_QUOTE_NUMBERS_AS_STRINGS) (bij ons disabled) worden nummers omgezet naar bijv. 99. Misschien moeten we hem enabled, dan wordt het "99" etc,. 

Volgens [deze spec](https://fasterxml.github.io/jackson-dataformats-text/javadoc/yaml/2.9/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.Feature.html#MINIMIZE_QUOTES) (bij ons enabled) worden strings die geen quotes hoeven te hebben weggelaten. Dat lijkt hier fout te gaan. We kunnen 'm enabled, het gaat hier wat minder om "leesbare" configuratie, maar Yaml is nu eenmaal het input formaat voor OpenAPI omgevingen zo begrijp ik.

Een testje op Json:
```
    "naam": "",
    "uitleg": "03",
```

levert yaml:
```
  naam: ""
  uitleg: "03"
```

Dekt deze test de lading?

**Comment by melsk-r** [comment]
Ik heb het idee van wel maar ik laat Johan nog even checken.

**Comment by JohanBoer** [comment]
> We gebruiken [FasterXML java code](https://fasterxml.github.io/jackson-dataformats-text/javadoc/yaml/2.9/overview-summary.html)
> 
> Volgens [deze spec](https://fasterxml.github.io/jackson-dataformats-text/javadoc/yaml/2.9/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.Feature.html#ALWAYS_QUOTE_NUMBERS_AS_STRINGS) (ALWAYS_QUOTE_NUMBERS_AS_STRINGS, bij ons disabled) worden nummers omgezet naar bijv. 99. Misschien moeten we hem enabled, dan wordt het "99" etc,.
> 
> Volgens [deze spec](https://fasterxml.github.io/jackson-dataformats-text/javadoc/yaml/2.9/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.Feature.html#MINIMIZE_QUOTES) (MINIMIZE_QUOTES, bij ons enabled) worden strings die geen quotes hoeven te hebben weggelaten. Dat lijkt hier fout te gaan. We kunnen 'm enabled, het gaat hier wat minder om "leesbare" configuratie, maar Yaml is nu eenmaal het input formaat voor OpenAPI omgevingen zo begrijp ik.
> 
> Een testje op Json:
> 
> ```
>     "naam": "",
>     "uitleg": "03",
> ```
> 
> levert yaml:
> 
> ```
>   naam: ""
>   uitleg: "03"
> ```
> 
> Dekt deze test de lading?

Ja

**Comment by ArjanLoeffen** [comment]
In nu nog onderdeel van dev-1.66.

**Comment by JohanBoer** [comment]
> In nu nog onderdeel van dev-1.66. @lennartvanbergen-kadaster ook Kadaster maakt gebruik van de omzetting naar Yaml. Is het okay deze settings ook in de Json schema Yaml te hanteren?

Ik zou verwachten dat dit z.s.m. in een patch opgelost wordt. Ik snap dat jullie met releases willen werken (helemaal voor ook), maar dit is functionaliteit die in een vorige versie wel goed werkte en nu niet meer. Een bug dus.
