### ISSUE TITLE
MIM1.1 Datatypen afhankelijk van GUID 

### ISSUE THREAD

**Issue by kad-mesdat** [Imvertor/Imvertor-Maven#248]
Een van onze modelleurs had een vervelende fout bij het genereren:
`Reference to "CharacterString" in outside model is not identified, but should be, as duplicates occur using mapping "NEN3610_GML322PROFILE_ENV" Imvert2interface.xsl / nl.imvertor.common.Messenger`

In zijn model zowel de GML datatypen als de MIM datatypen. Maar dat was het probleem niet. Hij had alles goed gekoppeld aan het MIM1.1. datatype CharacterString (in dit geval). Na veel zoeken bleek dat de GUID van zijn CharacterString niet dezelfde was als die in andere modellen wordt gebruikt en die wel werkt. 
Hij heeft dus ofwel de guids gestript bij het importeren ofwel een verkeerd MIM1.1 package geïmporteerd. 

Hiervoor zou een betere foutmelding kunnen worden gegenereerd. iets als:
` Unknown reference to "Characterstring": GUID should be "{18BFBA8D-E3F4-4d8c-9A8F-4429FA54B041}"`

Beter nog dan een verbeterde foutmelding zou zijn om imvertor hier robuust voor te maken. Als datataype = CharacterString dan assume CharacterString met {18BFBA8D-E3F4-4d8c-9A8F-4429FA54B041} en ook voor de andere datatypen natuurlijk. 

De volgende stap is dan dat we "gewoon" de primitieve datatypen van EA kunnen gebruiken en dat Imvertor die op de achtergrond mapt naar de goede definitie. Maar er waren vast goede redenen om dat niet te gebruiken, maar welke?

**Comment by ArjanLoeffen** [comment]
De "CharacterString" moet je opvatten als een "key", een unieke ID, in een tabel. Daaraan hangt allerlei informatie. Twee keys zouden eigenlijk niet hetzelfde moeten zijn. 

Omdat conceptual schema's worden bijeen gevoegd onder een zgn "mapping" ontstaat een tabel met keys op basis van meerdere mappings. daarin kunnen dubbelingen voorkomen. Dat is hier gebeurd: twee "CharacterString"s.

Er zijn twee manieren om dit op te lossen: 
1. Koppel aan de key de ID. Dat is wat we hier doen:  "CharacterString{18BFBA8D-E3F4-4d8c-9A8F-4429FA54B041}"
2. Verwijder duplicaten in de mapping. We kunnen zulke duplicaten zelfs signaleren als je de mapping configureert. Er zijn dan geen twee "CharacterString" keys en dat is eigenlijk het beste.

Naar mijn mening is er geen 3e optie. We kunnen op basis van alleen de key "CharacterString" niet "weten" welke je bedoeld hebt. En dat komt omdat we niet weten dat de CharacterString referentie uit een "EA MIM" package komt. Die informatie komt niet beschikbaar bij het overdragen van de XMI naar de server....

**Comment by ThiesMesdag** [comment]
Gerelateerd aan #288 Het voorstel is dan om 1 automatisch te laten doen door Imvertor, zodat je dat als gebruiker niet hoeft te doen en alleen de "key" in je model hoeft te noemen.

**Comment by ArjanLoeffen** [comment]
Zie #329 
Ik denk dat daarmee dit issue niet meer relevant is en kan worden gesloten.
