### ISSUE TITLE
Introduce TV check on minoccurs-maxoccurs

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#25]
now we have imf:check-tagged-value-occurs(); this should be reimpleehted to check min and max occurrences of tagged values. Also parameter for $validate-tv-missing should be $validate-tv-occurrence.

This isreuqired by ISO19103 GML featureCollecion; the number of FeatureCollection tagged values must be 1 at most. 
CLI/allowduplicatetv should be removed and redirected to the config for TV.

**Comment by ArjanLoeffen** [comment]
Thies, je mening?

**Comment by ThiesMesdag** [comment]
Gaat dit inderdaad over tagged values? Is het niet zo dat in de gml (ISO19103 GML featureCollecion) maar 1 feature collection mag voorkomen en dat dit dus over de xsd gaat? 
Maar heb je dit niet al geïmplementeerd? In effect is het voor de tv's toch hetzelfde?
Ik heb dus niet zo'n mening op dit moment...
