### ISSUE TITLE
Tagged value "Herkomst" not expected on stereotype "EXTERN"

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#251]
We krijgen een warning bij het gebruik van versie 1.66 van Imvertor die we bij 1.65 niet kregen:
<html>
<body>

# | Type | Element | Message
-- | -- | -- | --
00001 | WARNING | RO-BRO:: = http://www.bro.nl/conceptual-schemas/bro/1.0/ OUTSIDE-1 | Tagged value "Herkomst" not expected on stereotype "EXTERN" Imvert2validation.xsl / nl.imvertor.common.Messenger
00002 | WARNING | GML3:: = http://www.bro.nl/conceptual-schemas/ISO19107 OUTSIDE-2 | Tagged value "Herkomst" not expected on stereotype "EXTERN" Imvert2validation.xsl / nl.imvertor.common.Messenger

</body>
</html>

**Comment by WijnandvanRiel** [comment]
In het report wat je noemt staat alleen een warning dat er een nieuwe versie van imvertor beschikbaar is. In hetzelfde report staat 
![image](https://user-images.githubusercontent.com/57146824/170290494-e219d171-1e0a-4a06-9704-747640f9e327.png)
Ik heb altijd begrepen dat we al wel op mim 1.1 zitten. Dus ik het snap nog niet waar de warning vandaan komt.

**Comment by ArjanLoeffen** [comment]
Probleem is zover ik kan vaststellen opgelost in de volgende release van Imvertor. Herkomst is daarin wel tagged value van Extern.

**Comment by ArjanLoeffen** [comment]
Bij het genereren van Imvert formaat worden zgm. OUTSIDE packages samengesteld. Die zijn door het systeem gedefinieerd en hoeven niet te worden gevalideerd.  Tot nu toe deden we dat wel en dat gaf onder specifiek omstandigheden waarschuwingen. Dat hebben we nu ondervangen.

**Comment by HanWelmer** [comment]
Issue still occurs. 
See job 2023-03-01-13-36-31-410 based on SAD Logical Model.

**Comment by ArjanLoeffen** [comment]
Je moet de nightly build gebruiken.

**Comment by jacobvosimpronotion** [comment]
Gisteren geprobeerd met de nighly build, maar de foutmelding verschijnt nog steeds. Zie de job: https://imvertor.armatiek.nl/imvertor-executor/dashboard/app?subpath=Conceptual%20model%2FMijnbouwconstructies%20%28EPC%29%20-%20conceptueel%2F20210315.

**Comment by jacobvosimpronotion** [comment]
Zojuist nog maar eens gedraaid met de nightly build, en nu verschijnt de foutmelding niet meer.
