### ISSUE TITLE
Respec: Wanneer een attribuut onderdeel is van een keuze, wordt het formaat niet als een hyperlink afgebeeld

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#258]
Wanneer een attribuut onderdeel is van een keuze, wordt het formaat niet als een hyperlink afgebeeld (bijvoorbeeld):

![image](https://user-images.githubusercontent.com/12828217/171365642-f5c43a6e-aa3d-44c4-98ee-fdb5a6a1cf81.png)

**Comment by AnnemiekDroogh** [comment]
In de documentatie welke ik vandaag gegenereerd heb, is het formaat in bovenstaande voorbeeld nog geen hyperlink. 
Klopt dit?

**Comment by ArjanLoeffen** [comment]
Ik kijk nu in het resultaat 

https://imvertor.armatiek.nl/imvertor-executor/dashboard/app?subpath=SIM%2FIMWOZ%2F20220922&job=2022-08-18-09-43-31-471

met de catalogus

https://imvertor.armatiek.nl/download/dat/2022-08-18-09-43-31-471/work/app/cat/IMWOZ.html

Die gaat goed al tref ik bovenstaande attribuut niet op dezelfde manier aan. Ik wete niet welk model bovenstaand voorbeeld tot resultaat had.

**Comment by AnnemiekDroogh** [comment]
Bovenstaand model is inderdaad ons informatie model. 
Als ik kijk in paragraaf 2.1.11.4.1 Keuze BsnOfAnpId dan zie ik de een overzicht met keuze elementen. 
Ik klik op het Keuze element bsn. Ik kom dan terecht in paragraaf 2.1.11.9.4. 

Hier staat Attribuutsoort 'BsnOfAnpId bsn' en hier is het formaat 'IdentificatiePRS' geen hyperlink. 
Ook niet bij de volgende drie attribuutsoorten (anp.identificatie, rsin en ann.identificatie). 
Als ik kijk bij de volgende keuze 'KeuzeAdresBinnenBuitenland' dan is hier het formaat wel een hyperlink. 

Scroll ik verder naar beneden dan zie je dat er veel meer hyperlinks zijn en sommige niet. Hoe krijg ik alle formaten als hyperlink in de documentatie?

**Comment by ArjanLoeffen** [comment]
Aha, ik zie het. Dit zullen we corrigeren.

De functionele bedoeling is dat we overal een hyperlink plaatsen tenzij er geen plek is waar we naar kunnen verwijzen, dus er is geen aparte sectie die betreffende model element behandelt.

**Comment by ArjanLoeffen** [comment]
Zover ik kan zien betreft het primitieve datatypen die in het model worden gedefinieerd, waarnaar wordt verwezen in detailweergave. Voorbeeld daarvan is IdentificatiePRS, IdentificatiePRSalternatief, IdentificatieBAG etc. Deze worden nu omgeleid naar de globale definitie in het betreffende domein.

Ik kan dit als een minor in de master opnemen. Ik veronderstel daarbij dat degenen die gebruik maken van hyperlinking deze correctie accepteren. Wanneer (zoals bij BRO) geen aparte secties bestaan waarin informatie wordt gegeven over primitieve datatypen vervalt deze hyperlink automatisch.

**Comment by ArjanLoeffen** [comment]
Doorgevoerd.
