### ISSUE TITLE
tagged Value {is_ID} opnemen in de details van een attribuut

### ISSUE THREAD

**Issue by kad-mesdat** [Imvertor/Imvertor-Maven#266]
In onze modellen gebruiken we soms een attribuutsoort om een referentie naar een ander objecttype te maken. Die heeft dan het BRK-Id als type. Maar die attributen zijn niet identificerend en de identificatie wel. Bij identificatie staat ook {id} in het diagram, maar niet in de tabel met attribuutsoort details. Dat zou wel beter zijn ook om ze te onderscheiden van andere attributen met het BRK-Id als data type.

![image](https://user-images.githubusercontent.com/67012704/172656838-f444228b-016b-4f12-9b95-deea7fac257f.png)

**Comment by ArjanLoeffen** [comment]
Onderdeel van 1.67.

**Comment by ArjanLoeffen** [comment]
Ben het niet eens met het toekennen van een BRK-ID, omdat je dan van alles kunt opnemen als "waarde" van een attribuut. Ook is me niet duidelijk wat je nu precies wilt?

**Comment by kad-mesdat** [comment]
Afgezien van de schoonheid van deze oplossing is de bedoeling dat ik vanuit de KadastraleGrens een referentie kan leggen naar een perceel links en een perceel rechts. Dus naar het BRK-Id van die percelen. 
Daarom hebben perceelLinks en perceelRechts BRK-Id als datatype, maar géén {isID} (het zijn immers geen Id's, maar referenties). PerceelLinks en PerceelRechts hebben wel een domein attribuut omdat alleen gerefereerd mag worden naar Id's uit een specifiek domen (NL.INKAD.KadastraalObject in dit geval). 
(Deze modellering is niet nieuw, maar zat al in de vorig versie van het Kadastrale kaart model. Maar door de wijziging van het compositeId naar BRK-Id werkte dat niet meer. )


Een andere oplossing zou zijn om een complexdatatype te maken "BRK-IdReferentie" 
![image](https://user-images.githubusercontent.com/67012704/177142820-b630dab3-3e26-493d-91e4-9e183c0da417.png)

Of een relatie naar een (eigenlijk niet bestaand) referentie object
![image](https://user-images.githubusercontent.com/67012704/177143641-e15925c5-0da5-41ce-9c44-c907d4790721.png)

**Comment by kad-mesdat** [comment]
Ik heb net even gekeken maar het werkt nu wel  zoals gespecificeerd. Dus inderdaad hoef je nu niets meer te veranderen Maar dan is het fixed ipv won't fix.

**Comment by ArjanLoeffen** [comment]
@ThiesMesdag Ik snap het nog steeds niet. Je kunt niet refereren in een model naar een ID. je kunt alleen daat objecten of datatypen genereren. dat dioe een id _hebben_  is m.i. een heel ander issue...

**Comment by kad-mesdat** [comment]
Klopt, in het model heb ik een attribuut perceelLinks en perceelRechts met als type een BRK-Id. Dus daar refereer ik niet naar een ID maar heb ik een attribuutsoort opgenomen met als datatype BRK-Id met een fixed domein. 

Zodat in de xml perceelLinks en perceelRechts gevuld kunnen worden met een id van een concreet perceel (met een fixed xml attribuut domein). Zoals hieronder. 
![image](https://user-images.githubusercontent.com/67012704/177186980-7f61151b-7b98-4166-b9d2-07747e42f359.png)

**Comment by ThiesMesdag** [comment]
De oospronkelijke aanleiding voor dit issue was de regel  in imvertor dat het datatype BRK-Id alleen gebruikt kon worden bij een attribuutsoort van het type identificatie en dat bij een attribuutsoort identificatie isID aangevinkt moet zijn. De eerste regel is volgens mij komen te vervallen. Hierdoor werkt het weer in mij model.
