### ISSUE TITLE
Domein kunnen specificeren op referenties met BRK-Id

### ISSUE THREAD

**Issue by kad-mesdat** [Imvertor/Imvertor-Maven#267]
Er is een regel dat alleen bij **identificatie** attributen met als datatype **BRK-Id** en met de **{is ID} = true** kun je de **tagged value domein** opgeven. Dit domein wordt dan meegegenereerd als attribuut van het identificatie element in de xsd. 

Echter bij het gebruik van de BRK-Id als referentie naar een andere object zoals hieronder:
![image](https://user-images.githubusercontent.com/67012704/172659055-0925303a-a8b2-4ca2-862d-e072273c6837.png)
bij perceelLinks en perceelRechts moet het domein ook opgegeven kunnen worden. Daarvoor moet de regel worden aangepast.

Als type is _BRK-Id_ dan mag je de tagged value _domein_ specificeren. Deze wordt dan als attribuut bij het element in de xsd mee gegenereerd. 
```
<xs:element name="perceelLinks" minOccurs="0"> <!--type="t:BRKIdType" minOccurs="0">-->
	<xs:annotation>
		<xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: PerceelLinks is een referentie naar het perceel dat links van de Kadastrale grens ligt.</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="t:BRKIdType">
				<xs:attribute name="domein" type="xs:string" fixed="[domein]"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
```

**Comment by kad-mesdat** [comment]
Een alternatieve manier van modelleren is het gebruik van een relatiesoort naar een objecttype waarbij je kan aangeven dat alleen de ref bedoeld wordt. Dit zou een specialisatie van de relatiesoort kunnen zijn of misschien is het eigenlijk een ander type relatie, de referentierelatie. 

Een andere alternatieve oplossing is om een nieuw objecttype te introduceren en daar een relatie naar toe te leggen zoals hieronder 
![image](https://user-images.githubusercontent.com/67012704/172664388-aa90a418-c859-48a2-8df3-4a36a1a47793.png)
Dit en de manier van het issue zijn al in gebruik in modellen.

**Comment by ArjanLoeffen** [comment]
@ThiesMesdag Begrijp ik het goed dat je een regel wilt opnemen:

> Als type is BRK-Id dan mag je de tagged value domein specificeren.

Dus letterlijk "`BRK-id`"? En dat je dan in dat geval een domein meegenereert in de Kadaster schema's? 
En dat dat dan een attribuut `<xs:attribute name="domein" type="xs:string" fixed="[domein]"/>` moet zijn? Dus met de waarde van tv "domein"?

En dat dit (ook hier) niet geldt voor de ISIO19136 schema's?

**Comment by kad-mesdat** [comment]
Ja, dat bedoel ik. Anders zou het bij alle datatypen kunnen en dat is ook niet de bedoeling. 
Het alternatief is zoals hiervoor beschreven met een relatie naar een apart objecttype of een relatiesoort met een parameter.

**Comment by ArjanLoeffen** [comment]
Lastig. Wat doe je hier eigenlijk? Gebruik je nu een attribuut om een link te leggen met een ander object?

**Comment by kad-mesdat** [comment]
ja, eigenlijk alleen dat. Dus het object en z'n kenmerken en relaties zitten niet  (hier) aan het object vast. Het is de pointer naar een  perceelLinks of rechts met dat ID. Als we een relatie trekken dan komt het hele perceel in de xsd. Maar we willen alleen zeggen het linker perceel is het perceel met dit Id. Maar dat id is niet meer een composit id, maar een id met een domein attribuut in het element.

**Comment by ArjanLoeffen** [comment]
Okay. Dta is nu gebouwd. 

- Er was een regel dat domein waarden maar één keer per model kunnen worden opgegeven. Dat is nu beperkt tot "is-id" attributen.
- Er is géén regel dat het domein waar je naar verwijst binnen het model is gedefinieerd. Moet die er komen?

Voorbeeld: onderstaand schema is correct, en compleet. Check?

![image](https://user-images.githubusercontent.com/12828217/174038460-aae2da3a-6833-4d2f-a861-475bb3251d03.png)

**Comment by ArjanLoeffen** [comment]
Het is me trouwens niet duidelijk of en hoe dit in de andere producten terecht komt: documentatie, Skos, Json, etc. Heb je daar een visie op? Het wordt nu alleen "begrepen" door de Kadaster-variant in de XML schema module.

**Comment by kad-mesdat** [comment]
weet ik niet, zal ik naar kijken.

**Comment by kad-mesdat** [comment]
Voor het genereren is op de referentie nog een is id nodig. Dat is niet de bedoeling want de referentie is natuurlijk geen id. Die controle moet er dus uit.
de regel is dus als brk-id gebruikt dan kan een domein tv worden opgenomen
als de naar van het attribuut identificatie is dan moet er is_id tag worden gebruikt.

**Comment by kad-mesdat** [comment]
> weet ik niet, zal ik naar kijken.

In de gegenereerde test json zit geen attribuut domein. Dus dat is zowieso niet goed. het is wel gemodelleerd.
