### ISSUE TITLE
Opnemen van NITGCode en Putcode in juiste format in GMW-catalogus

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#269]
Zoals we in de BHR-P catalogus het domein 'Bepalingscode' hebben opgenomen, willen we in de GMW catalogus de domeinen NITGCode en Putcode opgenomen hebben.

Gewenst zijn:
- Naam = naam van het domein
- Type = "Code"
- Opbouw = Zoals bij het attribuut (dus niet bij het primitief datatype) is opgenomen in de tag 'Patroon'.

Definitie in de Enterprise Architect modellen is met Arjan doorgenomen. Screenshots zijn met hem gedeeld.

**Comment by ArjanLoeffen** [comment]
Deze vorm (domein met naam, type en opbouw) is onderdeel van een postprocessing-stap, die daar nu op is aangepast.
