### ISSUE TITLE
Tagged value op relatierol is lastig in te voeren in EA

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#275]
Tagged value op relatierol is lastig in te voeren in EA 15. Uiteindelijk komt het erop neer dat voor relatie rollen tagged values met de hand moeten worden gemaakt & ingevuld. Dat is vrij ernstig en is aangemeld bij Sparx, maar het lijkt erop dat men het geen prio heeft. We moeten een weg vinden om toch die TV's te maken.

De wegen die we kunnen  bewandelen:

1/
Mogelijkheid is om de tagged values op de relatie te plaatsen. Dat is nogal een trukendoos, maar de tagged values van de relatie komen overeen met die van de relatierol. Imvertor kan de tagged values "verplaatsen" naar de target rol als het model "relatierol leidend" is.
Nadeel is dat begrip op relatie en relatierol kan worden gespecificeerd. 
Ook wordt de definitie feitelijk als een tagged value verwerkt, en dus kunnen deze niet goed naast elkaar bestaan.
Deze problemen zijn wel oplosbaar in Imvertor, via configuraties.

2/
We kunnen ook in het notes field nieuwe secties opnemen, voor de tagged values, zoals:

```
-- Indicatie materiële historie --
Ja
-- Indicatie formele historie --
Nee
```

Imvertor plaatst de waarden Ja  en Nee in de juiste tagged value.

Hoe dan ook, we moeten een oplossing formuleren want zoals het nu gaat gaat het niet goed.

**Comment by ArjanLoeffen** [comment]
Zie ook #210 voor discussie over "wat is nou eigenlijk __het__ informatiemodel"

**Comment by PalmJanssen** [comment]
Dit issue is gerapporteerd by Sparx en in behandeling 'for future consideration'. Ik heb het opnieuw bij Sparx ingebracht nu via ISO TC211. Mogelijk help dat.
https://github.com/ISO-TC211/HMMG/issues/53

**Comment by HanWelmer** [comment]
Helaas moet er een onderscheid worden gemaakt tussen diverse versies van EA en wat het bijpassende gedrag is van het toekennen van een stereotype aan het endpoint van een association relation.

Bij **EA14** kan er wel degelijk een stereotype worden toegevoegd aan het target endpoint van een association relation, maar worden er niet automatisch tagged values toegevoegd. Oplossing: synchroniseer het stereotype (Resources -> UML Profiles -> <<gewenst profiel>> -> Rechter muisklik op gewenst stereotype -> Sync tagged values and constraints). Daarna zijn alsnog de tagged values van het sterotype toegekend bij het target endpoint van alle association relations. Daarom is het bij EA14 niet nodig handmatig tagged values toe te kennen bij het target endpoint van een association relation.

Bij **EA15** kan er geen stereotype worden toegevoegd aan het target endpoint van een association relation. Hiervoor is een [issue aangemaakt](https://github.com/ISO-TC211/HMMG/issues/53). Op basis van [meldingen van Sparx](https://sparxsystems.com/products/ea/history.html#1621) gaan we ervan uit dat het probleem is opgelost in EA16 build 1621.

Het gedrag bij **EA16** (jonger of ouder dan build 1621)hebben we niet uitgezocht.

**Comment by PalmJanssen** [comment]
Dit is al langer gelden opgelost in een nieuwe versie van de MIM Toolbox voor EA, build05

https://register.geostandaarden.nl/informatiemodel/mim/1.1.1/

Bugfix: De toekennning van <<Relatierol>> en het synchroniseren en invullen van de tagged values werkte niet goed in build04. De oorzaak daarvan lag bij een fout in EA. Het is opgelost met een workaround door in het MIM profiel de <<Relatierol>> als extensie van de UML-metaklasse Property op te nemen. In Build04 was het een extensie van de metaklasse AssociationEnd.
