### ISSUE TITLE
IHW: Correctie Conceptual schemas na verlies van mappings

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#276]
Tussen versie 1.65 en 1.66 van Imvertor zijn enkele mappings weggevallen uit de conceptual schemas. Dat bleef tot voor kort onopgemerkt maar nu blijkt dit een probleem. 
In 1.65 waren de volgende mappings beschikbaar:

- MIM11
- GML3
- IHW
- CPI
- EI
- INSPIRE
- NEN3610
- CITYGML
- IMGEO

In 1.67 zijn beschikbaar

- MIM11
- GML322PROFILE
- IHW-GENERIEK

In overleg moeten betreffende mappings worden hersteld tot de juiste en gewenst.
@MaxWelling7 Hierover graag overleg.

**Comment by ArjanLoeffen** [comment]
De folder `input\IHW\xsd\register.geostandaarden.nl` is tussen 1.65 en 1.66 weggevallen. Dit moet worden hersteld.
Deze folder bevat `IMGEO211-20130329`.
Omdat dit een Geonovum model is, stel ik voor dit op te nemen in de Genonovum conceptual schemas en daarnaar te verwijzen.

**Comment by ArjanLoeffen** [comment]
Ik zie dat bij een eerdere run (ook onder een subversie van 1.65) de volgende mapping werd geconfigureerd: 

- GML321
- CIT10
- GEX10
- INSPIRE
- INSPIRE-GEO
- INSPIRE-SOIL
- MIM11
- NEN3610
- CITYGML
- IMGEO211
- IHW-GENERIEK

Het is me niet duidelijk wat er is gebeurd, het is weer een andere mapping dan die als laatste werd gebruikt in de 1.65 serie, zie eerste commentaar. Check [dit imvertor report (inloggen)](https://imvertor.armatiek.nl/download/dat/2022-04-04-10-17-20-431/work/app/doc/index.html) voor een compleet overzicht. Wat verwacht IHW nog steeds te gebruiken (in 167 en verder)?

**Comment by ArjanLoeffen** [comment]
@PalmJanssen en @MaxWelling7  Wat mij betreft z.s.m. dit issue compleet maken en afronden. Ik heb het nu als hotfix voor IHW uitgebracht maar is niet compleet. 
Initiatief voor overleg en vaststelling juiste invulling ligt nu bij jullie.

**Comment by adbgnm** [comment]
Inderdaad twee mappings: 1 CityGML voor de CityGML objecten, en 1 IMGeo voor de specifieke IMGeo-objecten.
