### ISSUE TITLE
MIM 1.1.1 in Engels

### ISSUE THREAD

**Issue by PalmJanssen** [Imvertor/Imvertor-Maven#285]
Er is behoefte aan een MIM 1.1.1 versie waarbij alle stereotypen en tagged values in het Engels zijn opgenomen.

de BRO gebruikt een dergelijke Engelse versie van MIM 1.1.

1) Verzoek tot maken en autoriseren van een Engelse versie van het MIM 1.1.1 model.
2) Verzoek tot maken van een Engelse versie van de MIM toolbox
2) Verzoek tot toepassen van Engelse model in IMvertor

ad 1 en 2 passen eerder bij MIM beheer.

**Comment by ArjanLoeffen** [comment]
In branch https://github.com/Imvertor/Imvertor-Maven/tree/NEN3610-2022 is code opgenomen die een vertaaltabel genereert in het ZIP resultaatbestand. Deze kan gebruikt worden om de vertaling compleet te maken. Voorbeeld:

![image](https://user-images.githubusercontent.com/12828217/192483595-8d688a00-7534-4336-b4a2-c88b06fd31e3.png)

De vertalingen die er nu zijn moeten dus worden beoordeeld.

**Comment by ArjanLoeffen** [comment]
Is onderdeel van 2.0. De toolbox zal in het engels worden gegenereerd door Imvertor wanneer voor de engelse taal is gekozen.
Taalkeuze wordt doorgegeven in:

> `language = en:nl`
hier is het metamodel in het engels, en het model zelf in het nederlands.

> `language = en:en`
hier is het metamodel en het model zelf in het engels.
