### ISSUE TITLE
Ring mist in GML profiel van Kadaster

### ISSUE THREAD

**Issue by ThiesMesdag** [Imvertor/Imvertor-Maven#286]
Er is een schema waarin we de GML ring nodig hebben maar die zit niet in...
![image](https://user-images.githubusercontent.com/11945098/189896697-ae3d30a5-aa6e-4bdd-b32a-39a7469b55ad.png)
in plaats van het onderstaande, hoewel ik niet weet waarom de elementen daar 2x in zitten.
![image](https://user-images.githubusercontent.com/11945098/189896850-d140926e-c8bc-4a39-af5c-e5b0cdb2deb2.png)

In de OCG spec staat het volgende

![image](https://user-images.githubusercontent.com/11945098/189896201-03f093b1-9b61-4d72-8205-bd4a9e659a5e.png)

**Comment by ArjanLoeffen** [comment]
Mis je GM_Ring in GML en/of in het GML profile?

**Comment by ArjanLoeffen** [comment]
Kun je een voorbeeld geven van wat je als XSD constructie verwacht wanneer een attribuut is getypeerd als GM_Ring? 
Is het de bedoeling dat er zoiets uit komt?
![image](https://user-images.githubusercontent.com/12828217/191254850-552a5bb2-710e-4906-848f-34906acd9737.png)

**Comment by ThiesMesdag** [comment]
Een voorbeeld van een BGT bestand met daarin een ring. (het is een xml, maar die mag je niet als zodanig toevoegen dus daarom hernoemd naar .txt)

[Abonnementsgebied_Ooststellingwerf.xml.txt](https://github.com/Imvertor/Imvertor-Maven/files/9662393/Abonnementsgebied_Ooststellingwerf.xml.txt)

**Comment by ThiesMesdag** [comment]
Het voorbeeld voor de xsd is als in GML 3.2.2. Ik zal dat even opzoeken.

**Comment by ThiesMesdag** [comment]
Uit geometryPrimitives.xsd:
```
	<complexType name="RingType">
		<complexContent>
			<extension base="gml:AbstractRingType">
				<sequence>
					<element ref="gml:curveMember" maxOccurs="unbounded"/>
				</sequence>
				<attributeGroup ref="gml:AggregationAttributeGroup"/>
			</extension>
		</complexContent>
	</complexType>
	<element name="Ring" type="gml:RingType" substitutionGroup="gml:AbstractRing">
		<annotation>
			<documentation>A ring is used to represent a single connected component of a surface boundary as specified in ISO 19107:2003, 6.3.6.
Every gml:curveMember references or contains one curve, i.e. any element which is substitutable for gml:AbstractCurve. In the context of a ring, the curves describe the boundary of the surface. The sequence of curves shall be contiguous and connected in a cycle.
If provided, the aggregationType attribute shall have the value "sequence".</documentation>
		</annotation>
	</element>
	<element name="curveMember" type="gml:CurvePropertyType"/>
	<complexType name="RingPropertyType">
		<annotation>
			<documentation>A property with the content model of gml:RingPropertyType encapsulates a ring to represent a component of a surface boundary.</documentation>
		</annotation>
		<sequence>
			<element ref="gml:Ring"/>
		</sequence>
	</complexType>
```

**Comment by ArjanLoeffen** [comment]
Gedaan.
