### ISSUE TITLE
Serialisatie van keuze tussen twee ongetypeerde CharacterStrings vermijden

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#287]
MIM serialisatie: 

In UML kun je opgeven:

![image](https://user-images.githubusercontent.com/12828217/194278044-e75e0aff-c216-42be-95e9-158edfa95cba.png)

In XML schema ziet dit er uit als:

![image](https://user-images.githubusercontent.com/12828217/194277964-6b880af0-1ce1-4cd6-a1b6-fb56e457908d.png)

In de MIM serialisatie komt dit er nu uit als:

```xml
            <mim:Keuze id="bakstenen-keuze-betalingskenmerkofomschrijving-d17466e1215">
               <mim:naam>BetalingskenmerkOfOmschrijving</mim:naam>
               ...
               <mim:datatypen>
                  <mim-ref:InterfaceRef xlink:href="#interface-characterstring-d17466e2755">CharacterString</mim-ref:InterfaceRef>
                  <mim-ref:InterfaceRef xlink:href="#interface-characterstring-d17466e2755">CharacterString</mim-ref:InterfaceRef>
               </mim:datatypen>
            </mim:Keuze>
```

Die serialisatie is niet correct. Een keuze tussen twee ongetypeerde Characterstrings is niet logisch.

**Comment by ThiesMesdag** [comment]
Volgens mij is dit een voorbeeld waarbij het wel nodig is om ook het pad / de keuze naam op te nemen in de xsd. 
```
laatsteOverboeking 
           choice 
                Betalingskenmerk type string 
                omschrijving type string
```

**Comment by ArjanLoeffen** [comment]
Ik zie de relevantie en moet even denken over de oplossing.

**Comment by ArjanLoeffen** [comment]
Ik denk dat we de volgende oplossing moeten introduceren.
Iedere keuze heeft verplicht een label. Dat is de naam van de keuze. 

In ons voorbeeld: betalingskenmerk, en omschrijving. 
![image](https://user-images.githubusercontent.com/12828217/204531485-508df67a-bea8-407b-af4d-c210e078736d.png)
Dat label komt terug in de serialisatie als:
```xml
  <mim:keuzeDatatypen>
        <mim:Datatype label="betalingskenmerk">CharacterString</mim:Datatype>
        <mim:Datatype label="omschrijving">CharacterString</mim:Datatype>
     </mim:keuzeDatatypen>
```

Het is "slechts een label", maar het kan helpen om deze keuze te disambuigueren.

Dit geldt ook voor de volgende gevallen:

Keuze tussen relatiedoelen:
![image](https://user-images.githubusercontent.com/12828217/204531636-f13c8ca1-9385-42ac-8179-fe33c4609828.png)
Keert terug als:
```xml
    <mim:keuzeRelatiedoelen>
        <mim:Relatiedoel>
           <mim-ref:ObjecttypeRef label="klant" xlink:href="#klanten-objecttype-klant">Klant</mim-ref:ObjecttypeRef>
        </mim:Relatiedoel>
        <mim:Relatiedoel>
           <mim-ref:ObjecttypeRef label="contract" xlink:href="#klanten-objecttype-contract">Contract</mim-ref:ObjecttypeRef>
        </mim:Relatiedoel>
     </mim:keuzeRelatiedoelen>
````

Keuze tussen attributen: hier speelt dit niet. De attributen worden expliciet opgenomen, er zijn geen "labels".

Ik heb de code in branch hierop aangepast.
