### ISSUE TITLE
Verplichting van een query parameter komt niet correct in de OAS3

### ISSUE THREAD

**Issue by JosVanderArend** [Imvertor/Imvertor-Maven#292]
Ik geef in het BSM bij een query parameter middels de tagged value Multiplicity met de waarde 1 aan dat deze query parameter verplicht is. Echter in de OAS3 schemadefinities (YAML) heeft de property required dan toch de waarde false.
Dit komt vooral voor bij de methoden POST en PATCH.

Ik moet dan altijd de waarde van de property required bij deze query parameters handmatig aanpassen in de OAS3 schemadefinities (YAML).

**Comment by melsk-r** [comment]
Er werd daar niet gecheckt op het required zijn van een parameter. Parameter werd standaard op required = false gezet. Is gecorrigeerd.

**Comment by JosVanderArend** [comment]
Correctie waargenomen: required op true gezet in YAML
