### ISSUE TITLE
Voorbeeldwaarde van twee nullen bij query parameter komt niet goed in de OAS3/YAML

### ISSUE THREAD

**Issue by JosVanderArend** [Imvertor/Imvertor-Maven#293]
Ik heb in het BSM een query parameter als string gedefinieerd met patroon van 2 cijfers. Alleen als ik dan als geldige voorbeeldwaarde "00" (twee nullen) specificeer bj tagged value Example in het BSM dan volgt toch altijd de waarde "0" (een nul) in de OAS3 schemadefinities (YAML).

Wellicht hieraan gerelateerd is dat de definitie van een formeel patroon bij een query parameter in het BSM ook altijd ontbreekt in de YAML.

**Comment by melsk-r** [comment]
Het probleem met de voorbeeldwaarde "00" (twee nullen) heb ik niet kunnen reproduceren. Graag nogmaals checken of dit nog steeds speelt.
Het niet meenemen van de definitie van een formeel patroon bij een query parameter is wel opgelost. Zowel in de nieuwe als in de oude methode.

**Comment by JosVanderArend** [comment]
Dit probleem bij diverse BSM modellen niet meer waargenomen. 
Issue zal worden gesloten.
