### ISSUE TITLE
Overnemen van integrale URI van TV locatie in uitlezen van waardenlijst

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#296]
Verzoek:
Is het mogelijk om, in geval van een ST Referentielijst, de Locatie 1-1 over te nemen van de TV Locatie?

Oftewel, bijvoorbeeld de waarde “https://raw.githubusercontent.com/BROprogramma/EPL/gh-pages/lists/GeologischeEenheid.xml” 1-1 over te nemen?

Achtergrond:

De locatie van een waardenlijst wordt bepaald op basis van een "template" voor de locatie van de gegevens. Bijv

`https://raw.githubusercontent.com/BROprogramma/[appinfo/model-abbreviation]/gh-pages/lists/[temp/latest-list-key].xml`

Die latest-list-key wordt bepaald op basis van de locatie tagged value, namelijk de laatste "name" (losstaand of achter laatste /) van de locatie.

Gebruiker moet dus opvoeren:
`https://raw.githubusercontent.com/BROprogramma/EPL/gh-pages/lists/GeologischeEenheid`
of 
`GeologischeEenheid`
of wat dan ook als het maar eindigt op die naam.

**Comment by ThijsKnapen** [comment]
Fijn dat mijn verzoek bij deze in beschouwing is genomen.

**Comment by ArjanLoeffen** [comment]
Ten aanzien van de (nieuwe) werking van parameter includedoclist:

https://imvertor.armatiek.nl/imvertor-executor/dashboard/wiki?key=cli-includedoclist

**Comment by ThijsKnapen** [comment]
Check. Als ik naar de properties xlsx file kijk van de BRO (https://github.com/Imvertor/Imvertor-Maven/blob/master/src/main/resources/input/BRO/props/BRO.xlsx), in de meeste gevallen default op yes staat, dat is fijn.

Ik kan de volgende slotopmerkingen van https://imvertor.armatiek.nl/imvertor-executor/dashboard/wiki?key=cli-includedoclist alleen niet zo goed plaatsen;
_Het is in het algemeen beter te verwijzen naar de waardenlijsten op basis van hun naam. Dit, omdat internet locaties veranderen en dit technische locaties zijn, terwijl de bedoeling is in de tagged value slechts een “hint” te geven van waar betreffende informatie te vinden is. Het model zou waar mogelijk techniek-vrij moeten blijven. Het verplaatsen van de internet locatie (server) heeft in dat laatste geval dan ook geen effect op de inhoud van de modellen._

Ik ben het eens dat het een aandachtspunt is dat met het verwijzen naar een URL, er een risico ontstaat dat de locatie op een gegeven moment verandert. Maar dat risico geldt m.i. ook als je er indirect naar verwijst (als je de URL vanuit de software opbouwt). Bij een veranderde URL, zou je ook dan parameter waarden moeten aanpassen om weer tot een correct afgeleide URL te komen.

**Comment by ArjanLoeffen** [comment]
De aanname is dat de Naam die je opgeeft (dat kan ook iets anders zijn, bijv. een URI) de basis vormt voor het samenstellen van een technische locatie. Dat is een proces dat per omgeving/software anders kan zijn ingericht. Op dit moment is het simpel ingericht, zoals beschreven. Als waardenlijst-namen gaan veranderen is een wat complexere aanpak wellicht van toepassing. Dat is nu nog niet nodig.

NB we hebben speciaal aandacht voor deze zaak omdat ook Kadaster heeft aangegegeven waardenlijsten te willen gaan uitlezen en opnemen in de documentatie.

**Comment by ThijsKnapen** [comment]
Hoi Arjan,

Ik zie dat je schrijft... "_De aanname is dat ..._".
Van waaruit of van wie/wat is die aanname gestoeld? Is dat iets dat MIM of NEN3610 voorschrijft?

**Comment by ArjanLoeffen** [comment]
Nee, dat is aangenomen bij het ontwerp van het mechanisme.

Ik stel voor dat we testen of de locatie waarde ene URL is (http of https adres). Zo ja, afhandelen als URL.
