### ISSUE TITLE
Compare op basis van JobId

### ISSUE THREAD

**Issue by ThiesMesdag** [Imvertor/Imvertor-Maven#3]
Zie ook Kadaster-Jira IM-476

Het is gewenst om een release vergelijking (compare) uit te voeren tussen de huidige en een eerdere job, op basis van job-ID.
 Implementeer hiervoor de volgende opties:

-compare job 
-comparewith [jobID] 

In de rapportage wordt dan dus een compare lijst getoond tussen deze twee varianten van deze release.

Technische realisatie:

naast

\Imvertor-output\Kadaster\applications\cdmkad\BORIS\20160901\etc 

opnemen:

\Imvertor-output\Kadaster\applications\cdmkad\BORIS\20160901\job 

met daarin voor iedere job die uitgevoerd is voor deze release een folder:

\Imvertor-output\Kadaster\applications\cdmkad\BORIS\20160901\job\2016-10-05-07-42-46-925\model.system.xml 

want dat is de basis voor alle compares.


**Comment by ArjanLoeffen** [comment]
@ThiesMesdag speelt dit nog? Is dit nog steeds een wens en wordt Compare wel gebruikt?

**Comment by kad-mesdat** [comment]
Wat we graag willen kunnen zien is of het huidige model dezelfde xsd oplevert voor alles wat niet is aangepast ten opzichte van de vorige versie van het model. DIe vorige versie is een x aantal jobs eerder gegenereerd, of lokaal beschikbaar. Misschien kan dit ook wel handiger door een oude xsd folder te kunnen opgeven o.i.d. en dan de verschillen terug te krijgen. Maar ik kan mij ook goed voorstellen dat dit een te complexe feature is voor in imvertor en een voor imvertor xsd's dif getuned tool ook prima kan.

**Comment by ArjanLoeffen** [comment]
@ThiesMesdag Spelen compares nog en heb je nog steeds behoefte aan de hier beschreven functionaliteit?
