### ISSUE TITLE
GML Profile wordt niet goed opgenomen in aanroepend schema

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#300]
Kadaster schema genereren met props:

> mapping             	= NEN36102022_GML322
> creategmlprofile        = yes

levert niet het juiste profiel op en een onterecht geplaatste referentie naar gml.xsd.

**Comment by ArjanLoeffen** [comment]
Het blijkt dat in de master 1.67 dit ook fout gaat:

```
mapping             	= NEN3610_GML322_ENV
creategmlprofile        = yes
```

levert fouten op omdat niet wordt verwezen naar het gegenereerde profiel 
`../../../gml/3.2/[modelnaam]-gml.xsd`
maar naar 
`../../../gml/3.2.2/gml.xsd`

Dit is dis een bug in de master. Gek dat dit niet eerder is opgemerkt. @ThiesMesdag  wordt deze optie `creategmlprofile = yes` wel gebruikt?

**Comment by ArjanLoeffen** [comment]
Ik heb de aanpassingen nu gepleegd. 

Let op: creategmlprofile werkt nog niet voor ISO19136. Als dat een probleem is, graag aangeven.

De varianten waarbij geen profiel wordt gegenereerd, of waarin het vastgestelde kadaster profiel wordt gebruikt werken wel.

**Comment by ThiesMesdag** [comment]
Het wordt wel gebruikt, maar met 
mapping             	= NEN3610_GML322PROFILE_ENV
creategmlprofile    	= yes

In onze handleiding heb ik het zo beschreven:
>4.2.1 GML
>De property mapping bepaalt samen met de property creategmlprofile wat voor GML er gegenereerd wordt. Als creategmlprofile = yes dan worden GML concepten beperkt tot wat het model nodig heeft. De property mapping bepaalt of heel GML als basis dient, of alleen de GML concepten die het Kadaster gebruikt. De mogelijkheden zijn NEN3610_GML322PROFILE_ENV voor het Kadasterprofiel of NEN3610_GML322_ENV voor het algemene GML profiel. Wanneer je het Kadasterprofiel of creategmlprofile = yes kiest wordt een enkel gml bestand gegenereerd waar alles inzit.

>4.2.2 IS019136
>Voor het genereren van xsd's voor GML bestanden wordt de schemavariant IS019136 gebruikt createxmlschemavariant = ISO19136. Deze generatievariant wordt onder andere gebruikt voor Kadastrale Kaart schema's.

**Comment by ArjanLoeffen** [comment]
Ik neem aan dat het genereren van een profiel niet nodig is als ISO19136 wordt gebruikt.
Wil je het issue sluiten?

**Comment by ThiesMesdag** [comment]
Al de behoefte voor een ISO19136 profiel ontstaat kan daar een nieuw issue voor worden aangemaakt.
