### ISSUE TITLE
Imvertor 2.0 probleem met gml datatypen

### ISSUE THREAD

**Issue by ThiesMesdag** [Imvertor/Imvertor-Maven#306]
Wanneer ik met 1.67.1 het zelfde model genereer (cdmkad) heb ik geen xsd validatie fouten (job 2023-01-04-12-40-45-020).  

Met 2.0 (job 2023-01-04-12-34-38-381) wel. 

![image](https://user-images.githubusercontent.com/11945098/210558751-202c4dcf-74ce-47e2-b4ce-75baebba70f6.png)

**Comment by ArjanLoeffen** [comment]
Alle typen waarvan is vastgesteld dat deze uit GML zijn overgenomen werden toegevoegd aan het profiel. Dat mechanisme moet ook worden ingezet voor typen uit GMLPROFILE.

Gefixed.

**Comment by ThiesMesdag** [comment]
Gefixed. Getest en output 2.0 is nu gelijk aan 1.67
