### ISSUE TITLE
Geonovum - toevoegen tv's en afstemmen docrules

### ISSUE THREAD

**Issue by Gtrouborst** [Imvertor/Imvertor-Maven#310]
## Samenvatting
Voor DiSGeo hebben we een extentie op de tagged value set van MIM. Deze willen we graag terugzien in de documentatie. Verder lijken er een aantal standaard MIM-tags niet mee in de documentatie. Ook die zien we graag wel daarin terug. 

### «Objecttype»

Aspect | Kardinaliteit | Toelichting | Type | In EA
-- | -- | -- | -- | -- 
*actualiteit* | 1..1 | Beschrijving van eisen aan de update frequentie. | String | Tagged value
*inwinning verplicht* | 1..1 | Geeft de mate van compleetheid van het objecttype aan. | Boolean | Tagged value

### «Atttribuutsoort»
Aspect | Kardinaliteit | Toelichting | Type | In EA
-- | -- | -- | -- | --
*inwinningsregels* | 0..1 | Hyperlink naar inwinregels voor het objecttype. Deze zijn te omvangrijk om in EA op te nemen. | String | Tagged value
*positionele juistheid* | 0..1 | De nauwkeurigheid van de geometrie. | Integer | Tagged value

## Verzoek
 1. Toevoegen van de bovenstaande tagged values aan `tvsets`
 1. Toevoegen van bovenstaande tagged values aan de `docrules`
 1. Afstemmen `docrules` _NEN3610:2022_ en _MIM1.1.1_

**Comment by ArjanLoeffen** [comment]
De vier tagged values zijn toegevoegd. Voor de liefhebber:
https://github.com/Imvertor/Imvertor-Maven/commit/dbc28750f96364a10a84fb08be9167f37febfce4

**Comment by Gtrouborst** [comment]
@ArjanLoeffen, dank voor het doorvoeren! Ik zie nog **twee dingen** die niet helemaal naar wens zijn

### 1 Documentatie
Ik heb vanuit EA opnieuw met de Nightly build het DiSGeo model gedraaid. Maar er is **in de documentatie nog geen verschil zichtbaar** dat wil zeggen, we missen nog:

- de **volledige lijst met MIM-tv’s** (in ieder geval bij «Objecttype» en «Attribuutsoort», want dat heb ik mij op gericht)
- de **aanvullende DiSGeo tags**

### 2 Kardinaliteit
In de tabel van «Objecttype» (zie: bovenstaand) heb ik de kardinaliteiten van de nieuwe tags aangepast t.o.v. van wat wij ervoor besproken hadden. Dat heb ik niet meer expliciet benoemd, maar die zou ik nog wel graag aangepast willen zien. Ze staan hier: 
 - [**line 36**](https://github.com/Imvertor/Imvertor-Maven/blob/Development/src/main/resources/input/Geonovum/cfg/tvsets/Geonovum.xml#L36)
 - [**line 45**](https://github.com/Imvertor/Imvertor-Maven/blob/Development/src/main/resources/input/Geonovum/cfg/tvsets/Geonovum.xml#L45)

**Comment by Gtrouborst** [comment]
Als voorbeeld kun je kijken naar het object [`BestuurlijkGebied`](https://geonovum.github.io/disgeo-im/#global_class_BestuurlijkGebied_BestuurlijkGebied) en de bijbehorende attributen

**Comment by ArjanLoeffen** [comment]
Ik zie die info wel. Dit even offline nalopen samen.

**Comment by ArjanLoeffen** [comment]
@Gtrouborst  Ik zie dat de CFG-DOC-ACTUALITEIT (etc) in de documentatieregels van NEN3610-2022 zijn opgenomen. Je hebt getest met MIMCM van Geonovum, dat is een ander metamodel, en heef geheel eigen documentatie regels. Ik neem nu aan dat op beide documentatievormen deze tagged values moeten worden opgenomen. Klopt dat?
