### ISSUE TITLE
Padparameter midden in het pad ontbreekt in de OAS3-definities

### ISSUE THREAD

**Issue by JosVanderArend** [Imvertor/Imvertor-Maven#313]
In de OAS3-defnities (openapi.yaml) bij padparameters midden in het pad zitten ontbreekt de definitie van parameter id. Zoals bijvoorbeeld bij “/examens/{id}/examenvarianten”. 

Zit de padparameter aan het einde (bijvoorbeeld “/examens/{id}”) dan gaat het wel goed en komt de definitie van parameter id wel in de OAS3.

**Comment by JosVanderArend** [comment]
Bij een ander model worden dergelijke padparameters wel gegenereerd, zoals bij het pad “/vestigingen/{vestigingsid}/leerlingen” of bij het pad “/groepen/{groepsid}/leerlingen”. 
Ik weet niet of dit ligt aan de langer/andere benaming van de padparameter (vestigingsid/groepsid in plaats van id).

**Comment by melsk-r** [comment]
Ik heb even m.b.v. het model BSM FDE wat onderzoek gedaan.

In het bericht '/groep/{groepsid}/leerlingen' komt '{groepsid} na genereren ook niet voor als pad parameter. Dit komt doordat je 'groep/{groepsid}' als waarde van 'custom_path_facet' hebt gedefinieerd. Daardoor wordt dat deel van de url niet tegen de request berichtstructuur gevalideerd waardoor 'groepsid' een query parameter wordt.

Het feit dat 'groep' met een '{groepsid}' voorkomt in de url impliceert n.m.m. echter dat een 'groep' een resource is, in het model het stereotype 'Entiteittype' moet krijgen,  de tagged value 'custom_path_facet' moet worden verwijderd en opgenomen moet worden in de query berichtstructuur zoals onderstaand:

![image](https://user-images.githubusercontent.com/20185784/216979343-1729fe8d-3d36-412b-abbb-b98613e5aef7.png)

Indien 'groep' in de url was voorgekomen in een url zonder het '{groepsid}' attribuutsoort en voor een resource, dus als /groep/leerlingen, dan had je 'custom_path_facet' kunnen gebruiken met de waarde 'groep'.

Uit het feit dat je opmerkt dat het bericht '/groepen/{groepsid}/leerlingen' wel goed worden gegenereerd maak ik op dat je in het model waar dat bericht voorkomt 'groepen' wel een 'Entiteittype' is, dat je deze hebt opgenomen in de query berichtstructuur en dat je daar geen 'custom_path_facet' hebt gedefinieerd. Voor het bericht '/vestigingen/{vestigingsid}/leerlingen' geldt hetzelfde denk ik.

Ik vermoed dat je er in het bericht '/examens/{id}/examenvarianten' voor hebt gekozen het Entiteittype 'examens' niet op te nemen in de query berichtstructuur en 'examens/{id}' als waarde van 'custom_path_facet' te specificeren. 'examens' zal denk ik wel een 'Entiteitype' zijn aangezien in het bericht '/examens/{id}' de parameter 'id' wel een pad parameter wordt.

**Comment by JosVanderArend** [comment]
Het gaat nu goed in de YAML van de beide inline padparameters /groepen/{groepsid}/leerlingen en '/vestigingen/{vestigingsid}/leerlingen in het FDE BSM.

In het model CEVO BSM wil de inline padparameter /examens/{id}/examenvarianten maar niet lukken. 
Tot nu toe ontbraken steeds alle parameters (pad parameter id en query parameters edu-to en edu-from) in de YAML bij /examens/{id}/examenvarianten. Ik heb die steeds er handmatig bijgeplaatst.
Ik heb nu in het model van de <<Bericht>>Variantencatalogus ook een <<Entiteittype>>Examen_parameters ertussen geplaatst. Maar nu krijg ik een foutmelding die ik maar niet weg krijg:
“Step-level system error - Please notify your system administrator: Transformation causes a fatal error: A sequence of more than one item is not allowed as the first argument of fn:lower-case() ("examens", "examens")”
Weet jij wat ik hier fout doe (?
[BSM-BSMCentraleexamensVO-01.02.03-1-20220921-20230220-093249.zip](https://github.com/Imvertor/Imvertor-Maven/files/10783143/BSM-BSMCentraleexamensVO-01.02.03-1-20220921-20230220-093249.zip)

**Comment by melsk-r** [comment]
De oorzaak van de foutmelding is de naam van het entiteittype dat je erbij hebt geplaatst: 'Examen_parameters'. In &lt;&lt;Bericht>>Toetscatalogus bestaat immers ook al een entiteittype 'examen_parameters'. De namen van deze classes zijn dus niet case sensitive. Hernoemen van 'Examen_parameters' in 'examen_parameter' lost de foutmelding al op.

Daarnaast moet je op de Padtype class '/examens/{id}/examenvarianten' geen 'custom_path_facet' tagged value definiëren. Er bestaat immers een class met de tagged value 'Naam in meervoud' met de waarde 'examens' in de request tree.

Volgens mij wordt er dan een correcte yaml gegenereerd.

Als dit alles klopt dan concludeer ik dat de nieuwe manier van genereren geen problemen meer voor jullie oplevert. De problemen die er waren heb ik volgens mij allemaal opgelost. Kun je dat bevestigen?

**Comment by JosVanderArend** [comment]
Ik heb het opgelost en het werkt nu prima. De YAML is nu correct.

Ik heb het trouwens toch net iets anders gedaan omdat die andere 'examen_parameters' anders is bedoeld. Ik heb deze 'Examen_parameters' hernoemd naar het unieke 'examenvoorexamenvarianten_parameters'.
