### ISSUE TITLE
Imvertor versies en gekoppelde conceptual schema's

### ISSUE THREAD

**Issue by PalmJanssen** [Imvertor/Imvertor-Maven#316]
De imvertor versies (1.65, 1.67, 2.0 enz) zijn gekoppeld aan verschillende configuraties van conceptual schema's en mappings. Dat kan ik zelf niet instellen.

Ik kan nu bij een NEN 3610:2011 model alleen versie 1.5 gebruiken zonder een foutmelding op FucntioneelGebied te krijgen. Dat komt omdat in de andere versies FunctioneelGebied zowel in NEN 3610 als in IMGeo zit. Dat laatste is sowieso raar en neem ik aan niet juist, maar ik wil eigenlijk zelf kunnen aangeven of ik de IMGeo mapping nodig heb. Nu moet ik een beetje op de gok de geschikte Imvertor versie kiezen.

**Comment by ArjanLoeffen** [comment]
Imvertor is software + configuratie. Registratief gebied is onderdeel van de configuratie. Als je een oud NEN3610 model wilt gebruiken kies je voor het NEN3610 metamodel (ipv NEN3610:2022 metamodel). Via conceptual schema mappings (property `mapping`) kun je voor een van beide varianten kiezen. Misschien heb je verkeerde keuze gemaakt. De mappings die nu voor geonovum ter beschikking staan zijn:

![image](https://user-images.githubusercontent.com/12828217/217274207-223d86b8-e6d9-4bb4-972d-0a695e0d3101.png)

Als andere combinaties gewenst zijn kunnen we dat instellen.

**Comment by wilkoquak** [comment]
Allen, ik zit een beetje hardop te denken en ik merk dat ik het lastig vind dat de mapping zich in de configuratie bevindt. Zou het te bouwen zijn om de info die zich nu in een mapping bevindt te stoppen in een EA-package als tagged values? Het gebruiken van de juiste mapping gebeurt dan door de juiste EA packages in je model te stoppen...

**Comment by ArjanLoeffen** [comment]
Het is me niet duidelijk hoe dat zou moeten. Belangrijk is dat de betreffende informatie (modellen, maar ook realisatie in XML schema, OAS, Json etc.) niet (van nature) in EA thuishoort, en het complex wordt deze (mogelijk geforceerd) daarin op te nemen. 
Ik denk zelf dat het hoe dan ook nodig is om ergens, buiten EA, deze info vast te leggen in een leesbaar formaat. Dat dat onderdeel is van het Imvertor-OS github project, een ander project, of zelfs los binnen de gebruikersomgeving, dat is een andere discussie.
Maar ik sta open voor aanpassingen van de huidige opzet.

**Comment by PalmJanssen** [comment]
Is door Arjan opgelost met 'short cut' door de in geval van dubbele mapping 'de eerste te kiezen'. Dit wordt in het properties bestand geconfigureerd. En werkt op de Nightly build.

Dit wordt ingesteld met:

-	Gebruik Nightly build
-	Voeg dit toe aan properties file: **usefirstmap = yes**
