### ISSUE TITLE
IMvertor SKOS generatie mist definities

### ISSUE THREAD

**Issue by PalmJanssen** [Imvertor/Imvertor-Maven#317]
Bij het genereren van een SKOS begrippenkader uit UML komen de definities uit de notes velden niet in het skos bestand.

Voorbeeld:

# Construct: BKLActiviteiten::Mestvergisting (OBJECTTYPE)
<imev-werkomgeving/Mestvergisting>
   a skos:Concept ;
   skos:prefLabel "Mestvergisting"@nl ;
   rdfs:label "Mestvergisting" ;
   dct:created "2020-08-12"^^xsd:date ;
   dct:modified "2021-04-30"^^xsd:date ;
   skos:inScheme begrippenkader:imev-werkomgeving ;
   skosthes:broaderGeneric <imev-werkomgeving/BKLActiviteit> ;

Wel een fijne functionaliteit trouwens

**Comment by ArjanLoeffen** [comment]
Als Geonovum ook SKOS concepts wil genereren met gedefinieerde tagged values moet Geonovum SKOS rules configureren. Deze zijn nu alleen nog [vastgesteld voor BRO](https://github.com/Imvertor/Imvertor-Maven/blob/master/src/main/resources/input/BRO/cfg/skosrules/BRO.xml). IHW volgt BRO. Dat kan ook zo worden ingesteld voor Geonovum.

**Comment by ArjanLoeffen** [comment]
Opgenomen in de nightly build.

Geef mee in je properties file:
```
createskos              = yes
skosrules               = Geonovum
```

Als dit standaard moet worden, dan veranderen we dat ook op de server.

**Comment by PalmJanssen** [comment]
Fantastic!
