### ISSUE TITLE
Kadaster-respec: gestructureerd datatype met nillable data element

### ISSUE THREAD

**Issue by kad-mesdat** [Imvertor/Imvertor-Maven#318]
Het Kadaster gebruikt binnen een aantal gestructureerde datatypen een data element met mogelijk geen waarde. Dit is in de respec niet terug te vinden en zorgt daarmee voor verwarring omdat het niet terug te vinden is.
Graag de respec beschrijving van het data element uitbreiden met mogelijk geen waarde. 

voorbeeld:
https://imvertor.armatiek.nl/download/dat/2023-01-18-15-32-31-045/work/app/doc/index.html 
<html>
<body>

OnroerendeZaak::TypeKoopsom.bedrag (attrib) | Mogelijk geen waarde | Ja
-- | -- | --

</body>
</html>

![image](https://user-images.githubusercontent.com/67012704/218791072-4ba7694e-1252-42c9-879b-d6599f76b882.png)

in de respec

![image](https://user-images.githubusercontent.com/67012704/218791244-cdc71db4-02c2-4a9f-ba8f-a70e1d3c1c6c.png)

**Comment by ArjanLoeffen** [comment]
Ik zie dat in de oude CDMKAD configuratie de tagged value "Mogelijk geen waarde" ook werd gedefinieerd op Data element. Dat is niet het geval in de Kadaster MIM configuraties. Voorstel is dat te corrigeren voor de Kadaster MIM 1.1.1 config.

Ik snap trouwens niet wat die tagged value daar doet; kun je een voorbeeld geven waarin die tv nodig is?

**Comment by ArjanLoeffen** [comment]
Met deze aanpassing wordt de opbouw als volgt (let niet op de layout):

![image](https://user-images.githubusercontent.com/12828217/218989337-fe1fd809-df46-4d4d-b489-ea0a5c369f72.png)

De tagged value wordt dus niet getoond als die geen waarde heeft.

**Comment by kad-mesdat** [comment]
Lijkt mij goed zo. Een voorbeeld zit in het issue. 

Bij het typekoopsom is het bedrag verplicht, maar helaas bleek het bij de conversie uit AKR toch een paar keer te ontbreken, dus hebben we het optioneel gemaakt. Eerder hadden we het ook toegepast bij onvolledige datum, maar dat hebben we omgezet naar een keuze. Dat lijkt in dit geval wat omslachtig en niet helemaal passend.

**Comment by ArjanLoeffen** [comment]
Okay, ik voer de oplossing door in de development branch / Nightly build, 16-2 beschikbaar.
