### ISSUE TITLE
Opgeven van volgorde van objecttypen in catalogus

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#32]
Invoeren in EA / Gegenereerde catalogus.
De volgorde van entiteiten (objecttypen) in de catalogus is alfabetisch. We willen de volgorde echter zelf kunnen opgeven.
Aangebracht door BRO.

**Comment by ThiesMesdag** [comment]
Dit wil het Kadaster ook graag. De huidige sortering is op alphabet.
Ik zie twee mogelijkheden, 
1 (default?) de volgorde van de packages in de projectbrowser volgen óf 
2 via een tagged value op het package, net zo als de positie-tv voor attributen.

**Comment by ArjanLoeffen** [comment]
vanaf nu lezen we de locaties uit de projectbrowser uit.
