### ISSUE TITLE
MIM serialisatie: betere representatie van externe constructies (extern / interface)

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#320]
Er moet een betere / completere representatie komen van MIM externe constructies zoals GML datatypen. Nu is alleen de naam beschikbaar (als waarde van `<mim:ExternDatatype>`) maar dat moet strakker. Er kunnen meerdere datatypen met dezelfde naam voorkomen en informatie over de naam van het externe domein is ook relevant.

**Comment by ArjanLoeffen** [comment]
Ik ga uit van de volgende UML:

![image](https://user-images.githubusercontent.com/12828217/221174635-2d27c7fa-9628-4d0f-a6b6-74a96a1260f0.png)

Objecttype Class1 
-	Heeft attribuut externGML
-	Van type GM_Point
-	Dat is gedefinieerd in extern package GMLPROFILE

Bijgevoegde XSD (zie [mim.zip](https://github.com/Imvertor/Imvertor-Maven/files/10823867/mim.zip)) beschrijft de MIM serialisatie hiervan. 
Hieronder een ingekort fragment:

```
<mim:Objecttype id="model-objecttype-class1">
  <mim:naam>Class1</mim:naam>
    <mim:attribuutsoorten>
      <mim:Attribuutsoort>
        <mim:naam>externGML</mim:naam>
        <mim:type>
          <mim-ref:ExternDatatypeRef 
            xlink:href="#gmlprofile-constructie-gm_point"
            >GM_Point</mim-ref:ExternDatatypeRef>
        </mim:type>
…
<mim:Extern id="OUTSIDE-2">
  <mim:naam>GMLPROFILE</mim:naam>
  <mim:constructies>
    <mim-ext:Constructie id="gmlprofile-constructie-gm_point">
      <mim-ext:constructietype>FEATURETYPE</mim-ext:constructietype>
      <mim-ext:kenmerken>
        <mim-ext:kenmerk naam="naam">GM_Point</mim-ext:kenmerk>
      </mim-ext:kenmerken>
    </mim-ext:Constructie>
  </mim:constructies>
</mim:Extern>
```

De aanpassingen die we moeten doorvoeren op het MIM serialisatie schema zijn:
-	`<constructies>` toestaan binnen Extern (ik vat is op als een omissie in het huidige schema)
-	Introductie van `<mim-ref:ExternDatatypeRef>` in MIMFORMAT_MimRef_v2.xsd
-	Introductie van `<mim-ref:ExternDatatypeRef>` in MIMFORMAT_Mim_v2.xsd als mogelijk attribuutsoort type.

Dit handelt alleen nog de datatypen van attribuutsoorten af. Een soortelijke actie moet ook uitgevoerd worden voor relatiesoorten, data elementen etc. Echter: dat is overal exact hetzelfde mechanisme.

**Comment by lennartvanbergen** [comment]
Het gaat erom dat het een datatype is, waarbij de definitie extern is. Dat is de basis. 

Het 2e deel in je voorbeeld ziet er goed uit. Declaratief. 

Eerste deel van de uitwerking brengt me wat in verwarring. 

Ik zou daar iets verwachten zoals: 

Objecttype Perceel 
           Attribuutsoort perceelbegrenzing
                        ExternDatatype = GM_Point 

(in de gewone modellering manier) 

GM_Point staat dan gedeclareerd in een externe package,

Eventueel staat de package naam genoemd bij ExternDatatype, bv. 

                        ExternDatatype 
                                 naam = GM_Point 
                                 extern packacge naam = GMLPROFILE

**Comment by ArjanLoeffen** [comment]
Het enige verschil is dus dat je de referentie niet op basis van `xlink:href` wilt vormgeven. Dat  is dan wel een beetje raar, omdat  we op andere plekken in de MIM serialisatie ook verwijzen naar een elders gedefinieerde constructie, en dat doen we met xlink. 

We maken het met deze methode dus ook mogelijk om meerdere constructies te gebruiken met dezelfde naam. Dat is wellicht in de praktijk een eis.

**Comment by pmaria** [comment]
Ziet er op zich bruikbaar uit.

Een aantal vragen:

* zou `mim:constructies` niet ook in de `mim-ext` namespace gedefinieerd moeten zijn? Constructies zijn volgens mij niet iets wat in MIM gedefinieerd is. Dus lijkt het me netter om deze binding dan ook niet in de `mim` namespace te definieren.
* waarom weten we wel dat `mim-ref:ExternDatatypeRef` een extern datatype is? Gaan we straks ook `mim-ref:ExternObjecttypeRef` etc. krijgen? Ik had hier dan eerder iets als `mim-ext:constructieRef` verwacht.

**Comment by ArjanLoeffen** [comment]
- Ja, ik denk dat `mim-ext:constructies` logischer is. Ik volgde het schema zoals het nu is. Nb. `mim-ext:kenmerk` moet ook met een hoofdletter.
- Ja, misschien moeten we de "last" van het bepalen wat voor een constructie het is ook beleggen bij de verwerker van de externe modellen. Dus denk ik dat min-ext:ConstructieRef beter is.

**Comment by lennartvanbergen** [comment]
Mee eens.

**Comment by ArjanLoeffen** [comment]
Implementatie opgeleverd, graag testen. Ik zet die milestone.
