### ISSUE TITLE
Bij een property van het type 'array' wordt geen 'minItems' gegenereerd

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#323]
Een property waarvan in een BSM model is gedefinieerd dat het meerdere keren voor mag komen wordt in de YAML file wel netjes een array gemaakt maar als het in het BSM model als optioneel is gedefinieerd wordt er geen 'minItems' bij gedefinieerd.

Er wordt dus nu het volgende gedfinieerd:

```
        propertynaam:
          type: "array"
          items:
            $ref: "#/components/schemas/componentnaam"
```
terwijl het volgende wordt verwacht:

```
        propertynaam:
          type: "array"
          minItems: 0
          items:
            $ref: "#/components/schemas/componentnaam"
```

Voor 'maxItems' geldt hetzelfde.

**Comment by JohanBoer** [comment]
Lijkt mij een goed voorstel.
