### ISSUE TITLE
Respec template van Logius vereist figcaption in catalogus.

### ISSUE THREAD

**Issue by wilkoquak** [Imvertor/Imvertor-Maven#326]
Momenteel ben ik bezig met een catalogus te maken met Imvertor in de nieuwe Respec omgeving van Logius. (https://github.com/Logius-standaarden/ReSpec-template). Hiermee heb ik een dataspec gemaakt en als ik dan naar de list of figures kijk zie ik geen captions voor de figures die door Imvertor worden gemaakt (Zie: https://geonovum.github.io/dso-cim-template/#tof ). Zou bij het genereren van de catalogus een \<figcaption\> kunnen worden toegevoegd?

**Comment by ArjanLoeffen** [comment]
Wat je vraagt is feitelijk, als ik het goed begrijp, dat we een `<figure>` introduceren waar nu `<img>` is opgenomen:

https://www.w3schools.com/tags/tag_figcaption.asp

Dus waar het nu de vorm heeft:

```
<div class="imageinfo overview">
  <img src="" usemap="" alt="Diagram Overzicht van alle constructies in dit model voor bakstenen en hun producenten. " />
  <map name="">
     <area>...
     ....
```
wordt dit:
```
<div class="imageinfo overview">
  <figure>
    <img src="" usemap="" alt="Diagram Overzicht van alle constructies in dit model voor bakstenen en hun producenten. " />
    <figcaption>Diagram Overzicht van alle constructies in dit model voor bakstenen en hun producenten. </figcaption>
 </figure
<map name="">
     <area>...
     ....
```
Ik weet  niet hoe dit uitwerkt in het _figures_-overzicht van Respec, wanneer de complete caption daar wordt opgenomen.

Die caption wordt nu binnen EA geplaatst in de omschrijving (notes) van een diagram:

![image](https://user-images.githubusercontent.com/12828217/226318659-f0bcef82-ad8c-4d3d-af62-b313644410ee.png)

Graag je reactie.

**Comment by wilkoquak** [comment]
Ik zie het probleem. Helaas is de name die je aan het diagram geeft al in gebruik voor de titel van de paragraaf waarin het plaatje komt. Zou je die niet kunnen her-gebruiken? En dan zonder de '-overzicht' postfix. Het is een beetje dubbelop, maar het zou voor de list-of-figures wel het gewenste resultaat opleveren.

**Comment by Gtrouborst** [comment]
Langere bijschriften zijn op zich geen probleem: https://geonovum.github.io/MIM-Werkomgeving/#tof. De naam van het diagram zonder suffix `- overzicht` of `- detail` klinkt prima.

**Comment by ArjanLoeffen** [comment]
In de owner parameters is de parameter diagram-encoding opgenomen; deze is niet verplicht.
Wanneer 'figure', dan wordt een `<figure>` element met caption ingevoegd.
De naam van de figure is de title zonder "- overzicht".

**Comment by ArjanLoeffen** [comment]
Beschikbaar op 15 aug.

**Comment by Gtrouborst** [comment]
Als ik dit test bij bestuurlijke gebieden gaat het nog niet helemaal goed, maar misschien komt het doordat ik de parameter nog niet correct heb opgenomen.

Geef ik de owner parameters aan in de **properties file**? Op deze manier: `diagram-encodig = figure`?

**Comment by ArjanLoeffen** [comment]
Nee dat is onderdeel van de owner. Dus geldt voor heel Geonovum. Ik kan die
instellen zoals jullie willen.

--
Arjan vanaf mobiel

Op di 15 aug. 2023 17:27 schreef Gtrouborst ***@***.***>:

**Comment by Gtrouborst** [comment]
@wilkoquak en ik hebben hier vandaag nog even naar gekeken. Nu wordt `<figcaption>` samengesteld uit `Diagram Name` én `Diagram Notes`. Maar dat is teveel van het goede. De `Diagram Notes` gebruiken we graag voor een geschreven toelichting op een diagram. De teksten die we daar opnemen kunnen langer zijn dan prettig is als bijschrift voor een figuur. We zien die teksten wél graag terug in de documentatie, maar liever niet in de `<figcaption>`.

## Voorstel
Graag zien wij het als volgt:

- [x] Alleen `Diagram Name` in `<figcaption>`, zonder `- detail` of `- overzicht`
- [ ] De tekst in `<figcaption>` **niet vetgedrukt** maken (anders wijkt het af van de rest van het document) 
- [ ] De tekst uit de _Diagram Notes_ als losse tekst onder de figuur, dus na de _closing tag_ `</figure>`) en met behoud van opmaak zoals die in EA is meegegeven.

**Comment by ArjanLoeffen** [comment]
Uitgevoerd.

**Comment by ArjanLoeffen** [comment]
17 aug beschikbaar.

**Comment by Gtrouborst** [comment]
Fijn, dankjewel Arjan!

**Comment by PalmJanssen** [comment]
Voor de volledigheid. Als de naam eindigt op `- detail` wordt het diagram wel geplaatst maar wordt de tekst van het notes veld niet geprint. Dit was natuurlijk 'vroeger' wel zo, ook met de nightlyBuild.

**Comment by ArjanLoeffen** [comment]
Hersteld. Graag testen! De aanpassing geldt voor respec waarin `figure` elementen worden ingevoegd. Dat is op dit moment alleen het geval voor Geonovum, namelijk dmv de parameter:

` <parameter name="diagram-encoding">figure</parameter>`

onderdeel van `/input/Geonovum/cfg/owners/Geonovum.xml`

**Comment by ArjanLoeffen** [comment]
Beschikbaar in Nightly-build.10

**Comment by wilkoquak** [comment]
Dank! Ik zie dat (-overzicht) nog wel in de caption terechtkoment en (- overzicht) niet (een spatie verschil). Dat is nog niet helemaal logisch, zie in het screenshot hieronder het verschil tussen de table-of-contents en de list-of-figure maar dit issue ga ik sluiten.

![afbeelding](https://github.com/Imvertor/Imvertor-Maven/assets/2814052/ee19e5f0-124f-4719-bf98-abbd23a6a439)

**Comment by wilkoquak** [comment]
sorry vergeten te sluiten
