### ISSUE TITLE
BRO: wijziging default waarden tags 'Indicatie classificerend' en 'Datum opname'

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#330]
Wijzigingen aan te brengen op het MIM BRO Grouping NL profiel:

1. De default waarde van de tag ‘Indicatie classificerend’ (komt 1x voor) dient te worden: “Nee”.
2. De default waarde van de tag ‘Datum opname’ (kom 23x voor) dient te worden: “n.v.t.”.

Met verzoek de versie van het profiel en de toolbox te wijzigen van 0.9.4-2.0.0 naar 0.10.4-2.0.0.

**Comment by ArjanLoeffen** [comment]
Is het okay als ik deze aanpassing op de Development uitvoer? Je moet dan kiezen voor de Nightly build. 
Zeer binnenkort wordt dit deze release "vrijgegeven".

**Comment by jacobvosimpronotion** [comment]
Dat is prima.

**Comment by ArjanLoeffen** [comment]
De spec
> De default waarde van de tag ‘Indicatie classificerend’ (komt 1x voor) dient te worden: “Nee”.

betreft de MIM11 configuratie; die had nog geen default; we nemen deze default daarin op. De waarden worden beperkt tot Ja en Nee.
  
De spec
> De default waarde van de tag ‘Datum opname’ (kom 23x voor) dient te worden: “n.v.t.”.

kan nu nog niet worden gerealiseerd. Er is (nog) geen voorziening om een "voorgeprinte" waarde voor profielen in de Imvertor configuratie op te nemen. Dit moet ik even uitzoeken.

NB in de tagged value staat dan dus "voorgeprint" n.v.t. en de analist kan deze waarde overschrijven met iets anders. Het is dus niet een "pulldown" keuze.

**Comment by ArjanLoeffen** [comment]
@PalmJanssen geeft aan dat een default waarde ('voorgeprint') mogelijk is. Hij heeft een voorbeeld gestuurd:

```
<TaggedValues>
 <Tag name="Metadata type" type="CharacterString" description="" unit="" values="" default="GeorkestreerdGegeven"/>
</TaggedValues>
```
Ik voeg het toe aan de configuratie. En daarna aan het profiel.

**Comment by ArjanLoeffen** [comment]
Wanneer een keuze tussen waarden bedoeld is wordt dat gespecificeerd als:

```
            <declared-values lang="nl">
                <value default="yes">Conceptueel</value>
                <value>Logisch</value>
            </declared-values>  
```
Dat betekent dat een default waarde (waarbij de waarde kan worden overschreven) eenvoudig kan worden opgegeven als:

```
            <declared-values lang="nl">
                <value default="yes">Conceptueel</value>
            </declared-values>  
```
NB we nemen aan dat een "fixed value" (een vaste waarde voor een tagged value) nooit voorkomt; het betreft dus altijd een keuze uit waarden, of een ingevoerde waarde, beide met mogelijk een default.

**Comment by ArjanLoeffen** [comment]
Opgenomen in Development / Nighly build; op[ 4-4 beschikbaar.

**Comment by jacobvosimpronotion** [comment]
Ik plan het testen in op 4-4.

**Comment by jacobvosimpronotion** [comment]
Oplossing is OK. Wordt hiermee het issue gesloten, of pas als deze in een reguliere versie is opgenomen?
