### ISSUE TITLE
BRO: Stereotype 'Relatierol' in MIM BRO Grouping NL ook 'Property' als 'Apply type'

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#332]
I.v.m. problemen in EA onder versie 16 met het selecteren van het stereotype 'Relatierol' bij de Target van een relatie, is de volgende wijziging gewenst in het MIM BRO Grouping NL profiel:

Binnen `<Stereotype name="Relatierol">` dient onder `<Apply type="AssociationEnd"/>` toegevoegd te worden:
```
<Apply type="Property"/>
<Property name="isReference" value="false"/>
```

Met deze wijziging s.v.p. de versie van MIM BRO Grouping NL ophogen van 0.9.4 naar 0.9.5.

Kan deze wijziging beschikbaar worden gesteld zowel in 2.0 als in de nightly-build?

Dit na afstemming met Paul Jansen van Geonovum over de manier waarop zij deze bug in EA 15 oplossen in het MIM 1.1.1 profiel.

**Comment by ArjanLoeffen** [comment]
Dit wordt dan dus bijvoorbeeld:

```
               <Stereotype name="Relatierol"
                           notes="MIM11: De benaming ..."
                           ...>
                  <AppliesTo>
                     <Apply type="AssociationEnd"/>
                     <Apply type="Property"/>
                     <Property name="isReference" value="false"/>
                  </AppliesTo>
                  <TaggedValues>
                         ........
```

**Comment by jacobvosimpronotion** [comment]
Klopt.

(Terzijde: voor het 'NEN3610 BRO Grouping EN' profiel hebben we vanmorgen getest of het daar ook werkt, wat het geval blijkt te zijn, dus daar registreer ik zo ook nog een soortgelijk issue voor.)

**Comment by ArjanLoeffen** [comment]
NB Dit bij voorkeur niet voor 2.0, alleen nighly. Is dat een probleem? We doen namelijk niet aan fixes op oude releases.

**Comment by jacobvosimpronotion** [comment]
Of niet voor 2.0 een probleem is, vind ik lastig om te doorzien. Stel dat een conceptueel model wordt gemaakt (conform die nightly-build) met tags op het stereotype 'Relatierol', en dat model wordt aangeboden aan Imvertor 2.0: geeft dat problemen?

**Comment by ArjanLoeffen** [comment]
Nee, omdat het profiel alleen een hulpmiddel is voor bewerking in EA. Imvertor krijgt die info niet binnen en doet er (dus) ook niks mee.
