### ISSUE TITLE
BRO: Stereotype 'AssociationRole' in NEN3610 BRO Grouping EN ook 'Property' als 'Apply type'

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#338]
I.v.m. problemen in EA onder versie 16 met het selecteren van het stereotype 'AssocationRole' bij de Target van een relatie, is de volgende wijziging gewenst in het NEN3610 BRO Grouping EN profiel:

Binnen <Stereotype name="AssociationRole"> dient onder <Apply type="AssociationEnd"/> toegevoegd te worden:

```
<Apply type="Property"/>
<Property name="isReference" value="false"/>
```

Met deze wijziging s.v.p. de versie van NEN3610 BRO Grouping EN ophogen van 0.9.3 naar 0.9.5 (0.9.4 slaan we over).

Kan deze wijziging beschikbaar worden gesteld zowel in 2.0 als in de nightly-build?

Dit na afstemming met Paul Jansen van Geonovum over de manier waarop zij deze bug in EA 15 oplossen in het MIM 1.1.1 profiel.

**Comment by ArjanLoeffen** [comment]
Ik neem aan dat dit ook geldt voor de logische modellen?
> NEN3610 BRO Grouping NL
> NEN3610 BRO Grouping EN

**Comment by jacobvosimpronotion** [comment]
"ook": de 'EN' variant noemde ik al

Resteert 'NEN3610 BRO Grouping NL: die variant gebruiken we niet. Of misschien moet ik zeggen: niet meer, want het feit dat ie bestaat, betekent wrs. dat ie vroeger is gebruikt. Dit riekt naar dat er iets moet worden opgeschoond. Kun jij vanuit jouw positie iets aangeven wanneer dat profiel nog werd gebruikt?

**Comment by jacobvosimpronotion** [comment]
BRO LOGICAL

**Comment by ArjanLoeffen** [comment]
Dat is dan toolbox/profiel "NEN3610 BRO Grouping EN", toch?

**Comment by jacobvosimpronotion** [comment]
Klopt. Maar de NL-variant (NEN3610 BRO Grouping NL) die jij noemde, gebruiken we niet.
