### ISSUE TITLE
Verbeteringen EP tussenformaat

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#343]
Een hele lijst van verbeteringen doorvoeren in EP. Hier de essentie, in commentaar zonodig de uitwerking.

(1) Introduceer een andere opzet van ep:documentation, met @type. Daarbinnen `ep:text` en `ep:parameters` in documentatie elementen. `ep:text` is HTML, gewoon als namespaceloze elementjes. Parameters kunnen worden doorgegeven om additionele info over deze tekst mee te leveren. 
NB. "Documentatie" is informatie die relevant is voor de afnemer van het schema, maar die geen technische invloed heeft op de validatie, dwz. de werking van het schema.
 
(2) onderscheid localconstruct en globalconstruct opheffen.

(3) introductie van groups(s) in plaats van message-set(s). 
NB Het verschil tussen group en message(set) is:
- date en patchnumber vervallen; deze gaan naar `ep:parameter`.
- in message-sets kunnen messages en constructs voorkomen. In groups kunnen constructs of groups voorkomen. Dus eigenlijk hetzelfde.

(4) `ep:alias` laten vervallen. Opnemen als `ep:parameter`.
NB zie ook (5)

(5) ep:tech-name vervalt. De afnemer van een EP instantie bepaalt zelf de technische naam op basis van naam. 
NB Uitgangspunt is dat we één EP file kunnen genereren voor de schema's die uit een model komen rollen, en dat dat file voldoende info daarvoor bevat. Dan zou een json-"naam" voor een construct door de json serialisatie zelf moeten worden samengesteld, omdat daar wellicht andere regels gelden dan voor bijvoorbeeld XSD.

(6) Supertypen kunnen worden opgegeven
NB In dat geval is "content" (een `ep:seq` of` ep:choice`) element niet altijd meer nodig. Ik ga er dus van uit dat het omgaan met "supertypen" iets is van de serialisatie, die deze intact laat of platslaat (doorkopieren naar subtypen) oid.

(7) Vorm van de parameters vereenvoudigen, tbv leesbaarheid. 
Het wordt bijv:

```xml
                         <ep:parameter name="use">attribuutsoort</ep:parameter>
                         <ep:parameter name="position">100</ep:parameter>
                         <ep:parameter name="index">1189</ep:parameter>
```

(8) `ep:example` vervalt, wordt `ep:documentation/@type = 'voorbeeld'`

(9) `ep:enum` type wordt een string. 
NB het is feitelijk gewoon “een keuze uit waardes” (=strings) als alternatief voor “waarde” (=datatype).

(10) `ep:parameters` verwijderen uit `ep:choice` en `ep:seq`

(11)  `ep:id` wordt een attribuut `@id` op construct / group
NB: De ID is niet technische info die relevant is voor een schema, maar voor de opbouw van EP zelf.

**Comment by melsk-r** [comment]
> NB: De ID is niet technische info die relevant is voor een schema, maar voor de opbouw van EP zelf.

Ik neem aan dat je bedoelt: 'NB: De ID is niet technische info die ***niet*** relevant is voor een schema, maar voor de opbouw van EP zelf.'

**Comment by ArjanLoeffen** [comment]
Nog een open eindje eigenlijk.

> De ID is niet technische info die niet relevant is voor een schema, maar voor de opbouw van EP zelf.

Dat klopt. Maar hoe moeten we ep:ref vormgeven? Als een xlink? Dat vind ik te zwaar. Zoals het nu is is het ook niet goed:

```xml
<ep:construct>
  <ep:id>id1</ep:id>.
...
<ep:ref>id1</ep:ref>
```

Zullen we ervan maken:

```xml
<ep:construct id="id1">.......
...
<ep:ref href="id1"/>
```
@melsk-r graag je input.

**Comment by melsk-r** [comment]
Lijkt me een prima voorstel.
