### ISSUE TITLE
BRO: fout in XSD bij aanbieden logisch model met daarin IndicatieJaNee(Onbekend) en voidable=yes

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#347]
Bij het aanbieden van een logisch model aan Imvertor verschijnt er in het gegenereerde XSD iets anders dan verwacht in het geval van het datatype 'IndicatieJaNee' of 'IndicatieJaNeeOnbekend' (aanwezig in het conceptual schema) i.c.m. als de tag 'voidable' op 'yes' is ingesteld.

Dit verschijnt er:

```
    <xs:element name="geometryPubliclyAvailable"
                type="bro:IndicationYesNoTypeType"
                minOccurs="0"
                maxOccurs="1">
      <xs:annotation>
           (........)
      </xs:annotation>
    </xs:element>

```

En we verwachten iets als:

```
   <xs:element name="geometryPubliclyAvailable"
                     minOccurs="0"
                     maxOccurs="1"
                     nillable="true">
        <xs:annotation>
            (........)
        </xs:annotation>
        <xs:complexType>
            <xs:simpleContent>
                  <xs:extension base="brocom:IndicationYesNoType">
                     <xs:attribute name="nilReason" type="xs:string" use="optional"/>
                  </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
   </xs:element>

```
Kortom: het XML-attribuut nillable=”true” ontbreekt.

Er zijn ook nog andere verschillen, maar die zijn wat ons betreft minder relevant, zoals:
- wel/geen nilReason
- namespace prefix bro: versus brocom:
- type = IndicationYesNoTypeType versus type = IndicationYesNoType

Merk op dat de gegenereerde XSD er wel goed uitziet bij andere datatypes, zoals het in package brocom gedefinieerde datatype IndicationYesNo or IndicationYesNoUnknown.

**Comment by ArjanLoeffen** [comment]
Het lijkt erop dat de tagged value "voidable" meermaals is opgenomen. Om dat te zien moet je de optie "Show Duplicate Tags" aanvinken:
![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/094f4a2e-7e26-4921-9dd6-898d9d9d4b5b)
Wil je dat eerst even checken?

De nilreason wordt altijd toegevoegd als het attrribuut voidable is, omdat dat is aangegeven via stereotype `<<voidable>>`, via tagged value, omdat de property `forcenillable `is gezet op yes.

Ik kan niet vanaf hier overzien waarom brocom al dan niet goed is, daar is meer uitleg bij nodig.

**Comment by jacobvosimpronotion** [comment]
De tagged value 'Voidable' is maar 1x opgenomen. Met 'ShowDuplicateTags' zien we 'm niet meerdere keren verschijnen.

Zie job https://imvertor.armatiek.nl/imvertor-executor/dashboard/app?subpath=Logical%20model%2FGrondwatergebruik%20%28GUF%29%20logisch%2F20230503&job=2023-05-26-06-36-49-722. Op regel 42.492 van 'model.xmi' zie je de voidable = yes (bij attribuut 'geometryPubliclyAvailable', bij klasse 'DesignSurfaceInfiltration').

In de Gufcom.xsd (in de map xsd\Grondwatergebruik (GUF) logisch\unknown\v20230503 van de ZIP-file) zie je nabij regel 233 het resultaat ervan.

**Comment by ArjanLoeffen** [comment]
Ik kan het reproduceren en kijk ernaar.

**Comment by ArjanLoeffen** [comment]
Deze casus gaat over het verwijzen naar een externe constructie `IndicatieJaNee`. Die wordt dus opgelost via de conceptual schemas. Hierin is niet aangegeven wat voor een constructie het betreft in het model (enumeratie? complext datatype?). Imvertor neemt daarom aan dat het een primitief datatype is.

Nu blijkt dat voor deze situatie nillable niet was uitgeprogrammeerd. Dat is nu toegevoegd. 

Blijft wel de behoefte om in de mapping (/resources/input/BRO/xsd/cm-BRO-COMMON.xml) aan te geven welk stereotype de constructie heeft. Dit is eerder in een issue opgenomen.
Maar dat moet ook nog beter worden afgetast in de code van de schema generator.

**Comment by jacobvosimpronotion** [comment]
@ArjanLoeffen: Kun je aangeven welke aanpassing(en) in de mapping (/resources/input/BRO/xsd/cm-BRO-COMMON.xml) moet(en) worden doorgevoerd om het probleem op te lossen (naast dat er wat 'uitgeprogrammeerd moest worden)? Je schrijft "iets van een stereoTypes", maar omdat het woord 'stereotype' nu niet in die mapping voorkomt, is ons niet duidelijk wat je bedoelt.

Verder: wat je hebt uitgeprogrammeerd, komt dat beschikbaar via een nightly-build?

**Comment by ArjanLoeffen** [comment]
1/ Die opmerking over stereoType betreft iets nieuws: het opnemen van stereotypen in de conceptual schema's. Die zijn daar nu géén onderdeel van. Er zijn andere situaties waarin die info eigenlijk ook gewenst is.

2/ De correctie is in de Nightly build beschikbaar gekomen. Heb je het getest?

**Comment by ArjanLoeffen** [comment]
@jacobvosimpronotion Kun je de job eens runnen met in de properties file:

```
debug                   = yes
debugmode               = ISOS
```

**Comment by jacobvosimpronotion** [comment]
Gedaan. Job ID: 2023-05-30-11-33-08-289.

**Comment by ArjanLoeffen** [comment]
Ik denk, op basis van een debug voorbeeld, dat het hier gaat om een als conceptueel herkende enumeratie. Daarvoor was nillable ook niet uitgeprogrammeerd.  Nu aangepast.
Morgen beschikbaar als Nighly-build.5.

**Comment by jacobvosimpronotion** [comment]
Opgelost! Het XSD bevat nu:

```
 <xs:element name="geometryPubliclyAvailable"
             minOccurs="0"
             maxOccurs="1"
             nillable="true">
    <xs:annotation>
                 (...)
    </xs:annotation>
    <xs:complexType>
       <xs:simpleContent>
          <xs:extension base="bro:IndicationYesNoTypeType">
             <xs:attribute name="nilReason" type="xs:string" use="optional"/>
          </xs:extension>
       </xs:simpleContent>
    </xs:complexType>
 </xs:element>
```
