### ISSUE TITLE
UML diagrammen afwezig in catalogus bij een logisch model

### ISSUE THREAD

**Issue by PalmJanssen** [Imvertor/Imvertor-Maven#351]
Het viel me op dat bij het genereren van een catalogus bij een logisch model er geen UML diagram in de catalogus wordt gezet. Als je conceptueel model kiest komt er wel een diagram. Het eerste in ongewenst. Ook bij logisch model is een UML diagram in de catalogus nodig.

**Comment by ArjanLoeffen** [comment]
Ik ga ervan uit dat MIM 1.1 óók wordt gevolgd in de logische modellen. Dus dan koppelen we Geonovum aan de MIM 1.1 documentatieregels. Daarin staat wat er wordt gedocumenteerd en op welke plek dat gebeurt; ook het opnemen van diagrammen is daarin geregeld. Feitelijk wordt voor logische modellen exact dezelfde documentatie aanpak gevolgd als voor conceptuele modellen.
