### ISSUE TITLE
BRO: Tonen attributen supertype bij subtype o.b.v. stereotype van generalisatie

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#352]
In BRO-catalogi worden attribuutsoorten van het supertype (bijv. 'Registratieobject') getoond bij een subtype (bijv. 'Grondwaterstandonderzoek') als de betreffende generalisatierelatie het stereotype 'Static' heeft.

Wat is de oorsprong van dit stereotype? Het MIM BRO Grouping NL profiel bevat de stereotypen 'Static' en 'Static liskov'. Is het BRO-specifiek? Of Imvertor-breed?

Ik heb op https://imvertor.armatiek.nl/imvertor-executor/dashboard/wikis gezocht naar 'liskov', maar vond niets. Wel op 'static', maar dan gaat het specifiek over multiple inheritance, en daar gaat ons issue niet over.

**Comment by ArjanLoeffen** [comment]
Wanneer een generalisatie relatie _static_ is, betekent dat, dat de eigenschappen van het supertype doorgekopieerd moeten worden naar de subtypen. Het is dus een indicatie dat het supertype feitelijk alleen de rol van een "collectie eigenschappen" (attributen, relaties) is (zoals "object met historie"), en niet een gemeenschappelijke noemer voor alle subtypen ("fiets").

_Liskov_ is een generalisatie volgen het [Liskov principe](https://nl.wikipedia.org/wiki/Substitutieprincipe_van_Liskov). 

_Static liskov_ is de combinatie van beiden; veelal is dat de implementatie van de generalisatie zonder speciale aanduiding.

Static en Static liskov zijn geen MIM constructies, maar zijn onderdeel van de vaste MIM extensies, die destijds zijn vastgesteld.
