### ISSUE TITLE
BRO: Nieuwe datatypen in BRO common conceptueel: 'NITGCode' en 'GUID'

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#353]
In het BRO common conceptueel package zijn nieuwe datatypen gedefinieerd: 'NITGCode' en 'GUID'. Wat moet hiervoor gebeuren om dit op de gewenste manier in de catalogi getoond / door Imvertor op de juiste manier verwerkt te krijgen?

Minimaal leek me aanpassing van src/main/resources/input/BRO/xsd/cm-BRO-COMMON.xml vereist.

In catalogi willen we deze nieuwe datatypen getoond hebben zoals nu voor NITGCode al in de GMW catalogus (zie https://github.com/Imvertor/Imvertor-Maven/issues/269):

**Domein** (leeg)
**Naam** NITGCode
**Type** Code
**Opbouw** (overgenomen vanuit het aangeleverde model)

**Comment by ArjanLoeffen** [comment]
Deze moeten dan worden opgenomen in cm-BRO-COMMON.xml, dat is correct. Omdat NITGCode is al onderdeel van BRO-GMW moet hij daar dan misschien weg; het is dubbelop.
Als GUID een speciaal domein heeft moeten we die ook opnemen in postprocessing; anders kan het bij het toevoegen aan cm-BRO-COMMON.xml blijven, zover ik nu zie.

**Comment by jacobvosimpronotion** [comment]
Wat is de afspraak m.b.t. wie (BRO Standaardisatie of Armatiek) bestanden als cm-BRO-COMMON.xml aanpast?

NITGCode uit GMW moet idd verwijderd worden, maar pas nadat zeker is dat de brocommon-variant werkt.

**Comment by ArjanLoeffen** [comment]
Als BRO zich veilig voelt bij deze aanpassingen kan BRO deze ook doorvoeren op Development, en een pull request doen.
Anders pakt Armatiek het op.

**Comment by jacobvosimpronotion** [comment]
Wat mij betreft pakken jullie dit op. Jullie moeten hierbij toch ook een wijziging doorvoeren vanwege het op de juiste manier tonen ervan in de catalogi.

**Comment by ArjanLoeffen** [comment]
De GUID is dus ook een Code?

**Comment by ArjanLoeffen** [comment]
Okay, heb ik doorgevoerd. Graag testen morgen Nightly build bugfix release 8 (of hoger).

**Comment by jacobvosimpronotion** [comment]
Zojuist getest (met nightly build 8) en zowel NITGCode als GUID worden op de juiste manier getoond in de catalogus.
