### ISSUE TITLE
BRO: Nieuw te ondersteunen GML datatype: GM_Aggregate

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#354]
We willen GM_Aggregate gaan gebruiken. Wat moet hiervoor aangepast worden? Wellicht https://github.com/Imvertor/Imvertor-Maven/blob/master/src/main/resources/input/BRO/xsd/cm-GML321-profile.xml?

Kunnen we de aanpassingen zelf doen?

**Comment by ArjanLoeffen** [comment]
GM_Aggregate is onderdeel van de GML 322 configuratie. (Ik zie dat hij daarin zelfs dubbel is opgenomen; dit zouden we moeten opschonen.)
Jullie kunnen GML 322 gaan volgen, ik weet niet of dat voor jullie een optie is. Anders moet het alsnog aan GML321 worden toegevoegd, en ik weet niet of dat zomaar kan. Als het wel onderdeel is van GML 321 is dat wellicht een omissie in de conceptual mapping, en voeg ik dat toe.

**Comment by jacobvosimpronotion** [comment]
GM_Aggregate wordt op dezelfde manieren benoemd / aangehaald in de GML 3.2.1 specificatie (https://portal.ogc.org/files/?artifact_id=20509) als in de GML 3.2.2 specificatie (https://portal.ogc.org/files/?artifact_id=74183&version=2).

Het lijkt me daarom een omissie in de conceptual mapping. Als je het hier mee eens bent, dan is mijn verzoek om GM_Aggegrate aan het de conceptual mapping toe te voegen.

**Comment by ArjanLoeffen** [comment]
In GML322 vatten we `GM_Aggregate `op als `MultiGeometryPropertyType `maar ook als `AggregatePropertyType `Die laatste komen we niet tegen in de GML schema's. Het lijkt een fout. Is het juist dat we dan uit moeten gaan van het volgende?

```xml
 <cs:Construct>
          <cs:name>GM_MultiPrimitive</cs:name>
          <cs:sentinel>false</cs:sentinel>
          <cs:xsdTypes>
             <cs:XsdType>
                <cs:name>MultiPrimitive</cs:name>
                <cs:asAttribute>MultiGeometryPropertyType</cs:asAttribute>
                <cs:asAttributeDesignation>complextype</cs:asAttributeDesignation>
                <cs:primitive>false</cs:primitive>
             </cs:XsdType>
          </cs:xsdTypes>
 </cs:Construct>
```
Dan voeren we dat door in GML321 en GML322.

**Comment by jacobvosimpronotion** [comment]
Ik heb je vraag binnen BRO Standaardisatie uitstaan en kom erop terug.

**Comment by jacobvosimpronotion** [comment]
Het wordt toch wat anders: GM_MultiPrimitive i.p.v. GM_Aggregate.

Verdere feedback:
"Het UML type GM_MultiPrimitive wordt dan gemapt op een XSD gml:MultiGeometryPropertyType als het gaat om het type van een attribuut of naar een gml:MultiGeometry als het gaat om (een verwijzing naar) een root-element.

De door Armatiek voorgestelde configuratie lijkt me dus correct, met uitzondering van <cs:name>MultiPrimitive</cs:name waarover ik niet zeker ben. Zou dat niet <cs:name>MultiGeometry</cs:name> moeten zijn als het om de naam van een root-element gaat? Maar dat hangt dus af waarvoor Imvertor het element cs:name gebruikt."

**Comment by ArjanLoeffen** [comment]
Zo ver ik weet wordt de naam in `<cs:name>` gebruikt als naam van het element waarnaar wordt verwezen, dus `<gml:MultiPrimitive>`.

**Comment by HanWelmer** [comment]
cs:name komt op diverse plekken voor. Mijn beeld welke waarvoor wordt gebruikt is niet 100%. Maar dit is wat ik aanneem:

- **cs:name van een cs:Construct** wordt gebruikt om een naam (van een entiteit, attribuut, relatie, oid) in UML te koppelen aan een constructie in de Imvertor configuratie-bestanden.
- **cs:name van een cs:XsdType** wordt gebruikt door de Imvertor XSD generator als er een root element moet worden gegenereerd, of als er een substitutiongroup moet worden gegenereerd, of als er een complexType moet worden gegenereerd, of als er een extension van een complexType moet worden gegenereerd.

Daarnaast hebben we nog de **xs:asAttribute** van een xs:XsdType, wat volgens mij wordt gebruikt als er een type van een XML-element moet worden gegenereerd.

**Op basis van de GML ISO standaard en de XML coding daarvan kom ik tot de volgende keuzes:**

- De name van de construct **GM_MultiPrimitive** is letterlijk overgenomen uit het GML conceptueel model in de ISO
19107 standaard.
- De name van het XsdType **MultiGeometry** is letterlijk overgenomen van het root element in de gml [geometryAggregates.xsd](https://schemas.opengis.net/gml/3.2.1/geometryAggregates.xsd)https://[schemas.opengis.net/gml/3.2.1/geometryAggregates.xsd](https://schemas.opengis.net/gml/3.2.1/geometryAggregates.xsd).
- De asAttribute van het XsdType **MultiGeometryPropertyType** is letterlijk overgenomen van het complexType in de gml [geometryAggregates.xsd](https://schemas.opengis.net/gml/3.2.1/geometryAggregates.xsd)https://[schemas.opengis.net/gml/3.2.1/geometryAggregates.xsd](https://schemas.opengis.net/gml/3.2.1/geometryAggregates.xsd)

NB: als er een complexType of extension moet worden gegenereerd, zal de cs:name van het XsdType moeten worden aangevuld met Type, dus in dit geval "MultiGeometryType".

**Alles samenvattend kom ik tot het volgende voorstel voor de construct:**

<cs:Construct>
          <cs:name>GM_MultiPrimitive</cs:name>
          <cs:sentinel>false</cs:sentinel>
          <cs:xsdTypes>
             <cs:XsdType>
                <cs:name>MultiGeometry</cs:name>
                <cs:asAttribute>MultiGeometryPropertyType</cs:asAttribute>
                <cs:asAttributeDesignation>complextype</cs:asAttributeDesignation>
                <cs:primitive>false</cs:primitive>
             </cs:XsdType>
          </cs:xsdTypes>
 </cs:Construct>

**Comment by ArjanLoeffen** [comment]
Dat kan ik doorvoeren. Is het in GML322 ook `MultiGeometry `(en niet `MultiPrimitive`)? Dan pas ik dat daar ook aan.

**Comment by jacobvosimpronotion** [comment]
Het zou me verbazen als dit in GML322 zou afwijken van GML321, dus ik stel voor om het zo te implementeren.

**Comment by ArjanLoeffen** [comment]
Dan verwijs je dus in de modellen naar GM_Aggregate en dat keert terug in de schema's als MultiGeometry en MultiGeometryPropertyType. Er wordt dan in de Conceptual Maps géén GM_MultiGeometry opgenomen, maar alleen de GM_Aggregate, en voor 3.2.1 en 3.2.2 wordt dat als  MultiGeometry geserialiseerd. 

Als ik het zo goed heb begrepen wil je dat dan afstemmen met @ThiesMesdag :

GM_Aggregate in conceptual map voor GML322 van Kadaster (met duplicaat, moet worden gecorrigeerd) én van OGC (met duplicaat, moet worden gecorrigeerd), situatie zoals die nu is:
```xml
<cs:Construct>
          <cs:name>GM_Aggregate</cs:name>
          <cs:sentinel>false</cs:sentinel>
          <cs:xsdTypes>
             <cs:XsdType>
                <cs:name>Aggregate</cs:name>
                <cs:asAttribute>MultiGeometryPropertyType</cs:asAttribute>
                <cs:asAttributeDesignation>complextype</cs:asAttributeDesignation>
                <cs:primitive>false</cs:primitive>
             </cs:XsdType>
          </cs:xsdTypes>
       </cs:Construct>
```

GM_MultiGeometry in conceptual map van Kadaster én OGC, situatie zoals die nu is:
```xml
<cs:Construct>
          <cs:name>GM_MultiGeometry</cs:name>
          <cs:sentinel>false</cs:sentinel>
          <cs:xsdTypes>
             <cs:XsdType>
                <cs:name>MultiGeometry</cs:name>
                <cs:asAttribute>MultiGeometryPropertyType</cs:asAttribute>
                <cs:asAttributeDesignation>complextype</cs:asAttributeDesignation>
                <cs:primitive>false</cs:primitive>
             </cs:XsdType>
          </cs:xsdTypes>
          <cs:oasTypes>
             <cs:OasType>
                <cs:name>geometrycollectionGeoJSON</cs:name>
                <cs:primitive>false</cs:primitive>
             </cs:OasType>
          </cs:oasTypes>
       </cs:Construct>
```

Conclusies:
1/ Deze constructie moet ook worden opgenomen voor GML 321
2/ Kadaster gaat mee met de constructie, situatie zoals die moet worden:
```xml
<cs:Construct>
          <cs:name>GM_Aggregate</cs:name>
          <cs:sentinel>false</cs:sentinel>
          <cs:xsdTypes>
             <cs:XsdType>
                <cs:name>MultiGeometry</cs:name>
                <cs:asAttribute>MultiGeometryPropertyType</cs:asAttribute>
                <cs:asAttributeDesignation>complextype</cs:asAttributeDesignation>
                <cs:primitive>false</cs:primitive>
             </cs:XsdType>
          </cs:xsdTypes>
          <cs:oasTypes>
             <cs:OasType>
                <cs:name>geometrycollectionGeoJSON</cs:name>
                <cs:primitive>false</cs:primitive>
             </cs:OasType>
          </cs:oasTypes>
       </cs:Construct>
```

**Comment by ThiesMesdag** [comment]
We  hebben er naar gekeken en de keuze voor GM_MultiPrimitive lijkt ons inderdaad beter dan direct voor de GM_Aggregate te gaan. Uitbreiden kan altijd nog en het is inderdaad meer in lijn met het SF2 profile. Daarbij ga er vanuit dat het voor de toepassing van de MultiGeometry niet uit maakt.

**Comment by HanWelmer** [comment]
Added pull request https://github.com/Imvertor/Imvertor-Maven/pull/396 to add construct for GM_MultiPrimitive to the BRO conceptual schema configuration files.

**Comment by HanWelmer** [comment]
Pull request merged to master.
Successfully tested with SAD conceptual model submitted to Imvertor 3.0.0.
