### ISSUE TITLE
Nieuwe Respec omgeving geeft veel warnings op door Imvertor gegenereerde catalogus.

### ISSUE THREAD

**Issue by wilkoquak** [Imvertor/Imvertor-Maven#360]
Kijk bijvoorbeeld naar https://geonovum.github.io/dso-cim-tr/ . Hierin staat rechtsboven dat er flink veel warnings zijn. Als je de warnings bekijkt dan is dit de foutmelding: Found linkless <a> element with text "" but no matching <dfn>.

Kijkend naar de bron html zie ik inderdaad <a> tags zonder tekst. Is het inderdaad incorrecte html?

**Comment by ArjanLoeffen** [comment]
Het lijkt erop dat deze fout wordt gecreëerd door **core/link-to-dfn** plugin. Wat doet die en is die noodzakelijk?

**Comment by wilkoquak** [comment]
Geen idee, wie zou dat moeten weten? De hele plugin zegt me niet zoveel. Het lijkt me sowieso wel raar dat je een link naar een ander element hebt maar geen tekst erin zodat je er nooit op kunt klikken.

**Comment by ArjanLoeffen** [comment]
Het lijkt erop dat de plugin signalleert dat een <a> voorkomt zonder name attribuut. Dat klopt, die komen voor. Ik moet uitzoeken waarom dat in andere respec modellen geen probleem oplevert.
Voorbeeld:

```xml
<section id="">
      <h3>Objecttypen </h3>
      <a class="anchor" id="graph_EAID_025C7816_E47A_4b28_A6BC_97B676F1CE15"></a>
      <a class="anchor" id="global_class_CIMTR_Maatregel"></a>
      <section id="global_class_CIMTR_Maatregel">
         <h4> Maatregel</h4>
```

**Comment by ArjanLoeffen** [comment]
In het eerdere voorbeeld blijkt dat een a/@id dubbel optreedt. Dat moet worden hersteld. Het is echter niet de oorzaak van de melding (en het wordt in alle browsers zover we kunnen nagaan correct afgehandeld.).

In een gewone SAMPLE run treedt deze melding niet op.
Zie https://geonovum.github.io/SAMPLE/#global_class_BaksteenProductie_Fabriek

Mijn conclusie is dat het aan de gebruikte config/plugin ligt. Dat lijkt een logius inplementatie te zijn.

Ter vergelijking:

```xml
<section id="">
         <h4>Objecttypen </h4>
         <a class="anchor" id="graph_EAID_0D13D4A0_F7FA_4417_A5FC_3F4C83F067F2"></a>
         <a class="anchor" id="global_class_BaksteenProductie_Fabriek"></a>
         <section id="global_class_BaksteenProductie_Fabriek">
            <h5> Fabriek</h5>
```
De actieve scripts zijn:

```xml
        <script class="remove" src="./config.js"></script>
        <script class='remove' src='https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js' async></script>

```

**Comment by wilkoquak** [comment]
Ik zie net per mail een discussie langskomen over de vraag of die constructie (blijkbaar zijn het named anchors) niet gewoon toegestaan moet worden door logius. Ik houd je op de hoogte.

**Comment by wilkoquak** [comment]
Uit de maildiscussie kwam het volgende voorstel: De “name” attribuut van de <a> tag is “obsolete” in HTML5. Indien mogelijk stel ik voor het volgende formaat te gebruiken: <span id='_Ref503261397'></span>. Zou dat werken voor Imvertor?

**Comment by ArjanLoeffen** [comment]
Ik kijk er volgende week naar.

**Comment by Gtrouborst** [comment]
> **Note**
> **Logius-ReSpec**
> Bij Geonovum zijn we recent overgestapt op **Logius-ReSpec**. Dit is een fork op de W3C/ReSpec. In deze versie is het mogelijk om definities te voorzien van een speciale html-tag. Eerder maakten we bij Geonovum gebruik van een oudere versie van ReSpec. Daarin werden definities handmatig opgenomen/vormgegeven. 

> **Note**
> **Imvertor properties file**
> Waarschijnlijk speelt dit probleem alleen als in de _properties file_ het volgende staat: `createofficemode = click` - Ik verwacht op `createofficemode = plain` geen ReSpec-_warnings_, maar ik heb dat niet getest.

@ArjanLoeffen, @wilkoquak: hopelijk geeft onderstaande tekst _een antwoord op_, én _een oplossing voor_ de volgende vragen:

1. > Het lijkt erop dat deze fout wordt gecreëerd door **core/link-to-dfn** plugin. Wat doet die en is die noodzakelijk?
2. > Geen idee, wie zou dat moeten weten? De hele plugin zegt me niet zoveel. Het lijkt me sowieso wel raar dat je een link naar een ander element hebt maar geen tekst erin zodat je er nooit op kunt klikken.
3. > Ik moet uitzoeken waarom dat in andere respec modellen geen probleem oplevert.

## Wat doen de dfn-plugins?

(Logius)ReSpec faciliteert het toepassen van definities op een uniforme manier. Het roept hiervoor een stuk of 8 javascript plugins aan (zie: `src/core/`: `dfn~` / `~dfn`).

## Noodzakelijk?
Het heeft een aantal voordelen (en de werkversie van [MIM1.2 maakt hier veelvuldig gebruik van](https://geonovum.github.io/MIM-Werkomgeving/#objecttype)): 

- Het is een manier om definities in de code op een uniforme manier (technisch) vorm te geven.
- Ook in het kader van webtoegankelijkheid is dit een positieve ontwikkeling. Door de `<dfn>` tag te gebruiken is een definitie ook machinesleesbaar.
- Verder zit er nuttige functionaliteit aan vast, zoals een [automatisch gegenereerde definitielijst](https://geonovum.github.io/MIM-Werkomgeving/#index-defined-here).
- Bovendien kun je er, als je een begrip definieert, op andere plekken binnen het document naar verwijzen met (attribuutloze) _anchors_. Hoe het werkt, lees je in de  [ReSpec Documentatie](https://respec.org/docs/#definitions-and-linking).

## Wat gaat er mis en wanneer?
Op die (attribuutloze) _anchors_, ontstaat het probleem met de door Imvertor gegenereerde catalogus. Als je klikbare diagrammen opneemt in de documentatie, voegt Imvertor extra html-tags toe: een `<map>` tag met daarbinnen één of meerdere `<area>` tags (zie: _code snippet_). 

```html
<!-- Voorbeeld 1: DiSgeo Bestuurlijke Gebieden -->
<section id="EAID_ECC1D8E3_7991_4b70_8AC3_26EDA4D7687E">
   <h3>   CM Bestuurlijk gebied - overzicht</h3>
   <div class="imageinfo overview">
      <img src="data/Images/EAID_ECC1D8E3_7991_4b70_8AC3_26EDA4D7687E.png" usemap="#imagemap-EAID_ECC1D8E3_7991_4b70_8AC3_26EDA4D7687E">
      <map name="imagemap-EAID_ECC1D8E3_7991_4b70_8AC3_26EDA4D7687E">
         <area shape="rect" alt="BestuurlijkGebied" coords="323,273,579,396" href="#graph_EAID_CE4A19B0_E8ED_4517_A5F2_DACF596D2421">
         <area shape="rect" alt="BestuurlijkGebiedOpLand" coords="326,519,581,570" href="#graph_EAID_E67F6AFB_E933_4fc6_BE25_C2151BC3F3DA">
         <area shape="rect" alt="BestuurlijkGebiedOpZee" coords="48,519,303,570" href="#graph_EAID_5F74DAB6_FE84_42df_9E9D_1511E48F4311">
      </map>
   </div>
</section>
```
Een <area> verwijst met het attribuut `href` naar de `id` van een _anchor_ op een andere positie in het document. Die positie is gemarkeerd met twee <a> tags: één met een **EAID** (Enterprise Architect)  en één met een **leesbare naam** als `id` (zie: onderstaande _code snippet_).

```html
<!-- Voorbeeld 2: DiSgeo Bestuurlijke Gebieden -->
<section id="">
   <h3>Objecttypen   </h3>
   <a class="anchor" id="graph_EAID_CE4A19B0_E8ED_4517_A5F2_DACF596D2421"></a>
   <a class="anchor" id="global_class_BestuurlijkGebied_BestuurlijkGebied"></a>
   <section id="global_class_BestuurlijkGebied_BestuurlijkGebied">
      <h4>   Bestuurlijk­Gebied</h4>
   </section>
</section>
```
ReSpec ziet anchors (`<a>`) zonder `href` als verwijzingen naar een definitie (`<dfn>`), maar kan die vervolgens niet vinden en geeft daarop een _warning_.

## Voorstel
Een even elegante als eenvoudige oplossing is als in de Imvertorcode een `<area>` niet verwijst naar een speciaal toegevoegde `<a>`, maar naar een `<section id="naamVanHetModelelement">`, die toch al in het document zit, zoals in onderstaande voorbeelden. Als ik dit test, dan werkt het prima en ben ik de _warnings_ kwijt.

```html
<!-- Voorbeeld 3: DiSgeo Bestuurlijke Gebieden -->
<section id="EAID_ECC1D8E3_7991_4b70_8AC3_26EDA4D7687E">
   <h3>   CM Bestuurlijk gebied - overzicht</h3>
   <div class="imageinfo overview">
      <img src="data/Images/EAID_ECC1D8E3_7991_4b70_8AC3_26EDA4D7687E.png" usemap="#imagemap-EAID_ECC1D8E3_7991_4b70_8AC3_26EDA4D7687E">
      <map name="imagemap-EAID_ECC1D8E3_7991_4b70_8AC3_26EDA4D7687E">
         <area shape="rect" alt="BestuurlijkGebied" coords="323,273,579,396" href="#global_class_BestuurlijkGebied_BestuurlijkGebied">
      </map>
   </div>
</section>
```

```html
<!-- Voorbeeld 4: DiSgeo Bestuurlijke Gebieden -->
<section id="">
   <h3>Objecttypen   </h3>
   <section id="global_class_BestuurlijkGebied_BestuurlijkGebied">
      <h4>   Bestuurlijk­Gebied</h4>
   </section>
</section>
```

**Comment by ArjanLoeffen** [comment]
Ik heb het doorgevoerd. Ik zie zelf niets geks gebeuren. Kunnen jullie het nog even goed testen in development? Vanaf 15 aug beschikbaar.
