### ISSUE TITLE
Introduceer schemarules voor requirements classes van Json schema best practices

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#363]
Ik ga ervan uit dat er voor de implementatie van Json schemas (best practices) vaste combinaties zijn van _Requirements classes_ die de analist wil activeren bij het aanroepen van Imvertor. Deze kunnen worden benoemd en daarmee meegegeven aan Imvertor. Deze worden opgenomen in de `/input` folder onder

https://github.com/Imvertor/Imvertor-Maven/tree/Development/src/main/resources/input/Geonovum/cfg/schemarules

De naam van het betreffende XML bestandje (binnen de input folder van de owner, bijv. Geonovum) wordt meegegeven als CLI parameter

`createjsonschemavariant = jsonfg`

Dat verwijst dan naar 

https://github.com/Imvertor/Imvertor-Maven/tree/Development/src/main/resources/input/Geonovum/cfg/schemarules/JSON-jsonfg.xml

**Comment by PalmJanssen** [comment]
zie er goed uit.
