### ISSUE TITLE
BRO: ReSpec catalogus geeft fout Duplicate definitions of 'entiteit'

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#366]
De ReSpec catalogus geeft als fout: Duplicate definitions of 'entiteit' at: ..... - en dan een reeks met voorkomens van 'Entiteit' in de catalogus. Bijv. op https://broprogramma.github.io/GMW/.

Dit hebben we gisterochtend (22-08-2023) voor het eerst geconstateerd. Bij het werken met Nightly-build.9. Zie job 2023-08-22-09-44-56-979.

**Comment by jacobvosimpronotion** [comment]
Deze melding hangt hoogstwaarschijnlijk samen met issue https://github.com/Imvertor/Imvertor-Maven/issues/365.

**Comment by ArjanLoeffen** [comment]
Klopt. Ik zie dat in een laatste slag overal de namen van de objecttypen zijn vervangen door "entiteit", en de naam van het veld door "Type gegeven". Daardoor loopt dit fout. Ik realiseer me nu dat ik niet weet waar jullie die <dfn> dan verwachten. 

Om dit duidelijk te maken: hieronder is het wel helder:
![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/519057da-79b9-4a81-9307-458e072e8ed0)

Maar waar moet hij hier geplaatst worden?
![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/2a98717d-4d2d-4204-8ca8-97c48729329d)

**Comment by ArjanLoeffen** [comment]
Ja, klopt. Nogmaals: Waar moet `<dfn>` komen?
