### ISSUE TITLE
Waardelijst gebruiken ipv waardenlijst

### ISSUE THREAD

**Issue by PB-GNM** [Imvertor/Imvertor-Maven#367]
In onze Respec documenten willen wij 'waardelijst' gebruiken zonder tussen-n zoals de taalunie dat voorschrijft.
Zie ook: https://woordenlijst.org/leidraad/8/1 en https://woordenlijst.org/#/?q=waardenlijst

Imvertor maakt nu een kopje met 'waarde**n**lijst'  in onze Respec documenten maar dat kunnen wij niet direct aanpassen.
zie bv: https://docs.geostandaarden.nl/imev/imev/#lis
Het verzoek is deze 'n' te verwijderen in het deel van Imvertor waar dit kopje aangemaakt wordt.

**Comment by ArjanLoeffen** [comment]
Mijn taalgevoel zegt dat dit niet klopt. De regel die de taalunie stelt is te ver doorgevoerd. Dat "waardes" in het nederlands voorkomt maakt de regel wel toepasbaar maar in dit geval verwarrend. Het is geen lijst "te typeren als waarde" maar een lijst met daarin waarden. Maar de discussie is oneindig door te voeren, dus moeten we het praktisch behandelen.

Je vraagt ons nu 
- voor Geonovum specifiek de term _waardenlijst_ te vervangen door _waardelijst_?
- een derde taal te introduceren (naast Nederlands en Engels), namelijk Geonovum engels?
- een vertaalmodule in te bouwen waarbij iedereen ervoor kan kiezen bepaalde woorden/spelling te vervangen door een ander woord/spelling?

Want ik vermoed dat het niet bij deze ene spellingscorrectie blijft.

NB er is in de jaren 2015 e.v. discussie geweest binnen Kadaster wat de juiste spelling was, dat werd _waardenlijst_. Ik vind het twijfelachtig om nu spellingen tussen (semi)overheidsorganisaties te laten afwijken.

**Comment by ThiesMesdag** [comment]
Ah ik was ook al bezig met een reactie en kom tot dezelfde conclusie:

Jaren geleden hebben wij bij het Kadaster deze discussie ook gevoerd. We zijn er toen op uit gekomen dat het een lijst is van waardes (dus geen n op het eind), want waarden zijn vaak waarden zoals in "normen en waarden" en dat vonden we dan weer niet passen bij een lijst met plaatsnamen, of een lijst van landen. Vandaar dat het waardelijsten zijn geworden en niet waardenlijsten. Deze discussie speelt vaker op en misschien is  het uiteindelijk een kwestie van smaak. Maar inmiddels waardelijst wel de standaard benaming voor zo'n "externe lijst waarin je de toegestane waardes/waarden voor een gegevens element kan vinden"
Ik ben dus tegen deze wijziging, ook in NEN3610 hebben we het over waardelijsten.

**Comment by ArjanLoeffen** [comment]
Wacht even, dan is tot nu toe deze term niet goed gebruikt in de code. Het moet dus _overal_ Waardelijst zijn. Dat vat ik op als een bugfix. Die kan ik doorvoeren. Is dat wat we willen?

**Comment by ThiesMesdag** [comment]
Ik kwam dus niet tot dezelfde conclusie en ben het eens met Pieter. Bij Geonovum wordt waardenlijst 16 keer gevonden en waardelijst 33 keer. 

Als het inderdaad verder geen impact heeft lijkt het doorvoeren van de Bugfix mij prima.

**Comment by ArjanLoeffen** [comment]
In de MIM standaard komen _waardelijst_ 24x voor, en _waardenlijst_ 21 keer.  Ook daar moet dan een opschoonslag worden gedaan.
:-)

**Comment by ArjanLoeffen** [comment]
Dit moet wel worden voorgelegd aan de gebruikers. Ik ga ervan uit dat als het een bugfix is, het kopje

**Inhoud van waardenlijsten**

overal moet worden vervangen door

**Inhoud van waardelijsten**

Zover ik weet wordt door Kadaster trouwens overal de term _Waardenlijst_ gebruikt (als onderdeel van CDMKAD/IMKAD), @ThiesMesdag is dat zo?

**Comment by ThiesMesdag** [comment]
> Dit moet wel worden voorgelegd aan de gebruikers. Ik ga ervan uit dat als het een bugfix is, het kopje
> 
> **Inhoud van waardenlijsten**
> 
> overal moet worden vervangen door
> 
> **Inhoud van waardelijsten**
> 
> Zover ik weet wordt door Kadaster trouwens overal de term _Waardenlijst_ gebruikt (als onderdeel van CDMKAD/IMKAD), @ThiesMesdag is dat zo?

Nee, dat is niet zo. We gebruiken juist waardelijsten (zonder n). Zie bijvoorbeeld kadaster.nl/waardelijsten.

**Comment by ThiesMesdag** [comment]
Ja, die onderstreepte regel komt denk ik uit imvertor en die daaronder komt van mijzelf. Daar heb ik zelfs de l weggelaten (oops). 
Ja, er is wel een nieuwere versie, maar die is nog nooit vastgesteld. De informatielevering verloopt via de producten. Die zijn wel doorontwikkeld en dat zal ook terecht komen in de nieuwe IMKAD.  We hebben wel in de planning om de beta/draft/werk versie ook formeel te publiceren.

**Comment by ArjanLoeffen** [comment]
Okay, dan voer ik het voor iedereen door. Het is klaarblijkelijk correct nederlands en het vereist dus een bugfix.

**Comment by Gtrouborst** [comment]
> In de MIM standaard komen _waardelijst_ 24x voor, en _waardenlijst_ 21 keer. Ook daar moet dan een opschoonslag worden gedaan. :-)

Dank voor deze check @ArjanLoeffen. We nemen dit mee voor MIM 1.2!
