### ISSUE TITLE
toelichting verschijnt twee keer in de catalogus,

### ISSUE THREAD

**Issue by wilkoquak** [Imvertor/Imvertor-Maven#368]
Bij het draaien van Imvertor verschijnt momenteel de toelichting twee keer. Eén keer in de tabel en één keer in de paragraaf met het tabje toelichting. Dat is één keer teveel. Als ik kijk naar oude catalogi verschijnt de toelichting alleen in de tabel en niet in de losse paragraaf. Dank @PalmJanssen voor het melden.

**Comment by ArjanLoeffen** [comment]
@wilkoquak 
Welke versie, welk infomodel, en graag een screenshot van waar dat gebeurt?

**Comment by wilkoquak** [comment]
Dank. Het werkt.
