### ISSUE TITLE
Diakritische tekens in catalogus worden twee keer ge-escaped.

### ISSUE THREAD

**Issue by wilkoquak** [Imvertor/Imvertor-Maven#376]
In Enterprise Achitect heb ik in een comment veld een é (een e met een accent aigu). Imvertor (nightly build)  pikt deze netjes op en maakt hiervoor een escape sequence &#233;   Alleen wordt de ampersand in de escape sequence nog een keer ge-escaped en staat er in de gegenereerde html de volgende '&amp;#233;' en verschijnen er dus rare escape codes in de catalogus.  Dit is niet de bedoeling.

Zie bijvoorbeeld de caption onder Figuur 2 in (https://geonovum.github.io/dso-cim-ow/#fig-ow-op ). Bij nader inzien; het kan zijn dat di alleen mis gaat bij captions.

**Comment by ArjanLoeffen** [comment]
Ik kan dit reproduceren en ga het oplossen in Development.

**Comment by wilkoquak** [comment]
Het werkt naar wens. dank! Mag ik overigens zelf het issue sluiten? Of gaat er dan iets mis bij jullie in de workflow?

**Comment by ArjanLoeffen** [comment]
Nee hoor, sluit maar.

--
Arjan vanaf mobiel

Op ma 9 okt. 2023 16:03 schreef Wilko Quak ***@***.***>:

**Comment by wilkoquak** [comment]
Naar tevredenheid afgesloten.
