### ISSUE TITLE
Regels verschijnen niet meer in Respec doc na laatste nightly build

### ISSUE THREAD

**Issue by PB-GNM** [Imvertor/Imvertor-Maven#382]
Het blijkt dat ergens tussen versie 1.67 en de nightly build de regels (vanuit de toelichting) niet meer doorkomen.

Vergelijk:
https://geonovum.github.io/imev-werkomgeving/IMEV_WV_2.0_05102023_imvertor_1.67.html#global_class_IMEVbasis_LocatieActiviteit 
en
https://geonovum.github.io/imev-werkomgeving/IMEV_WV_2.0_28092023_imvertor_nightlybuilt.html#global_class_IMEVbasis_LocatieActiviteit 

In EA is het als volgt aangegeven:
![image](https://github.com/Imvertor/Imvertor-Maven/assets/80040145/4e48867f-c9aa-4789-afa9-bdf054669929)

mvgr,
Pieter Bresters

**Comment by ArjanLoeffen** [comment]
Gecorrigeerd. 

Morgen beschikbaar in Nightly build 11.

**Comment by PB-GNM** [comment]
Het is opgelost:
zie https://geonovum.github.io/imev-werkomgeving/#global_class_IMEVbasis_LocatieActiviteit
Bedankt voor de snelle oplossing.
