### ISSUE TITLE
Element img wordt niet meer binnen element figure genest

### ISSUE THREAD

**Issue by gwolbers** [Imvertor/Imvertor-Maven#383]
In eerdere versies werden png-plaatjes uit uml geplaatst als element `img` binnen een parent-element `figure`. Dit is niet meer het geval. Twee consequenties:

- De selector `figure img` uit base.css wordt niet meer gebruikt, waardoor de stijl `max-width: 100%` wordt toegepast. Bij grotere afbeeldingen gaat het daardoor mis met gebruikte maps.
- Het bijschrift `caption` wordt niet meer weergegeven.

**OUD**
![image (1)](https://github.com/Imvertor/Imvertor-Maven/assets/45358623/800132aa-ff6c-4b4a-aa93-b2fe74868a64)

**NIEUW**
![image](https://github.com/Imvertor/Imvertor-Maven/assets/45358623/64d05b47-5c8b-4006-b557-930a7b5e7e20)

**Comment by ArjanLoeffen** [comment]
Dit is onderdeel van Development (nightly build) en niet van FB-336. Welke heb je gebruikt?

`<figure>` is wel d "wrapper" voor Geonovum plaatjes in Development.

**Comment by gwolbers** [comment]
Hallo Arjan,

Het gaat om deze versie:

https://geonovum.github.io/imev-werkomgeving/IMEV_WV_2.0_05102023_imvertor_1.67.html
Informatiemodel Externe Veiligheid (IMEV) versie 2.0<https://geonovum.github.io/imev-werkomgeving/IMEV_WV_2.0_05102023_imvertor_1.67.html>
Dit document bevat het informatiemodel ten behoeve van gegevenslevering en gegevensontsluiting voor het Register Externe Veiligheidsrisico's (REV), het Informatiemodel Externe Veiligheid (IMEV). Het informatiemodel IMEV beschrijft de gegevensstructuur en objectdefinities van gegevens in het REV. De bronphouders die data aanleveren aan het REV gebruiken het IMEV voor het inrichten van hun gegevenshuishouding en aanlevern van data aan het REV. Op basis van het informatiemodel kan een eindgebruiker zich een goed beeld vormen van de data die door het REV worden aangeboden en de data inhoudelijk interpreteren. Daarnaast geldt dat onderdelen van het informatiemodel nodig zijn ten behoeve van applicatiebouw voor inrichten van datakopplingen met het REV.
geonovum.github.io

Overigens heeft Pieter hiervoor in style.css regel 16 de max-width op none gezet.


Met vriendelijke groet,



Gerard Wolbers

______________________________________

Geonovum

Senior beheerder geo-informatiestandaarden



a: Barchman Wuytierslaan 10, 3818 LH Amersfoort

p: Postbus 508, 3800 AM Amersfoort

m:+ 31 (0)6 54955047 (direct)

t:+ 31 (0)33 4604100 (algemeen)

e: ***@***.******@***.***>

i: www.geonovum.nl<http://www.geonovum.nl>



________________________________
Van: Arjan Loeffen ***@***.***>
Verzonden: dinsdag 10 oktober 2023 14:09
Aan: Imvertor/Imvertor-Maven ***@***.***>
CC: Gerard Wolbers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Imvertor/Imvertor-Maven] Element img wordt niet meer binnen element figure genest (Issue #383)


Dit is onderdeel van Development (nightly build) en niet van FB-336. Welke heb je gebruikt?

<figure> is wel d "wrapper" voor Geonovum plaatjes in Development.

**Comment by ArjanLoeffen** [comment]
Mijn vraag was: gebruik je de nightly build?
Het element <figure> is geintroduceerd in Development/nightly build dus is geen onderdeel van 1.67.

**Comment by PB-GNM** [comment]
De filenaam geeft aan met welke versie van Imvertor het gedraaid is.
dus 1e  plaatje van Gerard met: <https://geonovum.github.io/imev-werkomgeving/IMEV_WV_2.0_28092023_imvertor_nightlybuilt.html>
en 2 plaatje van Gerard met: <https://geonovum.github.io/imev-werkomgeving/IMEV_WV_2.0_05102023_imvertor_1.67.html>

Alleen het bovenschrift moet andersom. Dus wat oud is moet nieuw zijn en wat nieuw is moet oud zijn, want de nightly build is natuurlijk de nieuwe.

**Comment by ArjanLoeffen** [comment]
Dus als je nu voor Geonovum de IMEV draait met de nightly build komt `<figure>` niet door?
Heb je een jobnummer voor me?

**Comment by ArjanLoeffen** [comment]
Ik zit even te kijken naar je laatste run resultaat:
https://geonovum.github.io/imev-werkomgeving/#EAID_E73201ED_403D_4639_AE7B_84FAFA24072F
Dat lijkt gewoon okay toch?

**Comment by gwolbers** [comment]
Arjan, die zijn met de oude versie gedraaid. Ik zet trouwens Pieter in cc, want hij heeft ze gemaakt.


Met vriendelijke groet,



Gerard Wolbers

______________________________________

Geonovum

Senior beheerder geo-informatiestandaarden



a: Barchman Wuytierslaan 10, 3818 LH Amersfoort

p: Postbus 508, 3800 AM Amersfoort

m:+ 31 (0)6 54955047 (direct)

t:+ 31 (0)33 4604100 (algemeen)

e: ***@***.******@***.***>

i: www.geonovum.nl<http://www.geonovum.nl>



________________________________
Van: Arjan Loeffen ***@***.***>
Verzonden: donderdag 12 oktober 2023 10:56
Aan: Imvertor/Imvertor-Maven ***@***.***>
CC: Gerard Wolbers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Imvertor/Imvertor-Maven] Element img wordt niet meer binnen element figure genest (Issue #383)


Ik zit even te kijken naar je laatste run resultaat:
https://geonovum.github.io/imev-werkomgeving/#EAID_E73201ED_403D_4639_AE7B_84FAFA24072F
Dat lijkt gewoon okay toch?

**Comment by PB-GNM** [comment]
Nee, die is met de nieuwe nightly build versie gedraaid, maar in https://github.com/Geonovum/imev-werkomgeving/blob/main/data/imev-werkomgeving-cat.respec.html later handmatig aangepast door bij elk img element ' **style="max-width: none;"**  ' op te nemen.

**Comment by ArjanLoeffen** [comment]
NB deze job: 
https://imvertor.armatiek.nl/imvertor-executor/dashboard/app?subpath=MIMLM%2FIMEV-conceptueel%2F20221221&job=2023-10-11-10-29-22-173
Dit het gewoon goed, met de figure elementjes gewoon aan boord. Het is gemaakt met de Nightly build.

**Comment by gwolbers** [comment]
Arjan, wil je dit met Pieter afhandelen? Hij heeft de versies gemaakt.


Met vriendelijke groet,



Gerard Wolbers

______________________________________

Geonovum

Senior beheerder geo-informatiestandaarden



a: Barchman Wuytierslaan 10, 3818 LH Amersfoort

p: Postbus 508, 3800 AM Amersfoort

m:+ 31 (0)6 54955047 (direct)

t:+ 31 (0)33 4604100 (algemeen)

e: ***@***.******@***.***>

i: www.geonovum.nl<http://www.geonovum.nl>



________________________________
Van: Arjan Loeffen ***@***.***>
Verzonden: donderdag 12 oktober 2023 11:08
Aan: Imvertor/Imvertor-Maven ***@***.***>
CC: Gerard Wolbers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Imvertor/Imvertor-Maven] Element img wordt niet meer binnen element figure genest (Issue #383)


NB deze job:
https://imvertor.armatiek.nl/imvertor-executor/dashboard/app?subpath=MIMLM%2FIMEV-conceptueel%2F20221221&job=2023-10-11-10-29-22-173
Dit het gewoon goed, met de figure elementjes gewoon aan boord. Het is gemaakt met de Nightly build.

**Comment by PB-GNM** [comment]
Maar vroeger zaten die figure elementjes er kennelijk juist niet in. Ik vermoed dat Gerard dacht dat dit verschil de oorzaak is dat plaatjes geschaald worden terwijl we dat niet willen.

Hieronder een afbeelding hoe ik dat schaal probleem nu heb opgelost in :https://github.com/Geonovum/imev-werkomgeving/blob/main/data/imev-werkomgeving-cat.respec.html 

![image](https://github.com/Imvertor/Imvertor-Maven/assets/80040145/d20375bc-6b19-480b-bd3e-e6ff62911ebf)

**Comment by ArjanLoeffen** [comment]
Dat is een heel ander issue, het heeft wrsch niks met `<figure>` te maken.

Als je wilt dat plaatjes goed geschaald worden moet je dat op een andere manier oplossen. Ik kan me voorstellen dat Respec daar zelf opties voor heeft. Hoe dan ook, het verwijderen van de maximum breedte van een plaatje moet je via CSS regelen, vind ik, niet via style= attribuut. 
Geonovum heeft zijn eigen CSS (en Respec omgeving), dus is het geen Imvertor issue.

**Comment by PB-GNM** [comment]
Als het onderliggende probleem niks met figure te maken heeft zou ik dit issue sluiten. Zeker omdat het heel verwarrend is geworden doordat de oude en nieuwe situatie in de oorspronkelijke melding verwisseld zijn.

**Comment by gwolbers** [comment]
Klopt. Zolang de laatste versie het figuurbijschrift maar doorgeeft en de 'max-width: none' zet.


Met vriendelijke groet,



Gerard Wolbers

______________________________________

Geonovum

Senior beheerder geo-informatiestandaarden



a: Barchman Wuytierslaan 10, 3818 LH Amersfoort

p: Postbus 508, 3800 AM Amersfoort

m:+ 31 (0)6 54955047 (direct)

t:+ 31 (0)33 4604100 (algemeen)

e: ***@***.******@***.***>

i: www.geonovum.nl<http://www.geonovum.nl>



________________________________
Van: Pieter Bresters ***@***.***>
Verzonden: donderdag 12 oktober 2023 11:30
Aan: Imvertor/Imvertor-Maven ***@***.***>
CC: Gerard Wolbers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Imvertor/Imvertor-Maven] Element img wordt niet meer binnen element figure genest (Issue #383)


Als het onderliggende probleem niks met figure te maken heeft zou ik dit issue sluiten. Zeker omdat het heel verwarrend is geworden doordat de oude en nieuwe situatie in de oorspronkelijke melding verwisseld zijn.

**Comment by ArjanLoeffen** [comment]
Imvertor zet die `max-width: none` niet. Omdat we er vanuit gaan dat het in CSS wordt geregeld. bijv:

```css
figure img {
  max-width: none;
}
```

**Comment by gwolbers** [comment]
Dit zou inderdaad voor de nightly-build het probleem oplossen.


Met vriendelijke groet,



Gerard Wolbers

______________________________________

Geonovum

Senior beheerder geo-informatiestandaarden



a: Barchman Wuytierslaan 10, 3818 LH Amersfoort

p: Postbus 508, 3800 AM Amersfoort

m:+ 31 (0)6 54955047 (direct)

t:+ 31 (0)33 4604100 (algemeen)

e: ***@***.******@***.***>

i: www.geonovum.nl<http://www.geonovum.nl>



________________________________
Van: Arjan Loeffen ***@***.***>
Verzonden: donderdag 12 oktober 2023 11:43
Aan: Imvertor/Imvertor-Maven ***@***.***>
CC: Gerard Wolbers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Imvertor/Imvertor-Maven] Element img wordt niet meer binnen element figure genest (Issue #383)


Imvertor zet die max-width: none niet. Omdat we er vanuit gaan dat het in CSS wordt geregeld. bijv:

figure img {
  max-width: none;
}

**Comment by wilkoquak** [comment]
Om de  schaling van de UML diagrammen die uit Imvertor komen te kunnen aanpassen in de css is het handig als die duidelijk herkenbaar zijn. Voorstel hiervoor is om aan deze plaatjes een class="EAdiagram" op <figure> zetten. Is dat haalbaar?

**Comment by ArjanLoeffen** [comment]
Een `<figure>` valt binnen een `<div class="imageinfo">`. In CSS kun je dus gewoon

```css
.imageinfo figure {
 /* wat je wilt aanpassen komt hier*/
}
```

gebruiken. Als het een overview plaatje is wordt er een class "overview" toegevoegd:

```css
.imageinfo.overview figure {
 /* wat je wilt aanpassen komt hier*/
}
```

**Comment by ArjanLoeffen** [comment]
@gwolbers Deze vraag heeft betrekking op de SaaS omgeving van Armatiek Solutions. Dus verkeerde platform voor dit verzoek, omdat PNG niet automatisch naar SVG om te zetten is (dus Imvertor OS kan er niks mee).

De PNG bestanden worden door EA gegenereerd. Ze zijn niet beschikbaar in SVG en zover ik weet is het ook niet mogelijk om EA SVG te laten leveren. Er is wel een add-in maar die heeft beperkingen en het is de vraag of we die kunnen aanspreken vanuit onze Armatiek add-in. Het is trouwens ook weer 'een extra add-in' die je moet uitrollen op de werkplekken...

**Comment by gwolbers** [comment]
Hallo Arjan,

Dank voor het uitzoeken. Ik ga me verdiepen in de add-in van EA.


Met vriendelijke groet,



Gerard Wolbers

______________________________________

Geonovum

Senior beheerder geo-informatiestandaarden



a: Barchman Wuytierslaan 10, 3818 LH Amersfoort

p: Postbus 508, 3800 AM Amersfoort

m:+ 31 (0)6 54955047 (direct)

t:+ 31 (0)33 4604100 (algemeen)

e: ***@***.******@***.***>

i: www.geonovum.nl<http://www.geonovum.nl>



________________________________
Van: Arjan Loeffen ***@***.***>
Verzonden: donderdag 2 november 2023 11:48
Aan: Imvertor/Imvertor-Maven ***@***.***>
CC: Gerard Wolbers ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Imvertor/Imvertor-Maven] Element img wordt niet meer binnen element figure genest (Issue #383)


@gwolbers<https://github.com/gwolbers> Deze vraag heeft betrekking op de SaaS omgeving van Armatiek Solutions. Dus verkeerde platform voor dit verzoek, omdat PNG niet automatisch naar SVG om te zetten is (dus Imvertor OS kan er niks mee).

De PNG bestanden worden door EA gegenereerd. Ze zijn niet beschikbaar in SVG en zover ik weet is het ook niet mogelijk om EA SVG te laten leveren. Er is wel een add-in maar die heeft beperkingen en het is de vraag of we die kunnen aanspreken vanuit onze Armatiek add-in. Het is trouwens ook weer 'een extra add-in' die je moet uitrollen op de werkplekken...

**Comment by ArjanLoeffen** [comment]
[Add-in info is hier](https://community.sparxsystems.com/community-resources/706-svg-diagram-export-add-in#:~:text=Start%20Enterprise%20Architect%20and%20open,location%20for%20the%20SVG%20file.).

**Comment by gwolbers** [comment]
Dank je.


Met vriendelijke groet,



Gerard Wolbers

______________________________________

Geonovum

Senior beheerder geo-informatiestandaarden



a: Barchman Wuytierslaan 10, 3818 LH Amersfoort

p: Postbus 508, 3800 AM Amersfoort

m:+ 31 (0)6 54955047 (direct)

t:+ 31 (0)33 4604100 (algemeen)

e: ***@***.******@***.***>

i: www.geonovum.nl<http://www.geonovum.nl>



________________________________
Van: Arjan Loeffen ***@***.***>
Verzonden: donderdag 2 november 2023 11:57
Aan: Imvertor/Imvertor-Maven ***@***.***>
CC: Gerard Wolbers ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Imvertor/Imvertor-Maven] Element img wordt niet meer binnen element figure genest (Issue #383)


Add-in info is hier<https://community.sparxsystems.com/community-resources/706-svg-diagram-export-add-in#:~:text=Start%20Enterprise%20Architect%20and%20open,location%20for%20the%20SVG%20file.>.
