### ISSUE TITLE
IHW: URL-prefix https://aquo.nl/index.php/ voor "herkomst" plaatsen

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#384]
Vraag: in de TV Herkomst zetten we de GUID van onze begripsdefinitie. Hoe ingewikkeld is het om daar de URL-prefix https://aquo.nl/index.php/ voor te zetten, zodat we vanuit de catalogus direct door kunnen linken naar de AQUO-wiki?

**Comment by WijnandIHW** [comment]
Ziet er goed uit. Kan afgesloten worden
