### ISSUE TITLE
BRO: in XSD ontbreekt 'nillable = true' bij tag 'Voidable' = 'Yes' in logisch model

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#388]
In ons logisch model van EPC heeft het attribuut 'owner' van de entiteit AbstractMiningConstruction de tag 'Voidable' met als tagwaarde = 'Yes'. Op grond daarvan verwachten we in de XSD bij dit attribuut 'nillable = true'.

Dat is echter niet het geval. Zowel niet in Imvertor 1.67.1 als in Nighly build versie 11.

**Comment by ArjanLoeffen** [comment]
Zou je die job nog eens willen draaien met de volgende properties:

```
debug                   = yes
debugmode               = ISOS

```
En het jobnummer daarvan willen doorgeven?

**Comment by jacobvosimpronotion** [comment]
@ArjanLoeffen: zie job 2023-10-23-12-27-15-919.

**Comment by ArjanLoeffen** [comment]
Ik zie dat de Organisatie (type van owner) niet wordt herkend als een extern type. Ik kan niet bepalen waarom dat gebeurt; ik heb alleen de XMI en dat is niet voldoende; inladen in een eerdere versie van jullie EA infrastructuur (projecten en domeinen) levert fouten op.  Heb je de hele QEA file voor me, zodat ik e.e.a. kan testen?

Ik zou geholpen zijn met een complete QEA dus alle registratieobjecten, alle externe modellen zoals geostandaarden, MIM, etc,. (en dus ook daartussen het EPC).

**Comment by ArjanLoeffen** [comment]
Han Welmer heeft inmiddels een testbestand gestuurd.
Ik draait hem nu met de nightly build en zie:

```
<!--epccom::AbstractMiningConstruction.someNillableOrganization (attrib) = eigenaar - An attribute or association-->
               <xs:element name="someNillableOrganization"
                           minOccurs="1"
                           maxOccurs="1"
                           nillable="true"><!--epccom::AbstractMiningConstruction.someNillableOrganization (attrib) = eigenaar - The type of this property is a union, and voidable-->
                  <xs:annotation>
                     <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">....</xs:documentation>
                  </xs:annotation>
                  <xs:complexType>
                     <xs:complexContent>
                        <xs:extension base="brocom:OrganizationPropertyType">
                           <xs:attribute name="nilReason" type="xs:string" use="optional"/>
                        </xs:extension>
                     </xs:complexContent>
                  </xs:complexType>
               </xs:element>
```

Dit is toch correct?
Was voorheen (in het andere EA bestand) Organisation een Union?

**Comment by ArjanLoeffen** [comment]
Aha, ik zie dat je nu een ander model hebt gestuurd. Het WAS:

![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/a7584264-461f-40b8-b08f-7321add34ef3)

het is in jouw laatste testversie:

![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/9b4c330f-6a6a-4107-bbc8-f729347b85e3)

Dat is nogal een verschil... :-)

**Comment by ArjanLoeffen** [comment]
Als ik de situatie waar jullie een probleem mee hadden simuleer door **brocom** even buiten het model te plaatsen krijg ik de melding dat **Organisation** niet bekend is (niet terugkeert in conceptual schemas). Het lijkt erop dat jullie EAP bestand wat reden tot het GIThub issue is geweest niet zo in elkaar zit. Misschien beter om het even interactief te bekijken.

**Comment by HanWelmer** [comment]
Hallo Arjan. Ik ben vandaag (vrijdag 27-10-2023) tot 09:00 en van 11:00 tot 16:00 beschikbaar.

**Comment by HanWelmer** [comment]
Problem solved in Nightly build.

Output from version 1.67 (with error):
               <xs:element name="owner"
                           minOccurs="1"
                           maxOccurs="1"
                           type="bro:OrganizationType">
                  <xs:annotation>


Output from Nightly build (as expected):
               <xs:element name="owner"
                           minOccurs="1"
                           maxOccurs="1"
                           type="bro:OrganizationType"
                           nillable="true">
                  <xs:annotation>
