### ISSUE TITLE
tv location on Referencelist must be required

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#39]

**Comment by ArjanLoeffen** [comment]
Dit loopt gelijk op met https://github.com/Geonovum/MIM-Metamodel-Informatiemodelleren/issues/35
Eigenlijk moet er een regel komen die valideert of een locatie van een codelist (in een bepaalde context, nl. als toegekend als type van een attribuut) kan worden vastgesteld. Dit is dus een validatieregel.

**Comment by ThiesMesdag** [comment]
Zie ook https://github.com/Geonovum/MIM-Werkomgeving/issues/24.
Ik denk dat de algemene validatieregel is dat als er een url is opgenomen (in definitie, of toelichting, of locatie) dat er een warning is al die niet aankomt. Waarschijnlijk is het echter alleen mogelijk om bij de locatie te checken dat het een url is en daarna dat hij ook aankomt.
