### ISSUE TITLE
Compare functioneert niet

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#390]
Ik wil twee releases van hetzelfde model met elkaar vergelijken maar de optie 'Release comparison' wordt niet in het report gegenereerd. In mijn lokale properties bestand geef ik het volgende op:

```
compare = release
comparewith = 20210826
comparemethod = xmldiff
```
Job-id is 2023-10-23-14-12-00-486.

Ik heb het ook lokaal in eclipse geprobeerd (ook zonder de property 'comparemethod ') maar ook daar wordt de gewenste optie niet gegenereerd. In de logging kom ik ook geen logging m.b.t. de step 'ReleaseComparer' tegen.

**Comment by ArjanLoeffen** [comment]
Aftasten van `cli/compare` parameter ging verkeerd. Ik herstel dit in FB-336 om merge conflicten te vermijden.
Wordt vrijdag gemerged met Development.

**Comment by ArjanLoeffen** [comment]
De compare functie werkt alleen met parameter
`comparemethod = default`
omdat de parameter
`comparemethod = xmldiff`
niet meer wordt ondersteund. Dit was een server applicatie die Armatiek heeft opgezet maar die is gediscontinueerd.
Ook werkt compare op een verouderde normalisatieslag (`model.imvert`).

Het is raadzaam te overwegen e.e.a. te gaan baseren op MIM serialisatie of een andere normalisatieslag uit te voeren op `system.imvert`.

**Comment by melsk-r** [comment]
Wil je met die laatste opmerking zeggen dat de compare niet werkt op een SIM die aan het MIM voldoet?

**Comment by ArjanLoeffen** [comment]
De conversie naar model.imvert is niet geheel dekkend. Daardoor is de compare ook niet dekkend. De compare (`default`) werkt wel om alle modellen van alle metamodellen.

**Comment by melsk-r** [comment]
Wellicht wordt dat vrijdag opgelost maar ik krijg nu de volgende foutmeldingen:

```
Error near {...th-to-file-uri($ctrl-filepa...} at char 0 in xsl:variable/@select on line 45 column 82 of Imvert2compare-listing.xsl:
  XPST0017  Cannot find a 1-argument function named
  Q{http://www.imvertor.org/xsl/functions}path-to-file-uri()
Error near {...th-to-file-uri($test-filepa...} at char 0 in xsl:variable/@select on line 46 column 82 of Imvert2compare-listing.xsl:
  XPST0017  Cannot find a 1-argument function named
  Q{http://www.imvertor.org/xsl/functions}path-to-file-uri()
```
Op regel 45 van Imvert2compare-listing.xsl staat

`http://www.imvertor.org/imvertor/1.0/xslt/compare/compare-generated.xsl`

maar dat bestand bestaat blijkbaar helemaal niet.

**Comment by ArjanLoeffen** [comment]
Zit je in FB-336? Want dat moet.

**Comment by melsk-r** [comment]
Het probleem lijkt hem niet in het afwezig zijn van 'compare-generated.xsl' te zitten.
Het is de functie 'imf:path-to-file-uri' die niet gevonden wordt. Die begrijp ik echter niet want in het stylesheet 'common/Imvert-common.xsl' is die functie wel aanwezig en dat stylesheet wordt geïmporteerd.

**Comment by melsk-r** [comment]
> Zit je in FB-336? Want dat moet.

Ja, daarin heb ik lokaal de wijzigingen die je hebt aangegeven doorgevoerd.

**Comment by ArjanLoeffen** [comment]
Ik heb hem toegevoegd aan de Imvert2compare-listing.xsl. Ik krijg in FB0-336 die melding niet meer.

**Comment by melsk-r** [comment]
Zou de compare functie nu ook moeten werken in de 3.0 versie?

**Comment by melsk-r** [comment]
De compare functie werkt inmiddels in versie 3.0. Ik sluit dit issue.
