### ISSUE TITLE
BRO: Tag 'Toelichting' bij element van stereotype 'Keuze' niet in catalogus getoond

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#392]
In het GMW model hebben we een element van het stereotype 'Keuze'. In het Enterprise Architect notes veld staan een Definitie (middels --Definitie--) en een Toelichting (middels --Toelichting--).

In de ReSpec catalogus wordt wel de Definitie opgenomen, maar niet de Toelichting.

S.v.p. realiseren dat ook de Toelichting wordt getoond.

N.B.: Is dit iets dat binnen https://github.com/Imvertor/Imvertor-Maven/tree/master/src/main/resources/input/BRO wordt geconfigureerd?

**Comment by jacobvosimpronotion** [comment]
@ArjanLoeffen: Ik zie je dat je dit geclassificeerd hebt als een verbetering. Wij ervaren het als een bug.

**Comment by jacobvosimpronotion** [comment]
@ArjanLoeffen: Kan dit binnen een 2-3 weken beschikbaar zijn?

**Comment by ArjanLoeffen** [comment]
@jacobvosimpronotion Je kunt zelf het label naar Bug veranderen. Ik doe dat nu voor jullie.
Ik zal er vandaag naar kijken.

**Comment by ArjanLoeffen** [comment]
De documentatie regels staan in
`/Imvertor-Chains/src/main/resources/input/BRO/cfg/docrules/BRO-CONCEPTUAL.xml`
hetgeen verwijst naar
`/Imvertor-Chains/src/main/resources/input/BRO/cfg/docrules/BRO.xml`
De regels voor logische modellen zijn identiek.

Naast deze regels is een stylesheet opgenomen die specifieke aanpassingen tbv. BRO doet. Hierin wijkt BRO dus af van de regels van de samenstelling van documentatie.
In dit stylesheet is op een beperkt aantal plaatsen opgenomen dat een toelichting moet worden weergegeven. Ik heb de toelichting nu geplaatst op alle plekken waar een definitie wordt getoond. Echter, er is meer aan de hand en dat vereist overleg. Bijvoorbeeld, als de definitie is opgenomen, moet dan ook de herkomst van de definitie worden getoond?
Ik doe hierover geen verdere aannames.

**Comment by ArjanLoeffen** [comment]
Morgen beschikbaar in Nightly-build
