### ISSUE TITLE
PropertyType mapping in xsd bevat onverwachte minOccurs=0

### ISSUE THREAD

**Issue by wilkoquak** [Imvertor/Imvertor-Maven#393]
Bij het vertalen van UML naar XML-schema wordt voor ieder `<<objecttype>>` en `<<Gestructureerd datatype>>` een constructie gemaakt met aan de naam van de klasse PropertyType toegevoegd. Bijvoorbeeld bij data type NEN3610ID wordt het volgende PropertyType gemaakt
```
<xs:complexType name="NEN3610IDPropertyType">
   <xs:sequence minOccurs="0">
         <xs:element ref="img:NEN3610ID"/>
   </xs:sequence>
</xsd:complexType>
```

De vraag is nu: waarom staat die minOccurs=0 daar. Deze maakt het in de uitwisseling mogelijk om objecten met deze property uit te wisselen waar de property geen waarde heeft. Op bladzijde 345 van de GML3.2.1 standaard die de UML naar XSD mapping vastlegt staat deze minOccurs ook niet:
![afbeelding](https://github.com/Imvertor/Imvertor-Maven/assets/2814052/7d354aa1-9ceb-4fb9-8d7f-2fe79f86f860)

**Comment by ArjanLoeffen** [comment]
Je bedoelt dat we 'm daar weg moeten halen?

**Comment by wilkoquak** [comment]
Volgens mij is het een bug die er al heel lang inzit waardoor er door de jaren heen veel schemas zijn gepubliceerd die niet kloppen. Ik wil dit dus niet overhaasten en ben benieuwd naar de volgende punten:
- Is Annex-E van de GML standaard inderdaad de specificatie van de mapping van UML naar XSD?
- Zijn er nog anderen die deze mapping gebruiken en kunnen bevestigen dat het hier om een bug gaat?

**Comment by wilkoquak** [comment]
Als ik de GML mapping rules nog eens goed doorlees is die minOccurs=0 bedoeld voor het als je het betreffende element byReference opneemt.  In dat geval moet je in de uitwisseling een xlink naar het betreffende object opnemen en dus geen element met de betreffende waarde.  Of die minOccurs=0 er moet staan is dus afhankelijk van de waarde van inlineOrByReference. In het geval van IMGeluid heeft die altijd de waarde 'inline' en moet de minOccurs dus weg.

Ik zie in de mapping regels dat je in dat geval de property ook `ParcelNamePropertyByValueType` moet noemen en dat dat ook weer gestuurd wordt door de tagged value `byValuePropertyType=true` uit de GML specificatie. 

Volgens mij kent MIM dit tagged value ook niet. Er is in ieder geval meer aan de hand dan het weghalen van de minOccurs. In mijn volgende comment (en dat lukt niet meer vanavond) ga ik specificeren wat er volgens mij moet gebeuren.

**Comment by ArjanLoeffen** [comment]
@wilkoquak In het kader van de Json schema best practices (#336 ) is er een tagged value opgenomen met als (voorlopige) naam  InlineOrByReference. Die lijkt precies daarvoor bedoeld, maar dan voor de Json wereld. Misschien goed om dat mee te nemen; vraag @PalmJanssen .

**Comment by wilkoquak** [comment]
De GML standaard heeft inderdaad een InlineOrByReference tagged value. De betekenis hiervan is ook vastgelegd in de GML standaard.  Deze tagged value en dus ook de tagged value `byValuePropertyType` zouden dus geïmplementeerd moeten worden in Imvertor. Daarnaast is een command-line switch om een default waarde te kunnen vaststellen ook wenselijk.

**Comment by PalmJanssen** [comment]
Nog als achtergrond. Inderdaad heeft GML die InlineOrByReference UML-GML sturing. Default is die inline bij attributen en byReference bij relaties. We hadden tot nu toe voor GML (dacht ik) voldoende aan die default dus we specificeerden niets. Bij JSON is de default niet genoeg. Maar dus nu ook niet bij GML (en XML) naar ik begrijp

**Comment by HanWelmer** [comment]
Twee citaten uit de GML 3.2.1 specificaties.

**Appendix E.2.4.1**
Table E.2 — Tagged values

Attribute and association end:
 documentation
 sequenceNumber
 inlineOrByReference
 isMetadata

**Appendix E.2.4.11**

If the type of the value of the property is of complex content, then a property type shall be used. The default encoding of the property type allows both the inline or by-reference representation for feature and object types and the inline representation for data and union types. For feature and object types the representation may be restricted to inline or by-reference using a tagged value "inlineOrByReference" with the values "inline" or "byReference" respectively. If the tagged value is missing or its value is "inlineOrByReference" the default encoding shall be used.

EXAMPLE 3 By-reference or inline:
```
<complexType name="PersonPropertyType">
    <sequence minOccurs="0">
        <element ref="ex:Person"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup" />
</complexType>
```

**Comment by HanWelmer** [comment]
Met andere woorden:

- Volgens mij moeten we de XSD generatie niet hard gecodeerd aanpassen door minOccurs="0" weg te laten uit bovenstaande voorbeeld van Wilko van 3 weken geleden.
- Volgens mij moeten we bij afwezigheid van een sturende tagged value (op te voeren per target end van een associatie relatie naar een ObjectType) XSD code generen conform E.2.4.11 (example 3), dus zowel de optie bieden voor inline als by reference. En dus zowel een element met minOccurs="0" (optie voor inline opnemen) als een AssociationAttributeGroup (optie voor by reference). Rationale: volg de standaard en als iemand hiervan wil afwijken is het betrouwbaarder om overbodige code te verwijderen dan omgekeerd ontbrekende code toe te voegen.
- Volgens mij moeten we overwegen om bovenstaande tagged value toe te voegen aan MIM/Imvertor. Details hoe dat eruit moet komen te zien kunnen we dan bespreken (optionele waarde uit een 3-waardige keuze lijst ("alleen in-line", "alleen by-reference", "beiden") waarbij de waarde "beiden" hetzelfde effect heeft als geen waarde.

**Comment by wilkoquak** [comment]
Han, dank voor je reactie. Ik ben het ermee eens om GML Annex-E als uitgangspunt te nemen en Imvertor te vragen het zo te implementeren. Of we dan nog keuze overhebben zoals je hierboven beschrijft. Ik zal mijn best doen in dit issue met een correcte specificatie te komen.

**Comment by wilkoquak** [comment]
Ik zit hier al een tijdje op te puzzelen en momenteel gaat het echt mis bij klasses met het stereotype `<<Gestructureerd datatype>>`.  Dit MIM stereotype komt min of meer overeen met `<<DataType>>` in GML waarbij staat dat bijvoorbeeld voor de type Parcel het volgend propertytype moet worden gemaakt:

```
<complexType name="ParcelNamePropertyType">
    <sequence>
        <element ref="ex:ParcelName"/>
    </sequence> 
    <attributeGroup ref="gml:OwnershipAttributeGroup" />
</complexType>
```
Terwijl Imvertor het volgende aanmaakt:

```
<xs:complexType name="ParcelNamePropertyType">
    <xs:sequence minOccurs="0">
         <xs:element ref="img:ParcelName"/>                                                                                                 
    </xs:sequence> 
</xs:complexType>
```

De minOccurs die hierin staat klopt zeker niet en moet verwijderd worden. Dat is wat mij betreft echt een bug.

**Comment by wilkoquak** [comment]
Dit issue is een combinatie van een feature request en een bug. De bug zit nu los in #552 . De feature request ga ik sluiten.
