### ISSUE TITLE
Error imf:get-choice-of-datatypes 

### ISSUE THREAD

**Issue by ThiesMesdag** [Imvertor/Imvertor-Maven#411]
Hoi Arjan,  
Ik krijg een error op Job nr **2023-11-13-11-55-43-405** met als tekst:
Step-Level system error: tranformation causes fatal error: an empty sequence is not allowed as first argument of imf:get-choice-of-datatypes() 

Het uitzetten van de Json generator _createjsonschema=no_ in de properties file loste het probleem idd op.

**Comment by ArjanLoeffen** [comment]
Het is dus een fout in de Json schema compiler. Dat is work in progress; de eerste grote testgevallen zijn erdoorheen gekomen maar zoals je ziet: er is altijd wel een situatie die we niet hadden voorzien :-)

Ik ga kijken.

**Comment by ArjanLoeffen** [comment]
Aha, ik zie het. Voor Kadaster is Jon schema configuratie helemaal niet gezet. Feitelijk moet er een test worden gedaan of de "requirements" uit de specificatie überhaupt zijn vastgelegd in een Schema rules file.

Ik zal dat toevoegen.
