### ISSUE TITLE
BRO: in Respec catalogus tonen van diagram bij elementen met stereotype 'Keuze'

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#418]
In een Respec catalogus wordt er geen diagram getoond als het betreffend element een `<<Keuze>>` is. Zie bijv. https://broprogramma.github.io/GMW/#global_class_Model_Verkenning. Het betreffende diagram is opgenomen in het EA package, met als naam 'Verkenning - detail' (dus dat is OK).

Graag het diagram tonen zoals ook voor elementen met het stereotype `<<Objecttype>>`.

**Comment by ArjanLoeffen** [comment]
Gecorrigeerd in development/nightly build. Morgen beschikbaar.

**Comment by jacobvosimpronotion** [comment]
Getest en het werkt. Dank!
