### ISSUE TITLE
BRO: Diagrammen in catalogi zijn niet meer klikbaar

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#420]
Als in een catalogus op een diagram wordt geklikt, dan wordt er niet gesprongen naar de paragraaf van de entiteit waarop is geklikt. Het is ons niet duidelijk sinds welke versie / nightly build van Imvertor deze fout optreedt.

Voorbeeld van niet goed functionerende catalogus: https://broprogramma.github.io/SLD/#het-domeinmodel.

Voorbeeld van wel goed functionerende catalogus: https://broprogramma.github.io/EPL/#het-domeinmodel.

**Comment by ArjanLoeffen** [comment]
De `<img>` in de `<figure>` heeft een CSS:  `max-width: 100%;`
Dat lijkt de reden van het probleem. Het activeren van een deel van het image is gebaseerd op pixelpositie, en die wordt aangepast door het feitelijk verkleinen van de image.
De CSS moet dus worden aangepast. Of er moet een methode worden bedacht waarmee de _area_ berekening rekening houdt met de werkelijke (visuele) grootte van het plaatje.

**Comment by jacobvosimpronotion** [comment]
Wat is je voorstel?

Overigens is max-width bij beide gerefereerde diagrammen de waarde 100%.

**Comment by ArjanLoeffen** [comment]
Ik  vermoed dat bij  https://broprogramma.github.io/SLD/#het-domeinmodel. de figuren feitelijk "uit de 100% lopen". Ik denk dus dat we een extra CSS regel moeten toevoegen:

```css
.imageinfo img {
  max-width: none;
}
```

met het nadeel dat de figuur uit het scherm kan gaan lopen.

**Comment by jacobvosimpronotion** [comment]
Ja, ik zag het al: het diagram waarin het klikken werkt, nl. https://broprogramma.github.io/EPL/#het-domeinmodel. is bij 100% weergave precies zo groot als het origineel.

Maar inderdaad: als je die 100% weghaalt, dan gaan diagrammen idd uit het scherm lopen.

Ik vond dit: https://stackoverflow.com/questions/9103123/image-map-with-image-size-100.

**Comment by ArjanLoeffen** [comment]
Mooie uitdaging voor jou? :-)

**Comment by jacobvosimpronotion** [comment]
Eh, nee...

Er zijn echter ook voorbeelden, bijv. https://broprogramma.github.io/GMW/#global_class_Model_Monitoringbuis, dat het disablen van max-width niets oplost. Dus wrs. is er nog meer aan de hand.

**Comment by ArjanLoeffen** [comment]
Ja, klopt, maar daar is helemaal geen area info meegeleverd, dus valt er niks te klikken. Ik vermoed omdat het een detail-diagram betreft, zou ik moeten uitzoeken.

**Comment by jacobvosimpronotion** [comment]
Ook detail-diagrammen waren klikbaar. Zie https://broprogramma.github.io/EPL.

**Comment by jacobvosimpronotion** [comment]
@ArjanLoeffen Wat is de voortgang op dit issue?

**Comment by jacobvosimpronotion** [comment]
Twee vragen:

1. Hoe krijgen we $map hersteld voor detaildiagrammen in alle catalogi waar die nu weggevallen zijn? Moeten die catalogi opnieuw gegenereerd worden? Voor https://broprogramma.github.io/EPL heb ik geconstateerd dat het hersteld is.

2. Het omprogrammeren op javascript/css niveau om de coördinaten in de image maps te berekenen o.b.v. de verschaling van een diagram, gaan jullie dat nu oppakken, of is het iets speciaals dat de mening van de user group vereist?

**Comment by ArjanLoeffen** [comment]
- Alle catalogi moeten opnieuw worden gegenereerd.
- De users group hoeft hier niets over te zeggen. Het lijkt een bug in de constructie; ik moet wel even kijken wie verantwoordelijk is voor CSS en JS. Dat verschilt per klant.

**Comment by jacobvosimpronotion** [comment]
Wie is verantwoordelijk voor CSS en JS in ons geval?

**Comment by ArjanLoeffen** [comment]
Volgens mij is dat @adbgnm

**Comment by jacobvosimpronotion** [comment]
We gaan dit binnen BRO Standaardisatie oplossen.
