### ISSUE TITLE
BRO: 'Type' niet getoond als IndicatieJaNeeOnbekend voor IMBRO wordt gebruikt

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#421]
Als een attribuut het datatype ‘IndicatieJaNee' heeft, dan wordt in de ReSpec catalogus onder de naam van het domein 'IndicatieJaNee’ als type van het domein “Waardelijst niet uitbreidbaar” getoond.

Bij het datatype ‘IndicatieJaNeeOnbekend’ wordt het domeintype echter niet getoond, wat wel moet.

**Comment by ArjanLoeffen** [comment]
Morgen beschikbaar.

**Comment by jacobvosimpronotion** [comment]
Opgelost, dank.
