### ISSUE TITLE
IHW: pad naar images-map op github niet correct

### ISSUE THREAD

**Issue by WijnandIHW** [Imvertor/Imvertor-Maven#424]
We krijgen de plaatjes van onze domeinmodellen niet automatisch zichtbaar in de catalogus. We hebben een propertiesfile met createimagemap = yes. De images worden in ./data/images/ gezet, terwijl dit in ./images/ zou moeten. Hoe krijgen we dit voor elkaar?

**Comment by ArjanLoeffen** [comment]
De images komen terecht in

https://github.com/Aquo-standaard/IMWA-KW/tree/main/data/Images

Dit is de juiste locatie omdat de IHW bot daar veilig naar toe kan schrijven.
Vanuit een html file in gh-pages wordt verwezen naar deze images, als `src="data/Images/*"`. Dit is voor IHW aangepast.
De images in de data folder worden gebruikt, NIET de images in de root folder `/images`.

**Comment by WijnandIHW** [comment]
Werkt voor IMWA-Kunstwerken
