### ISSUE TITLE
IHW: Respec-catalogus opmaak wensen

### ISSUE THREAD

**Issue by WijnandIHW** [Imvertor/Imvertor-Maven#425]
In onze respec catalogi geven we overzichten van attributen van objecten:

![](https://github.com/Imvertor/Imvertor-Maven/assets/104829403/b7ba4371-73b0-48b2-a170-f772ca8d6c49)

Kan de kolomtitel Formaat gewijzigd worden in Attribuuttype? En Card in Kardinaliteit?

**Comment by ArjanLoeffen** [comment]
Dus overal waar Formaat en Card de kolomtitels zijn?

**Comment by ArjanLoeffen** [comment]
Deze termen zijn nu doorgevoerd op:

- Attribuutsoorten
- Data elementen
- Union elementen
- Referentie elementen

NB. doordat "Kardinaliteit" een lang woord is wordt er veel ruimte ingenomen in de tabel door deze kolom.
 
De vraag is wel of deze laatste drie als zodanig in rijen terecht komen; anders heeft de aanpassing geen effect.

NB @WijnandIHW kun je aangeven waar ik een catalogus kan vinden waar hef effect wordt getoond? Er is geen SAMPLE catalogus beschikbaar voor ontwikkeling/debugging.

**Comment by WijnandIHW** [comment]
Is voorlopig voldoende
