### ISSUE TITLE
IHW: Codelijsten in respec-catalogus

### ISSUE THREAD

**Issue by WijnandIHW** [Imvertor/Imvertor-Maven#426]
We hebben ook nog een dingetje met onze codelijsten. We hebben ze in EA gedefinieerd als Codelijst, maar we willen wel de lijsten met domeinwaarden zichtbaar hebben in de catalogus. Ik zie in https://imvertor.armatiek.nl/imvertor-executor/dashboard/wiki?key=cli-includedoclist 3 mogelijkheden, maar geen van die 3 is voor ons bruikbaar. Op ons aquo-wiki platform zijn domeinwaarden separate paginas met een (SKOS) Breder relatie naar de domeintabel. Je vraagt de domeintabel met -waarden op door een API-call. De output van die call zou wel een xml-document kunnen zijn, maar we hebben niet iets als een domeintabellen-service met set van kant-en-klaar xml-documenten.  
Zijn we hierin uniek, of zijn er imvertor gebruikers die op een vergelijkbare manier werken?

**Comment by ArjanLoeffen** [comment]
Geef me een voorbeeld van zo'n domeintabel & api-call.

**Comment by ArjanLoeffen** [comment]
Dit kan niet. Codelijsten hebben geen waarden in het model.

**Comment by WijnandIHW** [comment]
Zou je het dan kunnen oplossen zoals het bij de BRO gebeurt? De codelijst met stereotype codelijst en de waarden als <<enumeratiewaarde>>? 
![image](https://github.com/Imvertor/Imvertor-Maven/assets/104829403/78cd7a48-314e-4295-a32a-4f63e57a6d3f)
