### ISSUE TITLE
Viertal fouten bij het genereren van Respec HTML

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#428]
Het genereren van de HTML voor Respec gaat op 4 punten fout. De voorbeelden in de beschrijvingen staan in [dit bestand](https://github.com/Imvertor/Imvertor-Maven/files/13646887/SIM-Open.Raads-.en.StatenInformatie-1-20230113.respec.zip)

## (1) Link naar attribuutsoort met enumeration formaat werkt niet

De link in de kolom 'Formaat' bij het  attribuutsoort 'Provincie' binnen het entiteittype 'AGENDAPUNT' werkt niet. Dit komt omdat dit verwijst naar een section element met het id '#global_class_Model_provincie'. Dat bestaat echter helemaal niet. Ik vermoed dat een enumeration nu op dezelfde wijze naar Respec wordt gerendered als een Referentie element, dat is niet correct. in plaats daarvan moet het verwijzen naar een section met id '#detail_class_Model_provincie'. 

## (2) Sections m.b.t. associations komen dubbel voor

De section met id '#detail_association_Model_NATUURLIJKPERSOON_islidvan' komt tweemaal voor. Dat klopt in principe ook want 1 keer is het de relatie die verwijst naar FRACTIE en de andere keer de relatie die verwijst naar 'DAGELIJKS BESTUUR'. Dit geeft echter wel een fout in Respec want beide secties hebben dus dezelfde id. Een oplossing zou zijn in het id de naam van het gerelateerde objecttype mee te nemen. Natuurlijk moeten dan ook alle 'href' attributen die daarnaar verwijzen worden aangepast.
Hetzelfde geldt voor de sections met de id's:
* `detail_association_Model_INDIENER_is`
* `detail_association_Model_STEMMING_heeftbetrekkingop`
* `detail_association_Model_AANWEZIGEDEELNEMER_neemtdeelaan`

## (3) Gegevensgroeptypes worden 2 keer in het document getoond <-- OPGELOST

Gegevensgroeptypes worden nu 2 keer in het document getoond. Één keer als onderdeel (subparagraaf) van het objecttype waarin het attribuutsoort, dat de gegevensgroeptype als formaat gebruikt, staat en één keer als onderdeel van de paragraaf 'Gegevensgroeptype details', zie hieronder een voorbeeld:

```
4.7 Attribuut- en relatiesoort details

4.7.1 Objecttype details

4.7.1.5 NATUURLIJK PERSOON

4.7.1.5.5	Gegevensgroeptype Nevenfunctie NATUURLIJKE PERSOON

Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Omschrijving nevenfunctie
Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Naam organisatie nevenfunctie
Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Aantal uren per maand
Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Indicator bezoldigd
Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Indicator nevenfunctie vanwege lidmaatschap
Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Datum melding
Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Datum aanvang nevenfunctie
Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Datum einde nevenfunctie

4.7.2 Gegevensgroeptype details

4.7.2.1		Gegevensgroeptype Nevenfunctie NATUURLIJKE PERSOON

4.7.2.1.1 Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Omschrijving nevenfunctie
4.7.2.1.2 Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Naam organisatie nevenfunctie
4.7.2.1.3 Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Aantal uren per maand
4.7.2.1.4 Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Indicator bezoldigd
4.7.2.1.5 Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Indicator nevenfunctie vanwege lidmaatschap
4.7.2.1.6 Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Datum melding
4.7.2.1.7 Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Datum aanvang nevenfunctie
4.7.2.1.8 Attribuutsoort details Nevenfunctie NATUURLIJKE PERSOON Datum einde nevenfunctie
```

Aangezien gegevensgroeptypes door meerdere attribuutsoorten in meerdere objecttypes gebruikt kunnen worden lijkt me dat de eerste variant moet verdwijnen. Dat lost meteen het probleem op van de dubbele id's. In beide sections worden nl. dezeelfde id's gegenereerd.

## (4) Onterechte `class="notoc"` <-- OPGELOST

Sections die voor 'Gegevensgroepen' worden gegenereerd worden gegenereerd met `class="notoc"`, voorbeelden:

```<section class="notoc" id="detail_attribute_Model_NATUURLIJKPERSOON_NevenfunctieNATUURLIJKEPERSOON">
<section class="notoc" id="detail_attribute_Model_NATUURLIJKPERSOON_NaamNATUURLIJKPERSOON">
<section class="notoc" id="detail_attribute_Model_INFORMATIEOBJECT_Zaken">
<section class="notoc" id="detail_attribute_Model_STEMMING_Stemmingoverpersonen">```
```

Dit is niet terecht.

By the way, eigenlijk zouden de id's in de bovenstaande code de volgende waardes moeten hebben:

```
detail_gegevensgroep_Model_NATUURLIJKPERSOON_NevenfunctieNATUURLIJKEPERSOON
detail_gegevensgroep_Model_NATUURLIJKPERSOON_NaamNATUURLIJKPERSOON
detail_gegevensgroep_Model_INFORMATIEOBJECT_Zaken
detail_gegevensgroep_Model_STEMMING_Stemmingoverpersonen```

**Comment by ArjanLoeffen** [comment]
Ik kan dit niet overzien. Ik zou graag het model willen hebben waar deze catalogus op is gebaseerd, en een context waarin in de HTML goed kan bekijken; hebben jullie een respec config / publicatie locatie? Staat het ergens in ph pages?

NB De aanpassingen die je vraagt zijn ingrijpend voor anderen die Respec gebruiken. Dus met beleid doorvoeren.

**Comment by ArjanLoeffen** [comment]
(1)
De globale opsomming van enumeraties (alleen de naam en definitie, in een tabelletje) moet per enumeratie een ID hebben in de vorm `global_class_(domein)_(enumeratie)`. We linken dus naar een waarde in deze tabel, beetje raar maar we zijn dan zeker dat we geen zaken overhoop gooien. NB het issue is ook in bijv. Waarderingskamer IMWOZ terug te zien.

(2)
Er moet een validatieregel komen: associaties moeten een unieke naam hebben voor relatiesoort en/of relatierol. Zie  https://docs.geostandaarden.nl/mim/cv-st-mim-20231018/#afspraken-rondom-naamgeving-en-definities

(3)
Er zijn secties
- Objecttype details
- Gegevensgroeptype details

Beide bevatten de detailinfo van de attribuutsoorten in de gegevengroeptype. Ons voorstel: configureer waar je vindt dat het moet komen: onder objecttype details (dus uitgebreide opsomming) óf onder gegevensgroeptype details (die dus zou kunnen komen te vervallen.
NB Voorbeeld is VNG KOOPSOM.

(4)
`Notoc `is om een reden erin gezet en vooralsnog geen aanpassingen.
Wel moeten we de ID's aanpassen: het wordt dus bijv. `detail_gegevensgroep_Model_STEMMING_Stemmingoverpersonen`

**Comment by ArjanLoeffen** [comment]
tav. (2):

er is een regel toegevoegd aan MIM 1.1.1 modellen dat géén eigenschappen van constructies kunnen bestaan uit delen met gelijke naam. Dus attributen, associaties, associatie rollen moeten unieke naam hebben binnen die constructie (UML klasse), maar ook de data elementen, en enumeratiewaarden. Het moet blijken of er gevallen zijn waarin om terechte redenen namen toch meermaals voorkomen. Mijn inschatting is dat dit onbedoelde verdubbelingen zijn.

De melding is (bijv.):
> Several properties with same name found: "Bevat", "Heeft"

**Comment by ArjanLoeffen** [comment]
Tav (3)

We hebben een docrule toegevoegd: _gegevensgroep-attribute-container_ = 'object' or 'group'
Betekenis: Moeten de details van attribuutsoorten uit een gegevensgroeptype alleen worden opgenomen in de sectie voor gegevengroeptypen ('group'), of ook bij de objecten ('object')?
Default is: 'object'. 
Voorbeeld:

```xml
    <gegevensgroep-attribute-container>group</gegevensgroep-attribute-container>
```

Er is dus nog niet besloten om de mogelijkheid de hele sectie mbt gegevensgroeptypen weg te laten. Dit omdat er niet wordt geklaagd over de huidige situatie.

**Comment by ArjanLoeffen** [comment]
Tav. (4)

De ID is ontleend aan de formele naam van een constructie. Deze is opgenomen in het embellish bestand en is _onafhankelijk van het metamodel_. Ik heb daarom niet de neiging daarin te gaan rommelen. Let wel:

`detail_attribute_Productie_Operator_voornaam` (metamodel onafh.)
is niet
`detail_attribuutsoort_Productie_Operator_voornaam` (metamodel afh.)
en moet daarom ook niet worden:
`detail_gegevensgroep_Productie_Operator_voornaam` (metamodel afh.)

:-)

**Comment by melsk-r** [comment]
> Tav. (4)
> 
> De ID is ontleend aan de formele naam van een constructie. Deze is opgenomen in het embellish bestand en is _onafhankelijk van het metamodel_. Ik heb daarom niet de neiging daarin te gaan rommelen. Let wel:
> 
> `detail_attribute_Productie_Operator_voornaam` (metamodel onafh.) is niet `detail_attribuutsoort_Productie_Operator_voornaam` (metamodel afh.) en moet daarom ook niet worden: `detail_gegevensgroep_Productie_Operator_voornaam` (metamodel afh.)
> 
> :-)

Ik begrijp het, zowel een `attribuutsoort` als een `gegevensgroep` is een voorkomen van een `attribute`, dan zijn de id's inderdaad toch correct.

**Comment by ArjanLoeffen** [comment]
Kan ik dit issue sluiten? Is het getest?

Nb in het vervolg per onderwerp een apart issue aanmaken; is daardoor beter de managen en kan daardoor betere release notes aanmaken.

**Comment by melsk-r** [comment]
> Kan ik dit issue sluiten? Is het getest?

Ga ik z.s.m. doen maar mogelijk pas na de jaarwisseling.

> Nb in het vervolg per onderwerp een apart issue aanmaken; is daardoor beter de managen en kan daardoor betere release notes aanmaken.

Ga ik doen.

**Comment by melsk-r** [comment]
T.a.v. (1) 

Je geeft aan dat je exact dezelfde oplossing doorvoert voor codelijsten. Het is mij echter niet helemaal duidelijk wat die oplosing dan is. Ik vermoed dat je nu overal doorlinkt naar '#global_class_Model_<enumeratienaam>' of '<#global_class_Model_<codelijstnaam>'. Het probleem doet zich i.i.g. niet meer voor bij enumerations. Bij codelijsten vind ik nog steeds voorkomens die verwijzen naar '#global_class_Model_<codelijstnaam>'. Zie [bijgaande zip](https://github.com/Imvertor/Imvertor-Maven/files/13886319/KING.zip).

T.a.v. (2) 

De validatieregel lijkt niet te werken. Hoewel in het model dat ik test nog de in de eerste post van dit issue aangegeven situatie voorkomt wordt daar geen melding van gemaakt. Zie [bijgaande zip](https://github.com/Imvertor/Imvertor-Maven/files/13886319/KING.zip).

T.a.v. (3) 

Nu het probleem met de  dezelfde id's voor 2 verschillende secties is opgelost is er ook geen probleem meer. Top dat je nu kunt aangeven waar je dit soort secties gegenereerd wil hebben en dat werkt zo te zien.

T.a.v. (4) 

Geen opmerkingen.

**Comment by ArjanLoeffen** [comment]
Tav (1)

Ik zie dat mijn opmerking niet klopt: Codelijst volgt de aanpak van referentielijst. Ik ben terughoudend om het aan te passen wegens het gebruik bij andere users.

Samenvattend:
Voor enumeraties wordt altijd gelinked naar detail. Voorbeeld in jouw zip:
```
#detail_class_Model_besluitResultaat
```
Voor codelijst wordt naar enumeraties en codelijsten gelinked. Voorbeeld in jouw zip:
```
#global_class_Model_Codelijsttest
#detail_class_Model_Codelijsttest
```
Codelijst volgt de aanpak van referentielijst. In jouw zip:
```
#global_class_Model_WATERSCHAP
#detail_class_Model_WATERSCHAP
```

**Comment by ArjanLoeffen** [comment]
Tav (2):
Waar moet ik naar zoeken? De regel is wel degelijk actief.

**Comment by melsk-r** [comment]
> Tav (1)
> 
> Ik zie dat mijn opmerking niet klopt: Codelijst volgt de aanpak van referentielijst. Ik ben terughoudend om het aan te passen wegens het gebruik bij andere users.
> 
> Samenvattend: Voor enumeraties wordt altijd gelinked naar detail. Voorbeeld in jouw zip:
> 
> ```
> #detail_class_Model_besluitResultaat
> ```
> 
> Voor codelijst wordt naar enumeraties en codelijsten gelinked. Voorbeeld in jouw zip:
> 
> ```
> #global_class_Model_Codelijsttest
> #detail_class_Model_Codelijsttest
> ```
> 
> Codelijst volgt de aanpak van referentielijst. In jouw zip:
> 
> ```
> #global_class_Model_WATERSCHAP
> #detail_class_Model_WATERSCHAP
> ```

Daar lijkt het inderdaad op. Het enige verschil is dat er voor referentielijsten wel secties zijn met id's als 'global_class_Model_xxxx' bestaan en voor codelijsten niet. Daardoor loopt de link van het Formaat 'Codelijst test' (zie in de onderstaande image de tekst net de oranje achtergrond kleur) dood.

![image](https://github.com/Imvertor/Imvertor-Maven/assets/20185784/3f4bde66-75e4-413a-8f2c-9c492f6f3538)

**Comment by melsk-r** [comment]
Zoals je in onderstaande image ziet bestaan er 2 voorkomens van de relatie 'is lid van'. Naar aanleiding daarvan had ik de melding

> Several properties with same name found: "is lid van"

verwacht.

![image](https://github.com/Imvertor/Imvertor-Maven/assets/20185784/42faf204-ce94-421c-a677-3b4e421c2b5f)

**Comment by ArjanLoeffen** [comment]
Tav (1)

Ik zie dat het eigenlijk niet acceptabel is om geen globale ID te hebben voor enumeraties en codelijsten. Dat komt doordat de diagrammen altijd verwijzen naar de globale beschrijvingen (en globale ID's). Ik vat het niet aanwezig zijn van een globale ID dus op als een Bug. Wat jij?

Nb. stel dat je codelijst en enumeratie hebt, dan krijg je 
![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/229c69f8-e270-4954-8537-e0fc20db20ef)

Een link naar de "globale" beschrijving is dis effectief een link naar de regel in het tabelletje. Dat komt omdat er niet méér info is op globaal niveau voor deze construct. 
Dat is anders voor referentielijsten, bijv:

![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/85881667-f797-4579-ad4b-518f709ee910)

**Comment by ArjanLoeffen** [comment]
Ten aanzien van dubbele property namen: is de is-lid-van relatie uitgaand voor één construct? Zo zie het er niet uit.

**Comment by ArjanLoeffen** [comment]
Na Teams overleg:
- We gaan de globale ID's toevoegen aan enums en codelists
- De regel omtrent unieke namen betreft ook associatieklassen/relaties.

**Comment by melsk-r** [comment]
@ArjanLoeffen n.a.v. het testen met imagemaps zag ik dat dit issue nog niet was afgerond dus ik wil dit weer oppakken.
Ik weet alleen niet meer in welke branch jij deze aanpassingen had aangebracht,

**Comment by melsk-r** [comment]
@ArjanLoeffen Ik ben er vanuit gegaan dat de wijzigingen in de 'development' branch zijn aangebracht.

Nogmaals getest maar ik krijg nog steeds meldingen dat id's dubbel voorkomen zonder dat [de Imvertor run](https://imvertor.armatiek.nl//download/dat/2024-03-25-14-20-55-231/work/app/doc/index.html) aangeeft dat er problemen zijn met dubbele id's. Zie de betreffende [GitHub Actions run](https://github.com/VNG-Realisatie/Respec-test/actions/runs/8421766827) waarin een WCAG check wordt uitgevoerd die fout loopt. Als je doorklikt zie je dat er 26 errors van het volgende type voorkomen:

![image](https://github.com/Imvertor/Imvertor-Maven/assets/20185784/3a5dcbf9-270f-4ee1-9132-bc8ed3680f3f)

**Comment by melsk-r** [comment]
> Tav (1)
> 
> Ik zie dat het eigenlijk niet acceptabel is om geen globale ID te hebben voor enumeraties en codelijsten. Dat komt doordat de diagrammen altijd verwijzen naar de globale beschrijvingen (en globale ID's). Ik vat het niet aanwezig zijn van een globale ID dus op als een Bug. Wat jij?

Het is wel consistent om ook voor Enumeraties en Codelijsten een element met een globaal ID t eintroduceren. Uit gebruikersvriendelijk oogpunt zie ik het nut eigenlijk niet zo, het kost immers onnodig een klik meer.

**Comment by ArjanLoeffen** [comment]
Ik zie dat in de catalogus een gegevensgroeptype op twee plekken terecht komt:

- Groene pijl: gegevengroep
- Blauwe pijl gegevensgroeptype. Die hoort niet direct achter de groene pijl te komen.
- Rode pijl de verdubbelde ID, een attribuutsoort in het gegevensgroeptype.

Dus wat mij betreft moet die eerste blauwe pijl worden verwijderd. Wel raar dat niemand daar over klaagt. Ik doet dit verder uit.

![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/c262f5d7-ce15-4b6d-aaea-e2922732c3ed)

**Comment by melsk-r** [comment]
> Wel raar dat niemand daar over klaagt. 

Ik denk dat nog niemand het tot dat detail gecheckt heeft. Wat overigens wel vreemd is, is dat ik de gegevensgroepen wel in de content zie maar niet in de inhoudsopgave.

![image](https://github.com/Imvertor/Imvertor-Maven/assets/20185784/d7a08119-6ee8-4b66-b011-308dc338ea49)

**Comment by ArjanLoeffen** [comment]
Ik heb de correctie doorgevoerd. Ik zie dat dit probleem ook optreedt in de fietsenwinkel documentatie. Ik neem aan dat niemand dat zal opvallen. De _gegevensgroeptype details_  zijn dus vervallen in de context van _gegevensgroep attribuut details_.

**Comment by melsk-r** [comment]
@ArjanLoeffen Ik zie dat de sectie die met de eerste blauwe pijl wordt aangeduid inderdaad is verwijderd, mooi.
Helaas is echter ook de sectie die met de groene pijl wordt aangeduid verwijderd. Dat lijkt me niet de bedoeling.

**Comment by melsk-r** [comment]
Ik ga de problemen in dit issue proberen te reproduceren. Dit issue sluit ik en als ik nog problemen ervaar dan zal ik een nieuw issue opvoeren
