### ISSUE TITLE
MIM ​serialisatie: Geen RDF-XML output

### ISSUE THREAD

**Issue by WijnandIHW** [Imvertor/Imvertor-Maven#430]
Ik krijg geen output bij het gebruik van de volgende properties: 

createmimformat = yes

mimformatname = WL-SIM

mimformattype = rdf-xml

Ontbreekt er nog wat om een MIM serialisatie te genereren?

**Comment by ArjanLoeffen** [comment]
Nee, er ontbreekt geen property. Krijg je geen foutmeldingen? Als je model bijvoorbeeld niet voldoet aan de minimale MIM eisen kun je meldingen krijgen zoals:

> MIM serialisation requested on a model that is not MIM compliant. No "MIM versie" found.

Welke job kan ik bekijken?

**Comment by ArjanLoeffen** [comment]
Ik zie dat je job [2023-12-08-09-56-38-650](https://imvertor.armatiek.nl/imvertor-executor/dashboard/app?subpath=SIM%2FWL%20SIM%2F20210113&job=2023-12-08-09-56-38-650) geen waarde heeft voor `createmimformat`. Ik vermoed dat je je properties niet correct hebt meegegeven aan het proces.

**Comment by WijnandIHW** [comment]
Nu wel de goede properties :) , en idd de fout: 

MIM serialisation requested on a model that is not MIM compliant. No "MIM versie" found.

Ik heb geen idee waar en hoe ik er voor kan zorgen dat er wel een MIM-versie gevonden kan worden.

**Comment by ArjanLoeffen** [comment]
Een MIM compliant model moet die tagged value hebben. Check https://docs.geostandaarden.nl/mim/cv-st-mim-20231018/#informatiemodel-1

Dus tagged value: 
`MIM versie = 1.1.1`

Check ook de andere verplichte tagged values.

We zijn bezig naar 1.2 te gaan.
