### ISSUE TITLE
BRO: Weergave Keuze in catalogus: volgorde en Regels

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#434]
Twee dingen m.b.t. weergave van elementen met het stereotype 'Keuze' in catalogi:

Volgorde in de catalogus: deze elementen worden nu getoond ná objecttypen en gegevensgroeptypen. Wens is: opnemen op de plaats waar ze in het EA-package staan.

Bij een element met het stereotype ‘Keuze’ worden nu de ‘Regels’ niet getoond. Wens: regels opnemen (na het kenmerk ‘Definitie’, vóór het kenmerk ‘Toelichting’.

**Comment by ArjanLoeffen** [comment]
Geef even een voorbeeld waarbij je dit aantreft. Dus locatie van objecttypen, gegevengroeptypen en keuzes. Ik neem aan dat je dit voor de BRO vraagt.

**Comment by jacobvosimpronotion** [comment]
Vandaag getest in nightly build, en is akkoord.
