### ISSUE TITLE
Toepassen SBB voor generatie skos bestand

### ISSUE THREAD

**Issue by PalmJanssen** [Imvertor/Imvertor-Maven#437]
Imvertor genereert skos RDF voor begrippenkaders uit UML.

Dit ziet er goed uit maar er zijn een paar issues.

In de generatie van skos items kan nu de standaard voor beschrijven van begrippen [SBB](https://profielstelselcatalogus.pldn.nl/) worden gebruikt. Dat lost een aantal issues op.

**Comment by ArjanLoeffen** [comment]
Dit is verdubbeling van #427 
Ik sluit deze.
