### ISSUE TITLE
Fout in RDF-XML serialisatie

### ISSUE THREAD

**Issue by WijnandIHW** [Imvertor/Imvertor-Maven#441]
Bij serialisatie naar RDF-XML van een Basismodel krijgen relaties met stereotype relatiesoort bron en doel hetzelfde id als de relatie. Dit levert 'duplicate value'  fouten op in de XML

**Comment by ArjanLoeffen** [comment]
De identifiers van bron en doel in de relatie werden verkeerd uitgelezen. Dat is hersteld.

Voor relatiesoort gebaseerde  modellen kan het m.i. zo zijn dat er geen bron en doel info hoeft te worden meegeleverd in de MIM, wat deze fout melding overbodig maakt. Hierover contract gezocht met MIM commissie:

> In MIM 1.2 is gespecificeerd:
> 
> _Alternatief 1: Relatiesoort is leidend_
> _Relatiesoort is verplicht, met een naam en met een definitie en deze is leidend. Metadata aspecten worden hierbij altijd vastgelegd. Het gebruik van relatierol is optioneel (zowel bij source en target). Áls er een relatierol target wordt vastgelegd, dan is de metadata hierbij wel verplicht._
> 
> Hoe bepaal ik of een target is vastgelegd? Een relatie kan toch nooit worden gelegd zonder een bron en doel? Is het criterium dat er een naam aan is gegeven?

Zie https://docs.geostandaarden.nl/mim/cv-st-mim-20231018/#relaties-in-uml

Vooralsnog heb ik besloten dat dat laatste het geval is. Dus als een rol géén naam heeft wordt verondersteld dat die rol niet nader gespecificeerd is, en niet hoeft te worden opgenomen in de serialisatie.

**Comment by ArjanLoeffen** [comment]
Wanneer deze correctie is uitgevoerd blijkt een ander probleem. Zie #442.

**Comment by PalmJanssen** [comment]
Als toevoeging. Het besluit is correct.
> > In MIM 1.2 is gespecificeerd:
> > _Alternatief 1: Relatiesoort is leidend_
> > _Relatiesoort is verplicht, met een naam en met een definitie en deze is leidend. Metadata aspecten worden hierbij altijd vastgelegd. Het gebruik van relatierol is optioneel (zowel bij source en target). Áls er een relatierol target wordt vastgelegd, dan is de metadata hierbij wel verplicht._
> > Hoe bepaal ik of een target is vastgelegd? Een relatie kan toch nooit worden gelegd zonder een bron en doel? Is het criterium dat er een naam aan is gegeven?
> 
> Zie https://docs.geostandaarden.nl/mim/cv-st-mim-20231018/#relaties-in-uml
> 
> Vooralsnog heb ik besloten dat dat laatste het geval is. Dus als een rol géén naam heeft wordt verondersteld dat die rol niet nader gespecificeerd is, en niet hoeft te worden opgenomen in de serialisatie.


Dat is correct: met ‘gebruik van relatierol’ wordt bedoeld ‘het gebruik van het modelelement relatierol’. In feite dus als die relatierol benoemd is (een naam heeft) in het model.

Bij een relatie is er inderdaad altijd een bron en een doel. Maar het gaat hier over het feit of die wel of niet met het modelelement ‘relatierol’ is benoemd en gemetadateerd. Niet benoemd leidt er toe dat de relatierol niet geserialiseerd wordt.

**Comment by ArjanLoeffen** [comment]
Okay, dat is  nu zo doorgevoerd.

**Comment by WijnandIHW** [comment]
Bedankt voor de snelle actie en reactie. Het werkt, we krijgen een valide RDF-XML.
