### ISSUE TITLE
Fout in inhoud begin 1e 'p' element van catalog bestand

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#460]
Het begin van het 1e 'p' element van een catalog bestand bevat informatie over:
* het type model;
* de naam van dat model;
* de versie van dat model;
* de tijd waarop het catalog bestand is gegenereerd.

Zie het html fragment hieronder:

```
   <body>
      <p>BASISMODEL
         :
         Open Raads- en StatenInformatie
         :
         2.0.0
         :
         2024-02-23T08:33:47Z</p>
```

Er wordt hier netjes aangegeven dat het om versie 2.0.0 van het model gaat. Tenminste daar lijkt het op als je een SIM verwerkt als 'MIM SIM Uitgebreid' met versie 2.0 van Imvertor. Als je datzelfde model nl. verwerkt met Imvertor 3.0 ziet het er als volgt uit:

```
   <body>
      <p>BASISMODEL
         :
         Open Raads- en StatenInformatie
         :
         3.0.0
         :
         2024-02-23T07:59:07Z</p>
```

Het versienummer blijkt dan ineens niet het versienummer van het model te zijn maar het versienummer van Imvertor. Dat lijkt me niet de bedoeling.

Verzoek om dit te corrigeren.

**Comment by ArjanLoeffen** [comment]
Wat bedoel je met een een "catalog bestand"?
De respec die default wordt gegenereerd? Daar kom ik deze opbouw van waarden niet tegen.

**Comment by melsk-r** [comment]
Het gaat ook niet om de Respec documentatie.

Ik heb zojuist job [2024-04-15-09-45-24-095](https://imvertor.armatiek.nl/imvertor-executor/dashboard/app?job=2024-04-15-09-45-24-095) gedraaid. In de 'cat' folder in de zip vind je een html bestand en daar tref je nu:

```
   <body>
      <p>BASISMODEL
         :
         Open Raads- en StatenInformatie
         :
         4.0.0
         :
         2024-04-15T09:45:27Z</p>
      <p>
```

aan. De 4.0.0 slaat echter niet op het model maar op de Imvertor versie.

**Comment by ArjanLoeffen** [comment]
Je bedoelt MsWord documentatie. Die heeft een iets andere opbouw. De code die daar verantwoordelijk voor is is:
```xml
  <p>
                    <xsl:value-of select="@type"/>
                    :
                    <xsl:value-of select="@name"/>
                    :
                    <xsl:value-of select="@generator-version"/>
                    :
                    <xsl:value-of select="@generator-date"/>
     </p> 
```

Dat zijn attributen van de tussenvorm `<book>`, bijvoorbeeld:

```xml
<book name="SIM Logging"
      subpath="SIM/SIM Logging/20201009"
      type="BASISMODEL"
      id="EAPK_2AFAF2B1_2CD1_4fe5_AC81_1C2A6D76FDCF"
      generator-version="Nightly-build.14"
      generator-date="2024-04-15T10:22:47Z">
```

Wat wil je precies zien op die plek? dat moet eigenlijk gewoon worden ingericht, zoals bij iedereen.

**Comment by melsk-r** [comment]
Ok, de `4.0.0` wordt dus gegenereerd door 

```xml 
<xsl:value-of select="@generator-version"/>
```
en werkt dus zoals gespecificeerd. Ik zou het echter logischer vinden om hier het versienummer van het model te genereren.
Zeker zonder een label als `Generator: ` wek je n.m.m. de indruk dat de `4.0.0` op het model slaat.

**Comment by ArjanLoeffen** [comment]
Okay, pas ik dat voor jullie aan.

**Comment by ArjanLoeffen** [comment]
Eigenlijk weet ik gewoon niet wat jullie willen. Ik heb er nu maar van gemaakt, alléén voor MsWord output van SIM bestanden:

![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/370704bb-9c69-48a0-96d6-61589ff23899)

Maar beste is als jullie aangeven wat gewenst is voor alle documentatie varianten: Respec, MsWord i.c.m.  SIM, UGM, BSM.
"Alles" kan, het moet gewoon even worden ingericht.

Let wel: dit is nog steeds enkel de grove kern  (de catalogus), niet de documentatie, dus niet bedoeld voor verspreiding.

**Comment by melsk-r** [comment]
@ArjanLoeffen Is dit een configuratie kwestie of moet je hiervoor aanpassingen in de xslt stylesheets doorvoeren?

Anders is het misschien een idee dat ik het zelf voor ons doe.

**Comment by ArjanLoeffen** [comment]
Dit kun je doorvoeren in de stylesheets. Echter, ook in een centrale stylesheet worden waarden gezet (in de vorm van attributen) en als je nieuwe waarden wilt gebruiken moet je dat stylesheet ook aanpassen. Beter is even overleggen.
