### ISSUE TITLE
Imvertor genereert geen `<img>` en `<map>` elementen

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#463]
Ondanks dat de parameter 'createimagemap' de waarde 'yes' heeft worden er geen `<img>` elementen en gerelateerde `<map>` elementen in de Respec (x)html documenten gegenereerd.

Ik kan er niet helemaal de hand opleggen maar het begint er al mee dat de functie 'imf:create-section-for-diagrams' in het stylesheet 'OfficeCompiler/Imvert2modeldoc.xsl' lege content genereert. Mogelijk ligt dat aan de regel:

`<xsl:variable name="diagrams-in-construct" select="$imagemap/imvert-imap:diagram[(imvert-imap:in-construct,imvert-imap:in-package)[1] = $construct/imvert:id]"/>`

die volgens mij nooit wat op kan leveren aangezien `$imagemap/imvert-imap:diagram[(imvert-imap:in-construct,imvert-imap:in-package)[1]` een id van een diagram-package oplevert` en `$construct/imvert:id]` juist nooit.
Dat is echter maar een deel van het probleem. Als ik dat hack door de regel te vervangen door:

`<xsl:variable name="diagrams-in-construct" select="$imagemap/imvert-imap:diagram[(imvert-imap:in-construct,imvert-imap:in-package)[1] and .//imvert-imap:for-id = $construct/imvert:id]"/>`

levert dat weliswaar

`<div class="imageinfo "><img src="Images/xxx.png" usemap="#imagemap-EAID_xxx" alt="Diagram "></img></div>`

op maar nog steeds niet het bijbehorende `<map>` element. Dat wordt dan waarschijnlijk weer veroorzaakt doordat de variabele '$diagram-show-caption' in 'OfficeCompiler/common/Imvert2modeldoc-html-respec.xsl' false is. Waarom hangt het creëren van een `<map>` element samen met het wel of niet creëren van een caption en hoe kan je er voor zorgen dat er captions gegenereerd worden.

**Comment by ArjanLoeffen** [comment]
@melsk-r  Eerst even kijken of je diagram namen eindigt op `- overzicht` of op `- detail`. Dat is zo voor VNG geconfigureerd. 
Ik heb SIM Logging als test case gedraaid met deze suffixen, en die komen goed door, mét de maps.

**Comment by melsk-r** [comment]
De suffixes waren inderdaad niet aanwezig. Ik heb ze zoals je hieronder ziet

![image](https://github.com/Imvertor/Imvertor-Maven/assets/20185784/19a4b406-88c2-40db-a4f9-88ebd9a44564)

nu aangebracht. Als ik dat correct gedaan heb dan zou je mogen verwachten dat de eerste 2 diagrammen in de (x)html als 'img' element terug te vinden zouden moeten zijn en dat daarin ook de bijbehorende 'map' structuur terug te vinden is. Dat is nog niet het geval. Ik heb dit zowel lokaal als op de server uitgeprobeerd maar dat maakt geen verschil. Job Id op de server is '2024-03-19-09-42-24-678'.
Zijn de namen van de diagrammen nog steeds niet correct of heb ik nog foutjes in de properties staan?

**Comment by ArjanLoeffen** [comment]
Laten we uitgaan van deze opzet:
![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/2ee9d8d0-c8c8-448c-9f17-d167c2d825df)

- Alleen de diagrammen 1, 3 en 5 komen door.
- Diagram 2 is opgenomen in een package zonder betekenis, en wordt niet begrepen als behorende bij het model package.
- Diagram 4 is een _activity diagram_, alleen _class diagrams_ worden getoond.

Nb de suffix overzicht en detail geven alleen aan wet voor soort diagram het betreft; er wordt affectief geen onderscheid gemaakt omdat geen behoefte is gespecificeerd voor een onderscheid tussen (grote) overzichtsdiagrammen en (kleine) detaildiagrammen.

Let wel, als deze aanpak niet voldoet dan graag een alternatief voorstellen.

**Comment by melsk-r** [comment]
Met deze informatie lukt het allemaal veel beter maar het is nog niet helemaal goed.
Zie [de images binnen deze gegevensdefinitie](https://vng-realisatie.github.io/Respec-test/#catalog).
Er worden nu wel imagemaps gegenereerd maar als ik over de images hover dan klopt daar niet zo heel veel van. Op diverse plaatsen wordt gelinkt naar 'https://vng-realisatie.github.io/Respec-test/#global_class_Model_ORGANISATORISCHEEENHEID'.

Ik kan op basis van bovenstaande informatie i.i.g. wel de criteria waaraan diagrammen moeten voldoen opnemen in zowel de Respec documentatie die ik heb vervaardigd als in de VNG-R Imvertor documentatie. Maar misschien wel goed als het ook ergens in de Imvertor documentatie terecht komt.

**Comment by ArjanLoeffen** [comment]
Ditt probleem herken ik. Het komt doordat je de figuur downscalet naar de tekstbreedte. 
Verwijder `max-width: 100%;` uit je base.css.

**Comment by melsk-r** [comment]
Dat was hem inderdaad. Ik moest alleen even uitzoeken hoe ik de `max-width: 100%;` kon uitschakelen aangezien deze gedefinieerd stond in 'base.css' waarin ik niets kon aanpassen. Uiteindelijk heb ik in het `head` element in de 'index.html' van ons (van Logius afgeleide) Respec template het volgende toegevoegd:

```
 <style>
	.figure img,    .sidefigure img,    figure img,
	.figure object, .sidefigure object, figure object {
		max-width: none !important; 
	}
  </style>
```
