### ISSUE TITLE
BRO: Keuzes niet meer tonen als paragraaf in catalogi

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#466]
Na heroverweging van het gebruik van het MIM element 'Keuze' voor BRO standaarden, zijn we tot het besluit gekomen om keuzes niet meer als een paragraaf in BRO catalogi op te nemen.

Als voorbeeld: https://broprogramma.github.io/SLD/#global_class_Model_BodemlocatieofAangepaktgebied. In het EA package is hiervoor een element met het stereotype `<<Keuze>>` aanwezig. Deze paragraaf dient dus geheel te verdwijnen.

**Comment by ArjanLoeffen** [comment]
Ik begrijp dit als het verwijderen van alle keuze info (constructies met stereotype <<keuze>>) uit de documentatie.

**Comment by jacobvosimpronotion** [comment]
Ja, klopt.

**Comment by jacobvosimpronotion** [comment]
Getest, en akkoord bevonden.
