### ISSUE TITLE
Signaal als een compositie relatie naar gegevensgroep geen naam heeft

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#47]
Signaal als een compositie relatie naar gegevensgroep geen naam heeft. In dat geval wordt de naam van de gegevensgroep overgenomen als naam van de relatie. VNG gaat over naar expliciete namen voor alle compositie relaties. Het is daarom voor VNG aantrekkelijk om een melding te krijgen als die naam er niet is.

Vraag is nu: als info, warning or error opgeven? Of per metamodel apart implementeren? En voor welke metamodellen dan?

**Comment by ArjanLoeffen** [comment]
zie /Imvertor-Chains/src/main/resources/xsl/Validator/Imvert2canonical.xsl

**Comment by ArjanLoeffen** [comment]
Speelt dit nog? Anders sluiten.

**Comment by melsk-r** [comment]
Ik ga dit issue te sluiten. Bij het genereren van yaml speelt het i.i.g. niet waarmee er geen grote urgentie is om dit issue in te vullen. Mocht dit op de e.o.a. wijze weer gaan spelen dan openen we wel weer een nieuw issue.
