### ISSUE TITLE
BRO: Bij ontbrekende naam bij <<Keuze>> associatie is warning gewenst i.p.v. error

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#475]
Imvertor geeft een foutmelding indien bij een keuze-construct een associatie, met het stereotype ‘Keuze’ (tussen enerzijds het datatype element met het stereotype ‘Keuze’ en anderzijds een objecttype) die associatie geen naam heeft. Volgens MIM hoeft een dergelijke keuze-associatie geen naam te hebben.

Gewenste situatie: de naam bij een associatie die het stereotype ‘Keuze’ heeft, mag zowel leeg als gevuld zijn.

Zie als voorbeeld: https://broprogramma.github.io/SLD/#global_class_Model_Overheidsbesluitbodemverontreiniging. Daarin hebben nu de assocaties tussen enerzijds 'Bodemlocatie of Aangepakt gebied' en anderzijds 'Bodemlocatie' en 'Aangepakt gebied' een naam. En de naam op die plaats willen we weg kunnen laten zonder dat Imvertor daarop een error geeft.

**Comment by ArjanLoeffen** [comment]
Jacob, waar vind ik dit terug in de UML specificatie van MIM?

**Comment by ArjanLoeffen** [comment]
Hersteld: een relatie naar objecttypen in een keuze hoeft geen naam te hebben.

**Comment by jacobvosimpronotion** [comment]
@ArjanLoeffen Ik heb dit zojuist getest met de nightly-build, maar de foutmeldingen zijn er nog: https://imvertor.armatiek.nl//download/dat/2024-04-16-04-52-40-241/work/app/doc/index.html.

**Comment by ArjanLoeffen** [comment]
Dit is een andere foutmelding. De melding wordt gegeven door de documentatie module. Die is niet voorbereid op constructies zonder naam, in dit geval een relatie. Bug, ik ga ernaar kijken.

**Comment by ArjanLoeffen** [comment]
@jacobvosimpronotion Kun je me een qea bestand leveren waar dit in gebeurt; ik kan het niet reproduceren in een testomgeving.

**Comment by ArjanLoeffen** [comment]
Ik heb deze constructie getest in de Nightly build.:
![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/40d6981c-8b7d-4ad0-bb72-3692e7094012)

Dit voorbeeld is door jou aangeleverd; ik heb alleen de namen van de associaties voor deze test verwijderd. 
Ik krijg hierbij geen foutmeldingen. 

NB
In 4.0 wordt nog een foutmelding gegeven: _Cannot determine the name of this construct._  Dat is dus hersteld in de development branch.

**Comment by jacobvosimpronotion** [comment]
Getest met de nighly-build, en het werkt nu.
