### ISSUE TITLE
BRO: Onterechte foutmelding vanwege niet stereotyperen van associatie als Relatiesoort

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#477]
Bij het genereren van de BRO EPL-catalogus met gebruikmaking van Imvertor nightly-build of versie 4.0 verschijnt er de error: “Association to "OBJECTTYPE" must be stereotyped as "RELATIESOORT".

Dit is ongewenst: de BRO werkt niet volgens het principe van relatiesoort, maar relatierol.

Zie https://imvertor.armatiek.nl//download/dat/2024-04-17-13-38-33-151/work/app/doc/index.html.

Met versie 3.0 gaat het wel goed.

**Comment by jacobvosimpronotion** [comment]
@ArjanLoeffen Dit probleem treedt nog steeds op, constateer ik zojuist. Zowel in de nightly build als in 4.0. Kan dit op korte termijn opgelost worden?

**Comment by ArjanLoeffen** [comment]
Het wordt deze week opgelost.

**Comment by ArjanLoeffen** [comment]
In de tagged values op het informatiemodel is aangegeven dat de relatiesoort leidend is:

![image](https://github.com/Imvertor/Imvertor-Maven/assets/12828217/092849b3-5e42-49ed-b340-495b9ef58356)

Pas dit aan naar _Relatierol leidend_.

**Comment by jacobvosimpronotion** [comment]
Het aanpassen van het relatiemodelleringstype was de oplossing. Dank!
