### ISSUE TITLE
Toevoegen Inspire Hydronetwork aan CS

### ISSUE THREAD

**Issue by WijnandIHW** [Imvertor/Imvertor-Maven#481]
Voor het modelleren van hydrografische modellen gaan we bij IHW/Aquo HydroNetwork gebruiken. Kan dit schema toegevoegd worden aan de Inspire CS

**Comment by PalmJanssen** [comment]
Interessant. Kent Imvertor ook het Inspire model, of delen daarvan? IMKL (kabels en leidingen) is een extensie op Inspire Utility Networks. IMKL is een model van 'voor Imvertor' en MIM maar ik wil daar wel naar toe.

**Comment by WijnandIHW** [comment]
Enkele inspire-delen zijn al toegevoegd in de map: src/main/resources/input/INSPIRE/xsd

**Comment by ArjanLoeffen** [comment]
Zie #482  - ik sluit dit issue.
