### ISSUE TITLE
Voeg HydroNetwork toe aan INSPIRE configuratie

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#482]
Voeg HydroNetwork toe aan INSPIRE configuratie.  
Op verzoek van IHW / @WijnandIHW

**Comment by ArjanLoeffen** [comment]
Let op: INSPIRE referenties kennen we nu nog alleen vanuit de BRO setup. Het kan zijn dat er aan de IHW kant dus nog e.e.a. moet gebeuren om INSPIRE toegankelijk te maken voor IHW.

**Comment by ArjanLoeffen** [comment]
Had niet gezien dat #481 was aangemaakt. Vervolgvragen graag hier verder behandelen.

**Comment by WijnandIHW** [comment]
Het was even zoeken, maar ik denk dat Inspire HydroNetwork aan de BRO is toegevoegd ipv (ook) aan IHW.

**Comment by ArjanLoeffen** [comment]
Nee, HydroNetwork is opok voor IHW bescbikbaar gesteld. Dit door een xinlude link op te nemen:

```xml
<xi:include href="../../INSPIRE/xsd/cm-INSPIRE-HYDRONETWORK.xml"/>
```

**Comment by WijnandIHW** [comment]
Top, bedankt. Het werkt
