### ISSUE TITLE
Onverklaarbare MIM waarschuwing na runnen van UGM job

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#487]
Job 2024-05-23-07-58-06-285 resulteert in de volgende waarschuwingen:

![image](https://github.com/Imvertor/Imvertor-Maven/assets/20185784/d1e49eb7-a1d1-4403-bbaa-7a48b37702b6)

De eerste melding is echter onverklaarbaar omdat een UGM helemaal geen Informatiemodel is dat aan het MIM moet voldoen. Er wordt dan ook een ander profiel en andere run-properties toegepast.

**Comment by ArjanLoeffen** [comment]
Gefixed.

**Comment by melsk-r** [comment]
Akkoord!
