### ISSUE TITLE
Onverklaarbare GM_ waarschuwing na runnen van UGM job

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#488]
Job 2024-05-23-07-58-06-285 resulteert in de volgende waarschuwingen:

![image](https://github.com/Imvertor/Imvertor-Maven/assets/20185784/d1e49eb7-a1d1-4403-bbaa-7a48b37702b6)

De laatste is echter onverklaarbaar omdat er in het model helemaal niet gerefereerd wordt aan een GM_ datatype en al helemaal niet aan het datatype 'GM_SENTINEL' dat ik ook in het GML package dat binnen VNG-Realisatie gebruikt wordt helemaal niet tegenkom.

**Comment by ArjanLoeffen** [comment]
De GM_SENTINEL forceert het opnemen van GML in de imvert XML. Deze is nodig als er geen enkele referentie ie gemaakt naar een construct in GML.
GM_SENTINEL heeft daarom  slechts een signalleringsfunctie, en de validatieregel (op naamgevingsconventies) kan voorzien worden van een uitzondering: sla GM_SENTINEL over.

Is nu doorgevoerd

**Comment by melsk-r** [comment]
Ik neem aan dat je bedoelt dat deze **NIET** nodig is als  er geen enkele referentie is gemaakt naar een construct in GML.

Dank je voor het doorvoeren van de correctie. Ik zal kijken of ik deze week even kan testen of de melding inderdaad niet meer voorkomt.

**Comment by melsk-r** [comment]
Akkoord!
