### ISSUE TITLE
Onbekende foutmeldingen in 4.1

### ISSUE THREAD

**Issue by WijnandIHW** [Imvertor/Imvertor-Maven#518]
Ik krijg foutmeldingen in de 4.1 die ik niet kreeg in de 4.0:
<img width="545" alt="image" src="https://github.com/user-attachments/assets/45c305f4-825a-4dc1-9c10-63a34cfcb852">
Daarnaast is de foutmelding voor mij te vaag om eenvoudig op te lossen.

**Comment by ArjanLoeffen** [comment]
Deze melding is het gevolg van een aantal uitgaande relaties dat dezelfde naam heeft. Dat is niet conform MIM. Zie https://docs.geostandaarden.nl/mim/mim/#uniekheid-van-namen-van-modelelementen

**Comment by WijnandIHW** [comment]
Ok, thx. Ik zie dat er een aantal uitgaande relaties wel bestaan, maar niet zichtbaar zijn in diagram
