### ISSUE TITLE
Strings mogen leeg of niet-leeg zijn

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#52]
Dit regelen voor iedere XML schema methode. Voor Kadaster schema: niet leeg. Voor NEN3610 GML schema's: leeg is okay. Voor BRO schema's: leeg is okay.

**Comment by ArjanLoeffen** [comment]
Er is een schemarules parameter opgenomen: strings-nonempty:
```
    <!-- specify if strings must be non-empty -->
    <parameter name="strings-nonempty">false</parameter>
```
Als true, dan wordt een patroon toegevoegd op alle strings waarbij wordt afgedwongen dat een waarde altijd met een non-space character begint.
* Alle ISO19136 schema's: false
* Kadaster specifieke schemas: true.

**Comment by ArjanLoeffen** [comment]
Een niet-leeg element moet voldoen aan de regex `\S.*`.

BRO stelt voor `.+` te gebruiken als patroon voor "niet leeg", dus wel toestaan een space character bij start op te nemen.
Ik denk dat het niet goed is om `.+`  op te nemen omdat ik veronderstel dat een spatie aan het begin van een waarde nooit correct is. 
Als dat in sommige gevallen wel van toepassing is, of als je dat toch zelf wil kunnen bepalen kunnen we daar ook een keuze voor introduceren in de configuratie.  

@ThijsKnapen graag je reactie?

**Comment by ThijsKnapen** [comment]
Hoi Arjan,

Je geeft aan _BRO stelt voor `.+` te gebruiken als patroon voor "niet leeg"_
Dat was mijn persoonlijke gedachte, niet zozeer BRO gedragen. Ik zal ook dit eens voorleggen binnen het BRO Standaarden team om te kijken hoe anderen hier tegenaan kijken.

**Comment by ThijsKnapen** [comment]
Hoi Arjan,

Ik heb een meeting ingepland met de analisten van BRO Standaardisatie om het hierover te hebben. Ik kom er hopelijk woensdag op terug!

**Comment by ThijsKnapen** [comment]
Hoi Arjan,

Ik heb bovenstaande besproken binnen het BRO Standaardisatie team met de analisten. Twee items daaruit;
1) Aangezien er reeds de mogelijkheid is om via de TV 'Mogelijk geen waarde' de nillable eigenschap van een element te sturen, zien zij geen meerwaarde om lege tekststrings binnen de BRO toe te staan. Echter, omdat het toevoegen van deze regex pattern restriction direct de XSDs raakt, wil ik dit eerst met het LV_BRO team bespreken of zij dit ook zien zitten.
--> **Vooralsnog dus geen verzoek tot wijziging**.
2) In het geval dat er opvolging zou komen aan eerdere punt, vond men het een wenselijke aanvulling om naast zuiver 'niet leeg', ook direct af te dwingen dat een tekst waarde niet met whitespace characters mag beginnen **of eindigen**. In de het huidige patroon `\S.*` wordt enkel afgedwongen dat een waarde niet met een whitespace character kan beginnen. Daarom leek ons vanuit de BRO het patroon `(\S.*\S|\S)` beter. 
N.b. dat is ervan uitgaande dat in een gml regex pattern restriction al standaard de gehele pattern wordt gedicteerd (geen gedeeltelijke match). In een regex tester is dat veelal niet het geval, en om af te dwingen dat je de gehele string matcht moet je dan `^` (start of string) en `$` (end of string) toevoegen, en zou de regex pattern dus `^(\S.*\S|\S)$` worden.

**Comment by ArjanLoeffen** [comment]
Om dat de bestaande situatie niet mag worden "doorbroken" stel ik het volgende voor.
De parameter
`<parameter name="strings-nonempty">true</parameter>`
wordt vervangen door  
`<parameter name="regex-nonempty">\S.*</parameter>`
of
`<parameter name="regex-nonempty">\S.*\S|\S</parameter>`
(Al naar gelang de interpretatie van "correct gevuld".)
De code tast deze waarde af. Als een regex zoals hier getoond is opgegeven, wordt deze toegepast; anders vervalt de constraint.
Dus bij
`<parameter name="regex-nonempty"/>`
of afwezigheid van deze parameter is er geen beperking op de inhoud van een string.

@ThiesMesdag dit heeft dus geen impact op de huidige schema's van Kadaster.

**Comment by ThijsKnapen** [comment]
Hoi Arjan,

Dat lijkt mij een prima aanpak. Weet dus wel dat ik eerst nog met de LV_BRO bespreek of deze wijziging ook voor hen haalbaar is.

**Comment by ThiesMesdag** [comment]
Ja, lijkt mij prima.

**Comment by PalmJanssen** [comment]
Ter info:
Ik zag dit voorbijkomen en deed me denken aan een constraint die we bij IMRO hebben gebruikt om restricties op een string waarde op te nemen. De toepassing daarvan in xml was deze:

	
	<simpleType name="NotEmptyString">
		<restriction base="string">
			<pattern value="[^ \t\r\n]{1}.*"/>
			
			
		</restriction>
	</simpleType>

**Comment by ThijsKnapen** [comment]
Ok, dus eigenlijk zelfde type pattern als in Imvertor zat; '\S.*'
Zie ook; https://www.regular-expressions.info/shorthand.html;
`\s stands for “whitespace character”. Again, which characters this actually includes, depends on the regex flavor. In all flavors discussed in this tutorial, it includes [ \t\r\n\f]. That is: \s matches a space, a tab, a carriage return, a line feed, or a form feed. Most flavors also include the vertical tab, with [Perl](https://www.regular-expressions.info/perl.html) (prior to version 5.18) and [PCRE](https://www.regular-expressions.info/pcre.html) (prior to version 8.34) being notable exceptions.`

Punt dat ik aanhaalde is dat een spatie in theorie ook een niet lege string is, en dat de regex een stapje verder gaat en aangeeft dat dat type string niet wenselijk is. De uitbreiding is dus dat een whitespace aan het begin niet wordt toegestaan, maar aan het eind wel. Het leek ons logischer dat als je dan toch al deze uitbreidingsstap maakt, om dan ook whitespace aan het eind van een tekststring niet toe te staan.

**Comment by ThijsKnapen** [comment]
Ik heb dit punt afgestemd met het LV_BRO team. Zij zien dit soort validaties liever niet terug in de XSD, maar valideren dit liever in eigen software zodat ze er een eigen foutmelding over terug kunnen geven.

Voor de BRO blijft deze validatieactie dus vooralsnog iets in de software van de LV_BRO, en blijven we hanteren om geen regex pattern restriction in de XSDs te zetten.
