### ISSUE TITLE
BRO: Onterechte foutmelding over gebruik stereotype 'enumeratiewaarde'

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#524]
In Imvertor 4.1 en de nightly build verschijnen onverwachte foutmeldingen, als volgt:

`Attribute with stereotype "ENUMERATIEWAARDE" must not appear here, expecting (any of) "ENUMERATIE"`

en, als variant erop:

`Attribute with stereotype "ENUMERATIEWAARDE", "IMBRO/A" must not appear here, expecting (any of) "ENUMERATIE"`

Het zijn onterechte foutmeldingen, want het betreft daadwerkelijke enumeratiewaarden. Bijv. het element 'Mijnbouwconstructies (EPC) - conceptueel Model::BoortrajectCategorie.primair (attrib)'. Hierin is 'BoortrajectCategorie' gerstereotypeerd als 'CodeLijst' (EA type = DataType).

**Comment by ArjanLoeffen** [comment]
Heb je een job nummer voor me?

**Comment by ArjanLoeffen** [comment]
Tav. 2/:

De melding is vervangen door: 
_Attribute with stereotype "ENUMERATIEWAARDE", "IMBRO/A" must not appear here, but as attribute of (any of) "ENUMERATIE"_
In dat geval is de melding juist / conform MIM 1.2.

**Comment by jacobvosimpronotion** [comment]
@ArjanLoeffen In de melding die je voorstelt, komt niet tot uitdrukking dat "enumeratiewaarde" niet past bij "codelijst". Het wijst de gebruiker daarmee niet op wat er fout zit in het aangeboden model.

**Comment by ArjanLoeffen** [comment]
Jacob, je vraagt nu om in de melding te zeggen: Codelijst kan geen UML attribuut hebben (dus ook geen enumeratieve waarden). Imvertor heeft nog niet zo'n logica, maar zegt: ik tref een UML attribuut aan met een niet toegestaan stereotype. We kunnen een regel toevoegen die (ook) zegt: 

_Class with stereotype "CODELIJST" may not have any attributes._

Is dat wat je bedoelt?

**Comment by jacobvosimpronotion** [comment]
@ArjanLoeffen Ja, inderdaad.

**Comment by jacobvosimpronotion** [comment]
@ArjanLoeffen Ik zie dat dit nog niet is aangepast. Wordt dit een aanpassing op lange termijn?

**Comment by ArjanLoeffen** [comment]
Wegens de impact van de door jou voorgestelde verandering geef ik als optie om de melding te veranderen in:

_Attribute with stereotype "ENUMERATIEWAARDE", "IMBRO/A" must not appear here. It can only appear as attribute of (any of) "ENUMERATIE"_

Is dat acceptabel?

**Comment by jacobvosimpronotion** [comment]
Zojuist getest met nightly build, en het is opgelost.
