### ISSUE TITLE
BRO: Onterechte waarschuwing m.b.t. de tag 'Herkomst definitie'

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#525]
Zowel in Imvertor 4.1 als in de nightly build verschijnen waarschuwingen à la:

`Tagged value "Herkomst definitie" not expected on stereotype "DOMEIN"`

Conform de MIM 1.2 standaard is ‘herkomst definitie’ overal toegestaan waar ‘definitie’ is toegestaan (https://docs.geostandaarden.nl/mim/mim/#metagegeven-herkomst-definitie) en dat is bij alle modelelementen (https://docs.geostandaarden.nl/mim/mim/#metagegeven-definitie).

Dus de waarschuwing lijkt me onterecht.

**Comment by ArjanLoeffen** [comment]
Dat klopt, het is hersteld in 4.1 en development.

**Comment by jacobvosimpronotion** [comment]
Prima, daarmee afgesloten.
