### ISSUE TITLE
Generalisatie niet in de mim serialisatie

### ISSUE THREAD

**Issue by fzand** [Imvertor/Imvertor-Maven#536]
Generalisatie komt niet door in de mim serialisatie.

**Comment by ArjanLoeffen** [comment]
Hij komt zover ik kan zien wel door. 
In deze situatie:
![image](https://github.com/user-attachments/assets/13adc3d9-356a-4918-875f-b44fb6668e7c)

Krijg je in de MIM serialisatie:
```
 <mim:Objecttype index="1471" id="E2C93214_90E2_4151_B719_7BB8CDF8679F">
               <mim:naam>ExterneProducent</mim:naam>
               ...
               <mim:supertypen>
                  <mim:GeneralisatieObjecttypen index="1494" id="7DF5E004_E635_4dd9_8374_2DE2C1942799">
                     <mim:supertype>
                        <mim-ref:ObjecttypeRef index="1494" xlink:href="#04EED45C_4D30_41b9_83EE_65237E1F8E27">Producent</mim-ref:ObjecttypeRef>
                     </mim:supertype>
                  </mim:GeneralisatieObjecttypen>
               </mim:supertypen>

```

**Comment by fzand** [comment]
https://stelselcatalogius-logius-131732222fffeb0a88ba8dd4b6fc81ba720237.gitlab.io/respec/index.html#global_class_Stelselcatalogus_Registratie

Ik zie in EA dat mijn generalisaties weinig tagged valeus hebben en dat ik deze geen waarde heb gegeven. Daarnaast is mijn supertype abstract. Maakt dat uit?

**Comment by fzand** [comment]
Nadat ik de generalisaties een naam en een datumOpname heb gegeven komen de mim serialisatie wel door.
