### ISSUE TITLE
Volgorde van diagrammen

### ISSUE THREAD

**Issue by WijnandIHW** [Imvertor/Imvertor-Maven#537]
Een paar van onze diagrammen staan op hetzelfde niveau, maar verschillen in detailniveau (LOD0 en LOD1). De weergave is willekeurig. Hoe kunnen we aan een diagram een volgorde of positie meegeven?

**Comment by ArjanLoeffen** [comment]
Kun je een voorbeeld geven?

**Comment by WijnandIHW** [comment]
In https://aquo-standaard.github.io/IMWA-WS/#global_package_Watersysteem moet de volgorde van de diagrammen zijn LoD0 en daarna LoD1. Watersysteem heeft 5 LoD0 diagrammen en 5 LoD1 diagrammen. Deze staan nu door elkaar en dat is onoverzichtelijk.

**Comment by ArjanLoeffen** [comment]
De oplossing lijkt eenvoudig. Als je diagrammen plaatst in EA wordt de opvolging niet als relevant opgevat. Totdat je op de opvolgingspijltjes drukt, zoals hier:

![image](https://github.com/user-attachments/assets/ecdc63a7-c592-4f4c-9e06-9a4b1b8d4c70)

Als je die heen en weer schuift begrijpt EA ineens dat er wel een orde zit in de diagrammen. Imvertor leest die volgorde uit.

**Comment by WijnandIHW** [comment]
Top, bedankt
