### ISSUE TITLE
Schrappen validatie Multiple inheritance bij catalogus genereren Conceptueel Model

### ISSUE THREAD

**Issue by adbgnm** [Imvertor/Imvertor-Maven#54]
_Aanleiding:_ 
Voor het BRO _conceptueel_ model Bodemkaart is het noodzakelijk dat de BRO-objecttypen Bodemlaag/Bodemhorizont zowel een specialisatie zijn van BRO-objecttype Profiellaag als INSPIRE featureType SoilLayer/SoilHorizon. 

![image](https://user-images.githubusercontent.com/10595039/48411856-2555b880-e743-11e8-94d5-15eb4284cb20.png)

De generalisatie-relaties van Bodemlaag/Bodemhorizont/Profiellaag naar INSPIRE klassen hebben stereotype Static (overgenomen uit IMKAD UML Profile)  (label is verborgen in diagram).

_Verwacht resultaat:_ 
Multiple inheritance is een geldige UML-constructie en geeft pas problemen bij vertaling naar logisch model. Voor conceptueel model zou verwijzing van één objectklasse naar 2 supertypen mogelijk moeten zijn om zo catalogus-output via Imvertor te kunnen genereren

_Werkelijk resultaat:_
Imvertor geeft de volgende foutmeldingen:
![image](https://user-images.githubusercontent.com/10595039/48411979-96956b80-e743-11e8-89d1-902089e6ca41.png)

_Oplossingsrichting_:
Verzoek om de validatie op multiple inheritance te schrappen bij een conceptueel model.

**Comment by ArjanLoeffen** [comment]
Gedaan. Dit is nu geconfigureerd middels een feature 
```<feature name="allow-multiple-supertypes">false</feature>```
Dit is per metamodel anders.
