### ISSUE TITLE
De mim-prefix zou http moeten zijn ipv https.

### ISSUE THREAD

**Issue by fzand** [Imvertor/Imvertor-Maven#546]
dus

@prefix mim: <http://modellen.mim-standaard.nl/def/mim/#> .

ipv

@prefix mim: <https://modellen.mim-standaard.nl/def/mim/#> .

zie https://docs.geostandaarden.nl/mim/mim/media/mim.ttl

**Comment by ArjanLoeffen** [comment]
Gecorrigeerd in nightly build van 1 okt 2024

**Comment by fzand** [comment]
In orde.
