### ISSUE TITLE
BRO: Referentielijst wordt niet gevonden op GitHub

### ISSUE THREAD

**Issue by jacobvosimpronotion** [Imvertor/Imvertor-Maven#548]
De werking van de tag 'Locatie' bij een Referentielijst i.c.m. de tag 'Afkorting' bij een Basismodel is wat betreft het opnemen van die referentielijst in een catalogus anders dan verwacht.

O.b.v. informatie in https://github.com/Imvertor/Imvertor-Maven/issues/540 is die verwachting als volgt:

- als
-- bij een Referentielijst de tag 'Locatie' leeg is
-- en
-- bij het Basismodel de tag 'Afkorting' gevuld is
- dan
-- wordt de lijst met waarden om in de catalogus op te nemen gezocht op: `<basis URI van het informatiemodel> + "/" + <afkorting> + "/gh-pages/lists/" + <naam Referentielijst> + ".xml"`

Dus gegeven:

- basis URI van BRO = https://raw.githubusercontent.com/BROprogramma/
- Afkorting = SLD
- Naam referentielijst = Aanpak

wordt als bestand verwacht: https://raw.githubusercontent.com/BROprogramma/SLD/gh-pages/lists/Aanpak.xml

Dit bestand is aanwezig.

Maar: bij het genereren van de catalogus (met Imvertor 3.0) verschijnt als foutmelding voor element 'Model::Aanpak = Approach': "`Codelist content location not specified xsl/OfficeCompiler/Imvert2modeldoc-lists.xsl / xsl/OfficeCompiler/Imvert2modeldoc-lists.xsl`".

N.B.: De 'codelist' is dus hier een Referentielijst.

Wat gaat hier fout? Ik heb ook op het Domein-package de tag 'Afkorting' ingesteld, maar dat was niet de oplossing.

**Comment by ArjanLoeffen** [comment]
Nee, de naam van de lijst zoals die voorkomt in de EA speelt nu geen rol. Het gaat om de waarde die is ingevoerd als tagged value _Locatie_, zoals in:

![image](https://github.com/user-attachments/assets/46b26111-ab44-4b01-86ff-f2596b411e04)

We kunnen wel besluiten om de Parameterlijst naam van de referentielijst te gaan gebruiken als alternatief voopr de naam of de URL zoals ingveoerd als waarde van de tagged value Locatie. Dat zou een uitbreiding zijn van de logica. Echter, hou er rekening mee dat dit zich dan onmiddellijk vertaalt naar een filenaam. Dat is niet zo fijn, omdat je onafhankelijk wilt zijn van filenaam conventies op het host systeem. Maar daar kunnen we ook wel een afspraak over maken.

Hoe dan ook, mijn voorstel zou zijn de tv _Locatie_ altijd met URL of met een filenaam te vullen. Voor "locatie" is een afhankelijkheid van filenaam conventies wel acceptabel.

**Comment by jacobvosimpronotion** [comment]
Ik begrijp nu hoe het werkt en dat is voldoende. Aanpassing is (i.i.g. nu) niet nodig.

Bij de referentielijst 'Aanpak' kan ik als Locatie invullen waarna het door Imvertor wordt herkend:
- Aanpak
- https://raw.githubusercontent.com/BROprogramma/SLD/gh-pages/lists/Aanpak
- https://raw.githubusercontent.com/BROprogramma/SLD/gh-pages/lists/Aanpak.xml

N.B.: Aanpak.xml werkt niet, want dan wordt naar /Aanpak.xml.xml gezocht.

**Comment by ArjanLoeffen** [comment]
Kijk dat is interessant; ik dacht dat we .xml extensies altijd verwijderden, dus dat .xml.xml niet kan voorkomen. Ik check dat nog even.

**Comment by ArjanLoeffen** [comment]
De aanpak wat betreft de .xml extensie is als volgt:

- Als de Locatie het patroon `https?://.*?\.xml` volgt, dan is dat een URL en wordt die gelezen voor het ophalen van de data.
- In andere gevallen wordt de parameter `doclist-xml-url` gebruikt, met de beschreven vervanging van variabelen, dus ook de naam die is ingevoerd als waarde van Locatie.

Voorbeeld voor BRO:
`<parameter name="doclist-xml-url">https://raw.githubusercontent.com/BROprogramma/[appinfo/model-abbreviation]/gh-pages/lists/[temp/latest-list-key].xml</parameter>`
 
`https://raw.githubusercontent.com/BROprogramma/EPL/gh-pages/lists/GeologischeEenheid.xml`
wordt gelezen.

`GeologischeGrondsoort`
wordt omgezet naar https://raw.githubusercontent.com/BROprogramma/SAMPLE/gh-pages/lists/GeologischeGrondsoort.xml en die wordt gelezen.

`https://raw.githubusercontent.com/BROprogramma/EPL/gh-pages/lists/GeologischeEenheid`
Hiervan wordt _GeologischeEenheid_ begrepen als de latest-list-key, Die wordt ingevoegd in de doclist-xml-url.  Dat elvert in de praktijk geen bestaande lijst op: `https://raw.githubusercontent.com/BROprogramma/SAMPLE/gh-pages/lists/GeologischeEenheid.xml`

De verdubbeling van .xml kan ik dus niet thuisbrengen. Tenzij je alleen "Aanpak.xml" bet opgevoerd als waarde van Locatie, dan heeft dat het beschreven effect.

**Comment by jacobvosimpronotion** [comment]
Quote: "Tenzij je alleen "Aanpak.xml" hebt opgevoerd als waarde van Locatie, dan heeft dat het beschreven effect."

Ja, dat schreef ik ook: "Aanpak.xml werkt niet".
