### ISSUE TITLE
Onjuiste generatie van primitieve types ISO19136

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#68]
Kadaster: In het package KIMBAG-Adres zit een primitief datatype Indicatie.
Dit wordt in de XSD:

```
       <xs:element name="Indicatie" type="KIMBAGAdres:IndicatieType"/>

       <xs:complexType name="IndicatieType"/>

       <xs:complexType name="IndicatiePropertyType">
             <xs:sequence minOccurs="0">
                    <xs:element ref="KIMBAGAdres:Indicatie"/>
             </xs:sequence>
       </xs:complexType>
```

Maar was is het type nou? xs:String was verwacht (met een pattern J | N).

**Comment by ArjanLoeffen** [comment]
@ThiesMesdag Speelt dit nog? Zo niet dan graag sluiten....

**Comment by ThiesMesdag** [comment]
In huidige CDMKAD en IMKAD is het inderdaad als string met patroon J|N gegenereerd.

**Comment by ThiesMesdag** [comment]
Is opgelost
