### ISSUE TITLE
Codelijsten

### ISSUE THREAD

**Issue by HanWelmer** [Imvertor/Imvertor-Maven#69]
Sinds enige tijd geven geeft IMVertor bij een toegestane waarde van een bestaande codelijst een waarschuwing. Dit wordt waarschijnlijk veroorzaakt doordat bij een Referentielijst (dat is dus niet een codelijst!) de URL (http://standaard.aquo.nl/id/domeintabel/Parameterlijst) in de tagged value location wordt getraced. Bestaande codelijsten hebben daar een naam staan of een URN.

Voorstel is de tagged value Location niet te tracen bij een Codelijst (in tegenstelling tot Referentielijst) of de tagged value Location niet te tracen als dit een URN is (bijvoorbeeld urn:bro:bhrgt:SamplingQuality) in plaats van een URL (b.v. http://standaard.aquo.nl/id/domeintabel/Parameterlijst).

**Comment by ArjanLoeffen** [comment]
Ik ga ervan uit dat de regel kan zijn: 

> als start met urn: dan niet de codelijst inhoud ophalen. In andere gevallen wel, dus de geïmplementeerde strategie volgen.

Dit is nu zo geïmplementeerd.

**Comment by ArjanLoeffen** [comment]
Kunnen we deze sluiten?

**Comment by HanWelmer** [comment]
Tested. OK.
