### ISSUE TITLE
Conceptual Schemas in Imvertor report

### ISSUE THREAD

**Issue by HanWelmer** [Imvertor/Imvertor-Maven#70]
Hoofdstuk 3 van het Imvertor Report, Configuration, heeft al wel een hoofdstukkopje Conceptual schemas maar de inhoud van dat hoofdstuk is nog leeg.

Is het mogelijk hierin op te nemen de definities uit het configuratiebestand conceptualschemas.xml? Dat zou voor modelleurs inzichtelijk maken welke externe modellen er beschikbaar zijn en welke modelelementen zij kunnen gebruiken.

**Comment by ArjanLoeffen** [comment]
Dit is gemaakt in 1.52.3. Graag jullie commentaar.
