### ISSUE TITLE
Meerdere modellen tegelijkertijd verwijderen van Imvertor server

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#76]
Als beheerder van de VNG-Realisatie modellen op de Imvertor server wil ik graag meerdere bestanden tegelijkertijd verwijderen in het modellen scherm van het dashboard.

Nu moet ik steeds 1 model aanklikken waarna ik het vervolgens kan verwijderen. Daarna moet ik weer naar het modellen overzicht en daar weer zoeken naar de locatie waar ik was gebleven. Dit is erg tijdsintensief.

Ik kan me voorstellen dat deze wens conflicteert met de wens om heel voorzichtig te zijn met het verwijderen van modellen. Het zou echter fijn zijn als er wordt gekeken wat binnen die grenzen toch mogelijk is.

**Comment by ArjanLoeffen** [comment]
**Dit issue betreft Imverrtor SAAS en niet de Imvertor OS. 
Het moet worden verplaatst naar Amatiek Solutions Redmine.**

**Comment by ArjanLoeffen** [comment]
Wordt overgenomen in https://armatiek-solutions.plan.io/issues/120
