### ISSUE TITLE
Eigenaar van een model zichtbaar maken in scherm met modellen

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#77]
Als beheerder van de VNG Realisatie modellen wil ik graag bij elk model in de lijst met modellen van het dashboard in 1 oogopslag kunnen zien wie de eigenaar is. Dit mag middels een configuratie ingesteld worden.

**Comment by ArjanLoeffen** [comment]
**Dit issue betreft Imverrtor SAAS en niet de Imvertor OS. 
Het moet worden verplaatst naar Amatiek Solutions Redmine.**

**Comment by ArjanLoeffen** [comment]
Overgenomen in https://armatiek-solutions.plan.io/issues/121
