### ISSUE TITLE
Maak het mogelijk om achteraf de eigenaar van een model nog te benoemen of te wijzigen.

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#78]
Als beheerder van de VNG Realisatie modellen op de imvertor server wil ik graag de eigenaar van een model kunnen benoemen.
Nu komt het soms voor dat een model geen eigenaar heeft en dat geldt niet alleen voor oude modellen. In dat geval wil ik dat alsnog kunnen benoemen.

**Comment by ArjanLoeffen** [comment]
**Dit issue betreft Imvertor SAAS en niet de Imvertor OS. 
Het moet worden verplaatst naar Armatiek Solutions Redmine.**

**Comment by ArjanLoeffen** [comment]
Overgenomen in https://armatiek-solutions.plan.io/issues/122
