### ISSUE TITLE
Breidt de ondersteunde set met baretypes uit met MAAND en DAG

### ISSUE THREAD

**Issue by melsk-r** [Imvertor/Imvertor-Maven#83]
In een van onze modellen in EA bevat het complex datatype 'datum_onvolledig' de volgende attributen:

![afbeelding](https://user-images.githubusercontent.com/20185784/59667869-c1531100-91b7-11e9-9874-d12f841e867a.png)

Zoals je ziet hebben de attributen 'jaar' en 'datum' de types 'JAAR' resp. 'DATUM'. Op basis daarvan kan via/via in het yaml bestand 'format: "date_fullyear"' en 'format: "date"' gedefinieerd worden.
Voor de attributen 'maand' en 'dag' willen we ook  zo iets kunnen doen en willen we in EA dus de types 'MAAND' en 'DAG' kunnen toekennen wat in het embellish bestand vertaald moet worden naar:
* &lt;imvert:baretype>MAAND&lt;/imvert:baretype>
&lt;imvert:type-name>scalar-month&lt;/imvert:type-name>
* &lt;imvert:baretype>DAG&lt;/imvert:baretype>
&lt;imvert:type-name>scalar-day&lt;/imvert:type-name>

Zodra dat gebeurd is kan ik de betreffende YamlCompiler stylesheets daarop aanpassen.

**Comment by ArjanLoeffen** [comment]
Deze aanpassing heb ik gedaan in

> /Imvertor-Chains/src/main/resources/input/KING/cfg/metamodels/KINGUGM.xml
> /Imvertor-Chains/src/main/resources/input/KING/cfg/metamodels/KINGSIM.xml

We zouden dit ook kunnen verplaatsen naar BP-scalars. Ale scalaire typen komen uit de BP configuratie. Maar we kunnen ook wachten tot blijkt dat iedereen die op BP geënt is deze toevoegingen wil hebben.

**Comment by ArjanLoeffen** [comment]
Robert graag testen en sluiten.

**Comment by melsk-r** [comment]
Ziet er goed uit. Ik kan nu inderdaad realiseren wat ik wilde realiseren.
