### ISSUE TITLE
Gebruik van superscript en subscript

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#96]
We willen in de BRO-catalogi gebruik kunnen maken van superscript en subscript, zodat we CO2 en X2 als CO<sub>2</sub> en X<sup>2</sup> kunnen tonen. Het notes-field van EA bevat die optie, maar ergens verdwijnt deze opmaak.

**Comment by ArjanLoeffen** [comment]
Dit is nu toegevoegd. 
Opmerking: BRO hanteert Markdown in de notes fields, en accepteert HTML syntactic suger. Dus bepaalde HTML wordt begrepen (bold, italic, en nu dus ook super en subscript) en door imvertror voor de auteur omgezet naar martkdown. Maar je kunt erg veel opmaak bereiken als je zuivere markdown hanteert. Voorbeeld:

![afbeelding](https://user-images.githubusercontent.com/12828217/73097853-72592100-3ee8-11ea-8d0c-b06c73235fda.png)

**Comment by WijnandvanRiel** [comment]
Ziet er goed uit!
