### ISSUE TITLE
Indicatie Materiële Historie bij rapportage over Relatierol ontbreekt

### ISSUE THREAD

**Issue by WijnandvanRiel** [Imvertor/Imvertor-Maven#97]
Enkele stereotypes hebben de tagged-value 'indicatie materiële historie'. In de Imvertor-rapportage wordt bij Attribuutsoort ook gerapporteerd over deze tagged-values. Bij 'relatierol' ontbreekt de Imvertor-rapportage over deze tagged-value.

**Comment by ArjanLoeffen** [comment]
Ik snap deze opmerking niet. Er wordt helemaal geen documentatie opgesteld  voor relaties. Waar zou je deze waarde verwachten?

**Comment by WijnandvanRiel** [comment]
Dag Arjan,
Het issue is aangedragen door Han en het is bij nader inzien iets te beperkt beschreven.
In hfst. 11 van de Imvertor rapportage staat een lijst met de voorkomens van tagged values. Hier staat bij een aantal ‘tagged values occurs on = target’. In het tweede deel van hfst. 11 is echter geen rapportage opgenomen over ‘target’. Omdat target in het eerste deel van hfst 11 staat hadden we de verwachting dat het in het tweede deel zou voorkomen.
Dus de vraag is, hoeveel inspanning kost het om de rapportage uit te breiden met de tagged values van association targets?

Met groet,
Wijnand

**Comment by ArjanLoeffen** [comment]
Ik heb het toegevoegd. De rol (target van de relatie) is weergegeven als hieronder:
![afbeelding](https://user-images.githubusercontent.com/12828217/73391814-f80a1180-42d8-11ea-8ab9-9a76d8f5790c.png)
Beschikbaar in 1.58 vanaf 30 jan.

**Comment by HanWelmer** [comment]
Gebruikte tagged values bij relatietragte worden nu gerpporteerd in hoofdstuk 11 van het Imvertor report.
![image](https://user-images.githubusercontent.com/45099757/73857925-e922e200-4837-11ea-9f80-69118b928025.png)
